additional-dependency-files:
  - type: npm-package-json
    path: apps/app/package.json
  - type: npm-package-json
    path: apps/web/package.json
  - type: npm-package-json
    path: packages/aws-user-migrate/package.json
  - type: npm-package-json
    path: packages/config/package.json
  - type: npm-package-json
    path: packages/db/package.json
  - type: npm-package-json
    path: packages/eslint-config/package.json
  - type: npm-package-json
    path: packages/types/package.json
  - type: npm-package-json
    path: packages/ui/package.json
ignore-failures:
  javascript:
    - iso-3166-2
    - countries-languages
    - cuid
    - flat
    - langs
