version: '2'
plugins:
  tslint:
    enabled: true
    config: '.github/tslint.json'
  duplication:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  git-legal:
    enabled: true
  scss-lint:
    enabled: true
checks:
  file-lines:
    config:
      threshold: 300
  method-lines:
    config:
      threshold: 100
  similar-code:
    config:
      threshold: 175
  identical-code:
    config:
      threshold: 50
exclude_patterns:
  - '.vercel/'
  - '**/.next/'
  - '**/dist/'
  - '**/node_modules'
  - 'test/'
  - 'patches/'
