version = 1

exclude_patterns = ["docs/database"]

[[analyzers]]
	enabled = true
	name    = "javascript"

	[analyzers.meta]
		environment = ["nodejs"]
		plugins     = ["react"]

[[analyzers]]
	enabled = true
	name    = "secrets"

[[transformers]]
	enabled = false
	name    = "prettier"
