version = 1

exclude_patterns = ["docs/database"]

[[analyzers]]
name = "javascript"
enabled = true

[analyzers.meta]
plugins = ["react"]

[[analyzers]]
name = "secrets"
enabled = true

[[transformers]]
name = "prettier"
enabled = true
