version = 1

exclude_patterns = [
	"**/generated/**",
	"*.code-workspace",
	"packages/db/.snaplet/**",
	"packages/db/prisma/data-migrations/**",
	"packages/db/prisma/migrations/**",
	"packages/db/prisma/views/**",
	"packages/ui/icon/iconList.ts",
	"packages/ui/mockData/json/**",
]

[[analyzers]]
	enabled = true
	name    = "javascript"

	[analyzers.meta]
		environment = ["nodejs"]
		plugins     = ["react"]

[[analyzers]]
	enabled = true
	name    = "secrets"

[[transformers]]
	enabled = false
	name    = "prettier"
