import { type ApiOutput, type ApiInput } from '@weareinreach/api'

export const attributeCategories = [
	{
		id: 'attc_01GW2HHFV3DJ380F351SKB0B74',
		tag: 'additional-information',
		name: 'Additional Information',
		icon: null,
		intDesc: 'Misc',
	},
	{
		id: 'attc_01GXS3AYEER4CCSX670S9Z84EB',
		tag: 'alerts',
		name: 'Alerts',
		icon: null,
		intDesc: 'Alert messages',
	},
	{
		id: 'attc_01GW2HHFVFKNMYPN8F86M0H576',
		tag: 'cost',
		name: 'Cost',
		icon: null,
		intDesc: null,
	},
	{
		id: 'attc_01GW2HHFVGHPW1Y72SA8377623',
		tag: 'eligibility-requirements',
		name: 'Eligibility Requirements',
		icon: null,
		intDesc: null,
	},
	{
		id: 'attc_01GW2HHFVJQQ68XGSBXM976BDF',
		tag: 'languages',
		name: 'Languages',
		icon: null,
		intDesc: null,
	},
	{
		id: 'attc_01GW2HHFVRSN3W3GYZZ43WCW24',
		tag: 'law-practice-options',
		name: 'Law Practice Options',
		icon: null,
		intDesc: null,
	},
	{
		id: 'attc_01GW2HHFVMNHV2ZS5875JWCRJ7',
		tag: 'organization-leadership',
		name: 'Organization Leadership',
		icon: null,
		intDesc: null,
	},
	{
		id: 'attc_01GW2HHFVKAMMGPD71H90XRJ38',
		tag: 'service-access-instructions',
		name: 'Service Access Instructions',
		icon: null,
		intDesc: null,
	},
	{
		id: 'attc_01GW2HHFVNXMNJNV47BF2BPM1R',
		tag: 'service-focus',
		name: 'Service Focus',
		icon: null,
		intDesc: null,
	},
	{
		id: 'attc_01GW2HHFVSQWE2Y2RF3DT2VEYX',
		tag: 'service-provider-options',
		name: 'Service Provider Options',
		icon: null,
		intDesc: null,
	},
	{
		id: 'attc_01GW2HHFVKM2PSHFWVFM0TWX1P',
		tag: 'system',
		name: 'System',
		icon: null,
		intDesc: null,
	},
] satisfies ApiOutput['fieldOpt']['attributeCategories']

export const attributesByCategory = [
	{
		categoryId: 'attc_01GW2HHFV3DJ380F351SKB0B74',
		categoryName: 'additional-information',
		categoryDisplay: 'Additional Information',
		attributeId: 'attr_01GW2HHFV3YJ2AWADHVKG79BQ0',
		attributeName: 'at-capacity',
		attributeKey: 'additional.at-capacity',
		attributeNs: 'attribute',
		badgeRender: 'ATTRIBUTE',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFV3DJ380F351SKB0B74',
		categoryName: 'additional-information',
		categoryDisplay: 'Additional Information',
		attributeId: 'attr_01GW2HHFV4D5ZHFMAE7852GB4P',
		attributeName: 'geo-near-public-transit',
		attributeKey: 'additional.geo-near-public-transit',
		attributeNs: 'attribute',
		badgeRender: 'ATTRIBUTE',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFV3DJ380F351SKB0B74',
		categoryName: 'additional-information',
		categoryDisplay: 'Additional Information',
		attributeId: 'attr_01GW2HHFV48VQJBMFA05QCBBV9',
		attributeName: 'geo-public-transit-description',
		attributeKey: 'additional.geo-public-transit-description',
		attributeNs: 'attribute',
		badgeRender: 'ATTRIBUTE',
		requireText: true,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFV3DJ380F351SKB0B74',
		categoryName: 'additional-information',
		categoryDisplay: 'Additional Information',
		attributeId: 'attr_01GW2HHFV3BADK80TG0DXXFPMM',
		attributeName: 'has-confidentiality-policy',
		attributeKey: 'additional.has-confidentiality-policy',
		attributeNs: 'attribute',
		badgeRender: 'ATTRIBUTE',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFV3DJ380F351SKB0B74',
		categoryName: 'additional-information',
		categoryDisplay: 'Additional Information',
		attributeId: 'attr_01GW2HHFV5Q7XN2ZNTYFR1AD3M',
		attributeName: 'offers-remote-services',
		attributeKey: 'additional.offers-remote-services',
		attributeNs: 'attribute',
		icon: 'carbon:globe',
		badgeRender: 'ATTRIBUTE',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFV3DJ380F351SKB0B74',
		categoryName: 'additional-information',
		categoryDisplay: 'Additional Information',
		attributeId: 'attr_01GW2HHFV4TM7H5V6FHWA7S9JK',
		attributeName: 'time-walk-in',
		attributeKey: 'additional.time-walk-in',
		attributeNs: 'attribute',
		badgeRender: 'ATTRIBUTE',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFV3DJ380F351SKB0B74',
		categoryName: 'additional-information',
		categoryDisplay: 'Additional Information',
		attributeId: 'attr_01GW2HHFV5FYXQNGTPAQB7G2TF',
		attributeName: 'wheelchair-accessible',
		attributeKey: 'additional.wheelchair-accessible',
		attributeNs: 'attribute',
		interpolationValues: {
			true: 'Accessible',
			false: 'Not Accessible',
		},
		icon: 'carbon:accessibility',
		badgeRender: 'ATTRIBUTE',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: true,
		requireData: false,
	},
	{
		categoryId: 'attc_01GXS3AYEER4CCSX670S9Z84EB',
		categoryName: 'alerts',
		categoryDisplay: 'Alerts',
		attributeId: 'attr_01GXS3AYESEMT09DW78G5X396D',
		attributeName: 'info',
		attributeKey: 'alerts.info',
		attributeNs: 'attribute',
		icon: 'carbon:information-filled',
		requireText: true,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GXS3AYEER4CCSX670S9Z84EB',
		categoryName: 'alerts',
		categoryDisplay: 'Alerts',
		attributeId: 'attr_01GXS3AYF9A67KMYVED2ZFG25G',
		attributeName: 'warn',
		attributeKey: 'alerts.warn',
		attributeNs: 'attribute',
		icon: 'carbon:warning-filled',
		requireText: true,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVFKNMYPN8F86M0H576',
		categoryName: 'cost',
		categoryDisplay: 'Cost',
		attributeId: 'attr_01GW2HHFVGWKWB53HWAAHQ9AAZ',
		attributeName: 'cost-fees',
		attributeKey: 'cost.cost-fees',
		attributeNs: 'attribute',
		icon: 'carbon:piggy-bank',
		badgeRender: 'ATTRIBUTE',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: true,
		dataSchemaName: 'numMinMaxOrRange',
		dataSchema: {
			anyOf: [
				{
					type: 'object',
					required: ['min'],
					properties: {
						min: {
							type: 'number',
						},
					},
				},
				{
					type: 'object',
					required: ['max'],
					properties: {
						max: {
							type: 'number',
						},
					},
				},
				{
					type: 'object',
					required: ['min', 'max'],
					properties: {
						max: {
							type: 'number',
						},
						min: {
							type: 'number',
						},
					},
				},
			],
			$schema: 'http://json-schema.org/draft-07/schema#',
		},
	},
	{
		categoryId: 'attc_01GW2HHFVFKNMYPN8F86M0H576',
		categoryName: 'cost',
		categoryDisplay: 'Cost',
		attributeId: 'attr_01GW2HHFVGDTNW9PDQNXK6TF1T',
		attributeName: 'cost-free',
		attributeKey: 'cost.cost-free',
		attributeNs: 'attribute',
		icon: 'carbon:piggy-bank',
		badgeRender: 'ATTRIBUTE',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVGHPW1Y72SA8377623',
		categoryName: 'eligibility-requirements',
		categoryDisplay: 'Eligibility Requirements',
		attributeId: 'attr_01GW2HHFVGSAZXGR4JAVHEK6ZC',
		attributeName: 'elig-age',
		attributeKey: 'eligibility.elig-age',
		attributeNs: 'attribute',
		interpolationValues: {
			max: 'Under {{max}}',
			min: '{{min}} and older',
			range: '{{min}} - {{max}}',
		},
		badgeRender: 'LIST',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: true,
		dataSchemaName: 'numMinMaxOrRange',
		dataSchema: {
			anyOf: [
				{
					type: 'object',
					required: ['min'],
					properties: {
						min: {
							type: 'number',
						},
					},
				},
				{
					type: 'object',
					required: ['max'],
					properties: {
						max: {
							type: 'number',
						},
					},
				},
				{
					type: 'object',
					required: ['min', 'max'],
					properties: {
						max: {
							type: 'number',
						},
						min: {
							type: 'number',
						},
					},
				},
			],
			$schema: 'http://json-schema.org/draft-07/schema#',
		},
	},
	{
		categoryId: 'attc_01GW2HHFVGHPW1Y72SA8377623',
		categoryName: 'eligibility-requirements',
		categoryDisplay: 'Eligibility Requirements',
		attributeId: 'attr_01GW2HHFVJDKVF1HV7559CNZCY',
		attributeName: 'other-describe',
		attributeKey: 'eligibility.other-describe',
		attributeNs: 'attribute',
		badgeRender: 'LIST',
		requireText: true,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVGHPW1Y72SA8377623',
		categoryName: 'eligibility-requirements',
		categoryDisplay: 'Eligibility Requirements',
		attributeId: 'attr_01GW2HHFVH9DPBZ968VXGE50E7',
		attributeName: 'req-medical-insurance',
		attributeKey: 'eligibility.req-medical-insurance',
		attributeNs: 'attribute',
		badgeRender: 'LIST',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVGHPW1Y72SA8377623',
		categoryName: 'eligibility-requirements',
		categoryDisplay: 'Eligibility Requirements',
		attributeId: 'attr_01GW2HHFVHZ599M48CMSPGDCSC',
		attributeName: 'req-photo-id',
		attributeKey: 'eligibility.req-photo-id',
		attributeNs: 'attribute',
		badgeRender: 'LIST',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVGHPW1Y72SA8377623',
		categoryName: 'eligibility-requirements',
		categoryDisplay: 'Eligibility Requirements',
		attributeId: 'attr_01GW2HHFVH0GQK0GAJR5D952V3',
		attributeName: 'req-proof-of-age',
		attributeKey: 'eligibility.req-proof-of-age',
		attributeNs: 'attribute',
		badgeRender: 'LIST',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVGHPW1Y72SA8377623',
		categoryName: 'eligibility-requirements',
		categoryDisplay: 'Eligibility Requirements',
		attributeId: 'attr_01GW2HHFVHEVX4PMNN077ASQMG',
		attributeName: 'req-proof-of-income',
		attributeKey: 'eligibility.req-proof-of-income',
		attributeNs: 'attribute',
		badgeRender: 'LIST',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVGHPW1Y72SA8377623',
		categoryName: 'eligibility-requirements',
		categoryDisplay: 'Eligibility Requirements',
		attributeId: 'attr_01GW2HHFVHGMVCAY1G5BWF1PFB',
		attributeName: 'req-proof-of-residence',
		attributeKey: 'eligibility.req-proof-of-residence',
		attributeNs: 'attribute',
		badgeRender: 'LIST',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVGHPW1Y72SA8377623',
		categoryName: 'eligibility-requirements',
		categoryDisplay: 'Eligibility Requirements',
		attributeId: 'attr_01GW2HHFVJH8MADHYTHBV54CER',
		attributeName: 'req-referral',
		attributeKey: 'eligibility.req-referral',
		attributeNs: 'attribute',
		badgeRender: 'LIST',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVGHPW1Y72SA8377623',
		categoryName: 'eligibility-requirements',
		categoryDisplay: 'Eligibility Requirements',
		attributeId: 'attr_01GW2HHFVGJ5GD2WHNJDPSFNRW',
		attributeName: 'time-appointment-required',
		attributeKey: 'eligibility.time-appointment-required',
		attributeNs: 'attribute',
		badgeRender: 'LIST',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVJQQ68XGSBXM976BDF',
		categoryName: 'languages',
		categoryDisplay: 'Languages',
		attributeId: 'attr_01GW2HHFVJGDDWTR5D0C8BY357',
		attributeName: 'all-languages-by-interpreter',
		attributeKey: 'lang.all-languages-by-interpreter',
		attributeNs: 'attribute',
		badgeRender: 'LIST',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVJQQ68XGSBXM976BDF',
		categoryName: 'languages',
		categoryDisplay: 'Languages',
		attributeId: 'attr_01GW2HHFVJF09GXY5N5CKMSANJ',
		attributeName: 'american-sign-language',
		attributeKey: 'lang.american-sign-language',
		attributeNs: 'attribute',
		badgeRender: 'LIST',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVJQQ68XGSBXM976BDF',
		categoryName: 'languages',
		categoryDisplay: 'Languages',
		attributeId: 'attr_01GW2HHFVJ8K180CNX339BTXM2',
		attributeName: 'lang-offered',
		attributeKey: 'lang.lang-offered',
		attributeNs: 'attribute',
		badgeRender: 'LIST',
		requireText: false,
		requireLanguage: true,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVRSN3W3GYZZ43WCW24',
		categoryName: 'law-practice-options',
		categoryDisplay: 'Law Practice Options',
		attributeId: 'attr_01GW2HHFVRH531R2HAV8DMDZSC',
		attributeName: 'corp-law-firm',
		attributeKey: 'userlawpractice.corp-law-firm',
		attributeNs: 'attribute',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVRSN3W3GYZZ43WCW24',
		categoryName: 'law-practice-options',
		categoryDisplay: 'Law Practice Options',
		attributeId: 'attr_01GW2HHFVSE2074QZJ4SKEW74J',
		attributeName: 'law-other',
		attributeKey: 'userlawpractice.law-other',
		attributeNs: 'attribute',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: true,
		dataSchemaName: 'otherDescribe',
		dataSchema: {
			type: 'object',
			$schema: 'http://json-schema.org/draft-07/schema#',
			required: ['other'],
			properties: {
				other: {
					type: 'string',
				},
			},
		},
	},
	{
		categoryId: 'attc_01GW2HHFVRSN3W3GYZZ43WCW24',
		categoryName: 'law-practice-options',
		categoryDisplay: 'Law Practice Options',
		attributeId: 'attr_01GW2HHFVRS8XEJ3TJBBEQJ707',
		attributeName: 'law-school-clinic',
		attributeKey: 'userlawpractice.law-school-clinic',
		attributeNs: 'attribute',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVRSN3W3GYZZ43WCW24',
		categoryName: 'law-practice-options',
		categoryDisplay: 'Law Practice Options',
		attributeId: 'attr_01GW2HHFVRFPRQCQHNJA6BM3XP',
		attributeName: 'legal-nonprofit',
		attributeKey: 'userlawpractice.legal-nonprofit',
		attributeNs: 'attribute',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVMNHV2ZS5875JWCRJ7',
		categoryName: 'organization-leadership',
		categoryDisplay: 'Organization Leadership',
		attributeId: 'attr_01GW2HHFVNPKMHYK12DDRVC1VJ',
		attributeName: 'bipoc-led',
		attributeKey: 'orgleader.bipoc-led',
		attributeNs: 'attribute',
		icon: '🤎',
		iconBg: '#F1DD7F',
		badgeRender: 'LEADER',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVMNHV2ZS5875JWCRJ7',
		categoryName: 'organization-leadership',
		categoryDisplay: 'Organization Leadership',
		attributeId: 'attr_01GW2HHFVN3JX2J7REFFT5NAMS',
		attributeName: 'black-led',
		attributeKey: 'orgleader.black-led',
		attributeNs: 'attribute',
		icon: '️‍️‍✊🏿',
		iconBg: '#C77E54',
		badgeRender: 'LEADER',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVMNHV2ZS5875JWCRJ7',
		categoryName: 'organization-leadership',
		categoryDisplay: 'Organization Leadership',
		attributeId: 'attr_01GW2HHFVNHMF72WHVKRF6W4TA',
		attributeName: 'immigrant-led',
		attributeKey: 'orgleader.immigrant-led',
		attributeNs: 'attribute',
		icon: '️‍️‍🌎',
		iconBg: '#79ADD7',
		badgeRender: 'LEADER',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVMNHV2ZS5875JWCRJ7',
		categoryName: 'organization-leadership',
		categoryDisplay: 'Organization Leadership',
		attributeId: 'attr_01GW2HHFVN3RYX9JMXDZSQZM70',
		attributeName: 'trans-led',
		attributeKey: 'orgleader.trans-led',
		attributeNs: 'attribute',
		icon: '️‍🏳️‍⚧️',
		iconBg: '#D4A1BA',
		badgeRender: 'LEADER',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVKAMMGPD71H90XRJ38',
		categoryName: 'service-access-instructions',
		categoryDisplay: 'Service Access Instructions',
		attributeId: 'attr_01GW2HHFVKFM4TDY4QRK4AR2ZW',
		attributeName: 'accessemail',
		attributeKey: 'serviceaccess.accessemail',
		attributeNs: 'attribute',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: true,
		dataSchemaName: 'accessInstructions',
		dataSchema: {
			type: 'object',
			$schema: 'http://json-schema.org/draft-07/schema#',
			required: ['access_type', 'instructions'],
			properties: {
				access_type: {
					enum: ['email', 'file', 'link', 'location', 'other', 'phone'],
					type: 'string',
				},
				access_value: {
					type: ['string', 'null'],
				},
				instructions: {
					type: 'string',
				},
			},
		},
	},
	{
		categoryId: 'attc_01GW2HHFVKAMMGPD71H90XRJ38',
		categoryName: 'service-access-instructions',
		categoryDisplay: 'Service Access Instructions',
		attributeId: 'attr_01GW2HHFVKMRHFD8SMDAZM3SSM',
		attributeName: 'accessfile',
		attributeKey: 'serviceaccess.accessfile',
		attributeNs: 'attribute',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: true,
		dataSchemaName: 'accessInstructions',
		dataSchema: {
			type: 'object',
			$schema: 'http://json-schema.org/draft-07/schema#',
			required: ['access_type', 'instructions'],
			properties: {
				access_type: {
					enum: ['email', 'file', 'link', 'location', 'other', 'phone'],
					type: 'string',
				},
				access_value: {
					type: ['string', 'null'],
				},
				instructions: {
					type: 'string',
				},
			},
		},
	},
	{
		categoryId: 'attc_01GW2HHFVKAMMGPD71H90XRJ38',
		categoryName: 'service-access-instructions',
		categoryDisplay: 'Service Access Instructions',
		attributeId: 'attr_01GW2HHFVMYXMS8ARA3GE7HZFD',
		attributeName: 'accesslink',
		attributeKey: 'serviceaccess.accesslink',
		attributeNs: 'attribute',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: true,
		dataSchemaName: 'accessInstructions',
		dataSchema: {
			type: 'object',
			$schema: 'http://json-schema.org/draft-07/schema#',
			required: ['access_type', 'instructions'],
			properties: {
				access_type: {
					enum: ['email', 'file', 'link', 'location', 'other', 'phone'],
					type: 'string',
				},
				access_value: {
					type: ['string', 'null'],
				},
				instructions: {
					type: 'string',
				},
			},
		},
	},
	{
		categoryId: 'attc_01GW2HHFVKAMMGPD71H90XRJ38',
		categoryName: 'service-access-instructions',
		categoryDisplay: 'Service Access Instructions',
		attributeId: 'attr_01GW2HHFVMH6AE94EXN7T5A87C',
		attributeName: 'accesslocation',
		attributeKey: 'serviceaccess.accesslocation',
		attributeNs: 'attribute',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: true,
		dataSchemaName: 'accessInstructions',
		dataSchema: {
			type: 'object',
			$schema: 'http://json-schema.org/draft-07/schema#',
			required: ['access_type', 'instructions'],
			properties: {
				access_type: {
					enum: ['email', 'file', 'link', 'location', 'other', 'phone'],
					type: 'string',
				},
				access_value: {
					type: ['string', 'null'],
				},
				instructions: {
					type: 'string',
				},
			},
		},
	},
	{
		categoryId: 'attc_01GW2HHFVKAMMGPD71H90XRJ38',
		categoryName: 'service-access-instructions',
		categoryDisplay: 'Service Access Instructions',
		attributeId: 'attr_01GW2HHFVMKTFWCKBVVFJ5GMY0',
		attributeName: 'accessphone',
		attributeKey: 'serviceaccess.accessphone',
		attributeNs: 'attribute',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: true,
		dataSchemaName: 'accessInstructions',
		dataSchema: {
			type: 'object',
			$schema: 'http://json-schema.org/draft-07/schema#',
			required: ['access_type', 'instructions'],
			properties: {
				access_type: {
					enum: ['email', 'file', 'link', 'location', 'other', 'phone'],
					type: 'string',
				},
				access_value: {
					type: ['string', 'null'],
				},
				instructions: {
					type: 'string',
				},
			},
		},
	},
	{
		categoryId: 'attc_01GW2HHFVKAMMGPD71H90XRJ38',
		categoryName: 'service-access-instructions',
		categoryDisplay: 'Service Access Instructions',
		attributeId: 'attr_01GW2HHFVMSX7T1WDNZ5QEHKWT',
		attributeName: 'accesspublictransit',
		attributeKey: 'serviceaccess.accesspublictransit',
		attributeNs: 'attribute',
		requireText: true,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVKAMMGPD71H90XRJ38',
		categoryName: 'service-access-instructions',
		categoryDisplay: 'Service Access Instructions',
		attributeId: 'attr_01GW2HHFVMMF19AX2KPBTMV6P3',
		attributeName: 'accesstext',
		attributeKey: 'serviceaccess.accesstext',
		attributeNs: 'attribute',
		requireText: true,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVNXMNJNV47BF2BPM1R',
		categoryName: 'service-focus',
		categoryDisplay: 'Service Focus',
		attributeId: 'attr_01GW2HHFVPCVX8F3B7M30ZJEHW',
		attributeName: 'asylum-seekers',
		attributeKey: 'srvfocus.asylum-seekers',
		attributeNs: 'attribute',
		icon: '️‍️‍🌎',
		badgeRender: 'COMMUNITY',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVNXMNJNV47BF2BPM1R',
		categoryName: 'service-focus',
		categoryDisplay: 'Service Focus',
		attributeId: 'attr_01GW2HHFVN72D7XEBZZJXCJQXQ',
		attributeName: 'bipoc-comm',
		attributeKey: 'srvfocus.bipoc-comm',
		attributeNs: 'attribute',
		icon: '️‍️‍✊🏿',
		badgeRender: 'COMMUNITY',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVNXMNJNV47BF2BPM1R',
		categoryName: 'service-focus',
		categoryDisplay: 'Service Focus',
		attributeId: 'attr_01GW2HHFVQ7SYGD3KM8WP9X50B',
		attributeName: 'gender-nc',
		attributeKey: 'srvfocus.gender-nc',
		attributeNs: 'attribute',
		icon: '🏳️‍⚧️',
		badgeRender: 'COMMUNITY',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVNXMNJNV47BF2BPM1R',
		categoryName: 'service-focus',
		categoryDisplay: 'Service Focus',
		attributeId: 'attr_01GW2HHFVRMQFJ9AMA633SQQGV',
		attributeName: 'hiv-comm',
		attributeKey: 'srvfocus.hiv-comm',
		attributeNs: 'attribute',
		icon: '💛',
		badgeRender: 'COMMUNITY',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVNXMNJNV47BF2BPM1R',
		categoryName: 'service-focus',
		categoryDisplay: 'Service Focus',
		attributeId: 'attr_01GW2HHFVPTK9555WHJHDBDA2J',
		attributeName: 'immigrant-comm',
		attributeKey: 'srvfocus.immigrant-comm',
		attributeNs: 'attribute',
		icon: '️‍️‍🌎',
		badgeRender: 'COMMUNITY',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVNXMNJNV47BF2BPM1R',
		categoryName: 'service-focus',
		categoryDisplay: 'Service Focus',
		attributeId: 'attr_01GW2HHFVQCZPA3Z5GW6J3MQHW',
		attributeName: 'lgbtq-youth-focus',
		attributeKey: 'srvfocus.lgbtq-youth-focus',
		attributeNs: 'attribute',
		icon: '🌱',
		badgeRender: 'COMMUNITY',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVNXMNJNV47BF2BPM1R',
		categoryName: 'service-focus',
		categoryDisplay: 'Service Focus',
		attributeId: 'attr_01GW2HHFVPJERY0GS9D7F56A23',
		attributeName: 'resettled-refugees',
		attributeKey: 'srvfocus.resettled-refugees',
		attributeNs: 'attribute',
		icon: '️‍️‍🌎',
		badgeRender: 'COMMUNITY',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVNXMNJNV47BF2BPM1R',
		categoryName: 'service-focus',
		categoryDisplay: 'Service Focus',
		attributeId: 'attr_01GW2HHFVQ8AGBKBBZJWTHNP2F',
		attributeName: 'spanish-speakers',
		attributeKey: 'srvfocus.spanish-speakers',
		attributeNs: 'attribute',
		icon: '🗣️',
		badgeRender: 'COMMUNITY',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVNXMNJNV47BF2BPM1R',
		categoryName: 'service-focus',
		categoryDisplay: 'Service Focus',
		attributeId: 'attr_01GW2HHFVPSYBCYF37B44WP6CZ',
		attributeName: 'trans-comm',
		attributeKey: 'srvfocus.trans-comm',
		attributeNs: 'attribute',
		icon: '🏳️‍⚧️',
		badgeRender: 'COMMUNITY',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVNXMNJNV47BF2BPM1R',
		categoryName: 'service-focus',
		categoryDisplay: 'Service Focus',
		attributeId: 'attr_01GW2HHFVQX4M8DY1FSAYSJSSK',
		attributeName: 'trans-fem',
		attributeKey: 'srvfocus.trans-fem',
		attributeNs: 'attribute',
		icon: '🏳️‍⚧️',
		badgeRender: 'COMMUNITY',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVNXMNJNV47BF2BPM1R',
		categoryName: 'service-focus',
		categoryDisplay: 'Service Focus',
		attributeId: 'attr_01GW2HHFVQEFWW42MBAD64BWXZ',
		attributeName: 'trans-masc',
		attributeKey: 'srvfocus.trans-masc',
		attributeNs: 'attribute',
		icon: '🏳️‍⚧️',
		badgeRender: 'COMMUNITY',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVNXMNJNV47BF2BPM1R',
		categoryName: 'service-focus',
		categoryDisplay: 'Service Focus',
		attributeId: 'attr_01GW2HHFVQVEGH6W3A2ANH1QZE',
		attributeName: 'trans-youth-focus',
		attributeKey: 'srvfocus.trans-youth-focus',
		attributeNs: 'attribute',
		icon: '🌱',
		badgeRender: 'COMMUNITY',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVSQWE2Y2RF3DT2VEYX',
		categoryName: 'service-provider-options',
		categoryDisplay: 'Service Provider Options',
		attributeId: 'attr_01GW2HHFVTMFN73X6NVR0M9BZJ',
		attributeName: 'friend-family',
		attributeKey: 'userserviceprovider.friend-family',
		attributeNs: 'attribute',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVSQWE2Y2RF3DT2VEYX',
		categoryName: 'service-provider-options',
		categoryDisplay: 'Service Provider Options',
		attributeId: 'attr_01GW2HHFVSVSBFQ700RMJ19BVH',
		attributeName: 'govt-agency',
		attributeKey: 'userserviceprovider.govt-agency',
		attributeNs: 'attribute',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVSQWE2Y2RF3DT2VEYX',
		categoryName: 'service-provider-options',
		categoryDisplay: 'Service Provider Options',
		attributeId: 'attr_01GW2HHFVTMVQ7W2X26ZRK81FR',
		attributeName: 'grassroots-direct',
		attributeKey: 'userserviceprovider.grassroots-direct',
		attributeNs: 'attribute',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVSQWE2Y2RF3DT2VEYX',
		categoryName: 'service-provider-options',
		categoryDisplay: 'Service Provider Options',
		attributeId: 'attr_01GW2HHFVSPXWJJPFG9DKXESEK',
		attributeName: 'healthcare',
		attributeKey: 'userserviceprovider.healthcare',
		attributeNs: 'attribute',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVSQWE2Y2RF3DT2VEYX',
		categoryName: 'service-provider-options',
		categoryDisplay: 'Service Provider Options',
		attributeId: 'attr_01GW2HHFVTTZ83PZR61M37R8R7',
		attributeName: 'nonprofit',
		attributeKey: 'userserviceprovider.nonprofit',
		attributeNs: 'attribute',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVSQWE2Y2RF3DT2VEYX',
		categoryName: 'service-provider-options',
		categoryDisplay: 'Service Provider Options',
		attributeId: 'attr_01GW2HHFVTN6MSCMBW740Y7HN1',
		attributeName: 'student-club',
		attributeKey: 'userserviceprovider.student-club',
		attributeNs: 'attribute',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: false,
	},
	{
		categoryId: 'attc_01GW2HHFVKM2PSHFWVFM0TWX1P',
		categoryName: 'system',
		categoryDisplay: 'System',
		attributeId: 'attr_01GW2HHFVK8KPRGKYFSSM5ECPQ',
		attributeName: 'incompatible-info',
		attributeKey: 'sys.incompatible-info',
		attributeNs: 'attribute',
		requireText: false,
		requireLanguage: false,
		requireGeo: false,
		requireBoolean: false,
		requireData: true,
		dataSchemaName: 'incompatible',
		dataSchema: {
			type: 'array',
			items: {
				type: 'object',
				additionalProperties: {},
			},
			$schema: 'http://json-schema.org/draft-07/schema#',
		},
	},
] satisfies ApiOutput['fieldOpt']['attributesByCategory']

export const queryAttributeCategories = (query: ApiInput['fieldOpt']['attributeCategories']) => {
	if (Array.isArray(query)) {
		return attributeCategories.filter(({ tag }) => query.includes(tag))
	}
	return attributeCategories
}

export const queryAttributesByCategory = (query: ApiInput['fieldOpt']['attributesByCategory']) => {
	if (typeof query === 'string' || Array.isArray(query)) {
		return attributesByCategory.filter(({ categoryName }) =>
			Array.isArray(query) ? query.includes(categoryName) : query === categoryName
		)
	}
	return attributesByCategory
}
