import { getTRPCMock } from '~ui/lib/getTrpcMock'

export const orgPhone = {
	get: getTRPCMock({
		path: ['orgPhone', 'get'],
		response: [
			{
				id: 'ophn_01GVH3VEVCQW5N7R8YEV06D3AZ',
				number: '2027974457',
				ext: null,
				deleted: false,
				primary: false,
				published: true,
				country: 'US',
				description: 'Gender Affirming Services',
				locations: [],
				organization: {
					id: 'orgn_01GVH3V408N0YS7CDYAH3F2BMH',
					name: 'Whitman-Walker Health',
					slug: 'whitman-walker-health',
				},
				phoneType: null,
				services: [
					{
						id: 'osvc_01GVH3VEVR4SRPFQD2SJF1MCJJ',
						serviceName: 'Receive gender affirming care and services',
					},
					{
						id: 'osvc_01GVH3VEWHDC6F5FCQHB0H5GD6',
						serviceName: 'Get gender affirming hormone therapy',
					},
				],
			},
			{
				id: 'ophn_01GVH3VEVCFKT3NWQ79STYVDKR',
				number: '2027457000',
				ext: null,
				deleted: false,
				primary: true,
				published: true,
				country: 'US',
				description: 'Medical Care/ Appointments',
				locations: [],
				organization: {
					id: 'orgn_01GVH3V408N0YS7CDYAH3F2BMH',
					name: 'Whitman-Walker Health',
					slug: 'whitman-walker-health',
				},
				phoneType: null,
				services: [
					{
						id: 'osvc_01GVH3VEVPF1KEKBTRVTV70WGV',
						serviceName: 'Get rapid HIV testing',
					},
					{
						id: 'osvc_01GVH3VEVSNF9NH79R7HC9FHY6',
						serviceName: 'Get HIV care for newly diagnosed patients',
					},
					{
						id: 'osvc_01GVH3VEW2ND36DB0XWAH1PQY0',
						serviceName: 'Get dental health services for HIV-positive individuals',
					},
				],
			},
			{
				id: 'ophn_01GVH3VEVC36PW0Z9GDV0ZERV1',
				number: '2027974439',
				ext: null,
				deleted: false,
				primary: false,
				published: true,
				country: 'US',
				description: 'HIV/STI Testing or Sexual Health Appointment',
				locations: [],
				organization: {
					id: 'orgn_01GVH3V408N0YS7CDYAH3F2BMH',
					name: 'Whitman-Walker Health',
					slug: 'whitman-walker-health',
				},
				phoneType: null,
				services: [],
			},
			{
				id: 'ophn_01GVH3VEVCV5Y3PEXRQ0SDK41K',
				number: '2022072360',
				ext: null,
				deleted: false,
				primary: false,
				published: true,
				country: 'US',
				description: 'Youth Care',
				locations: [],
				organization: {
					id: 'orgn_01GVH3V408N0YS7CDYAH3F2BMH',
					name: 'Whitman-Walker Health',
					slug: 'whitman-walker-health',
				},
				phoneType: null,
				services: [],
			},
			{
				id: 'ophn_01GVH3VEVCBFHYF56W5EZ5M2QS',
				number: '2027974437',
				ext: null,
				deleted: false,
				primary: false,
				published: false,
				country: 'US',
				description: 'New with HIV',
				locations: [],
				organization: {
					id: 'orgn_01GVH3V408N0YS7CDYAH3F2BMH',
					name: 'Whitman-Walker Health',
					slug: 'whitman-walker-health',
				},
				phoneType: null,
				services: [],
			},
			{
				id: 'ophn_01GVH3VEVDSJTN1379Y17FNP28',
				number: '2022072480',
				ext: null,
				deleted: true,
				primary: false,
				published: false,
				country: 'US',
				description: 'COVID-19 Vaccine Appointments',
				locations: [],
				organization: {
					id: 'orgn_01GVH3V408N0YS7CDYAH3F2BMH',
					name: 'Whitman-Walker Health',
					slug: 'whitman-walker-health',
				},
				phoneType: null,
				services: [
					{
						id: 'osvc_01GVH3VEWFZ5FHZ6S7BXQY1W55',
						serviceName: 'Get the COVID-19 vaccine',
					},
				],
			},
		],
	}),
}
