import { getTRPCMock, type MockDataObject, type MockHandlerObject } from '~ui/lib/getTrpcMock'

export const orgPhoneData = {
	get: [
		{
			id: 'ophn_01GVH3VEVCQW5N7R8YEV06D3AZ',
			number: '2027974457',
			ext: null,
			deleted: false,
			primary: false,
			published: true,
			country: { id: 'ctry_01GW2HHDK9M26M80SG63T21SVH', cca2: 'US' },
			description: 'Gender Affirming Services',
			locations: [],
			organization: {
				id: 'orgn_01GVH3V408N0YS7CDYAH3F2BMH',
				name: 'Whitman-Walker Health',
				slug: 'whitman-walker-health',
			},
			phoneType: null,
			services: [
				{
					id: 'osvc_01GVH3VEVR4SRPFQD2SJF1MCJJ',
					serviceName: 'Receive gender affirming care and services',
				},
				{
					id: 'osvc_01GVH3VEWHDC6F5FCQHB0H5GD6',
					serviceName: 'Get gender affirming hormone therapy',
				},
			],
		},
		{
			id: 'ophn_01GVH3VEVCFKT3NWQ79STYVDKR',
			number: '2027457000',
			ext: null,
			deleted: false,
			primary: true,
			published: true,
			country: { id: 'ctry_01GW2HHDK9M26M80SG63T21SVH', cca2: 'US' },
			description: 'Medical Care/ Appointments',
			locations: [],
			organization: {
				id: 'orgn_01GVH3V408N0YS7CDYAH3F2BMH',
				name: 'Whitman-Walker Health',
				slug: 'whitman-walker-health',
			},
			phoneType: null,
			services: [
				{
					id: 'osvc_01GVH3VEVPF1KEKBTRVTV70WGV',
					serviceName: 'Get rapid HIV testing',
				},
				{
					id: 'osvc_01GVH3VEVSNF9NH79R7HC9FHY6',
					serviceName: 'Get HIV care for newly diagnosed patients',
				},
				{
					id: 'osvc_01GVH3VEW2ND36DB0XWAH1PQY0',
					serviceName: 'Get dental health services for HIV-positive individuals',
				},
			],
		},
		{
			id: 'ophn_01GVH3VEVC36PW0Z9GDV0ZERV1',
			number: '2027974439',
			ext: null,
			deleted: false,
			primary: false,
			published: true,
			country: { id: 'ctry_01GW2HHDK9M26M80SG63T21SVH', cca2: 'US' },
			description: 'HIV/STI Testing or Sexual Health Appointment',
			locations: [],
			organization: {
				id: 'orgn_01GVH3V408N0YS7CDYAH3F2BMH',
				name: 'Whitman-Walker Health',
				slug: 'whitman-walker-health',
			},
			phoneType: null,
			services: [],
		},
		{
			id: 'ophn_01GVH3VEVCV5Y3PEXRQ0SDK41K',
			number: '2022072360',
			ext: null,
			deleted: false,
			primary: false,
			published: true,
			country: { id: 'ctry_01GW2HHDK9M26M80SG63T21SVH', cca2: 'US' },
			description: 'Youth Care',
			locations: [],
			organization: {
				id: 'orgn_01GVH3V408N0YS7CDYAH3F2BMH',
				name: 'Whitman-Walker Health',
				slug: 'whitman-walker-health',
			},
			phoneType: null,
			services: [],
		},
		{
			id: 'ophn_01GVH3VEVCBFHYF56W5EZ5M2QS',
			number: '2027974437',
			ext: null,
			deleted: false,
			primary: false,
			published: false,
			country: { id: 'ctry_01GW2HHDK9M26M80SG63T21SVH', cca2: 'US' },
			description: 'New with HIV',
			locations: [],
			organization: {
				id: 'orgn_01GVH3V408N0YS7CDYAH3F2BMH',
				name: 'Whitman-Walker Health',
				slug: 'whitman-walker-health',
			},
			phoneType: null,
			services: [],
		},
		{
			id: 'ophn_01GVH3VEVDSJTN1379Y17FNP28',
			number: '2022072480',
			ext: null,
			deleted: true,
			primary: false,
			published: false,
			country: { id: 'ctry_01GW2HHDK9M26M80SG63T21SVH', cca2: 'US' },
			description: 'COVID-19 Vaccine Appointments',
			locations: [],
			organization: {
				id: 'orgn_01GVH3V408N0YS7CDYAH3F2BMH',
				name: 'Whitman-Walker Health',
				slug: 'whitman-walker-health',
			},
			phoneType: null,
			services: [
				{
					id: 'osvc_01GVH3VEWFZ5FHZ6S7BXQY1W55',
					serviceName: 'Get the COVID-19 vaccine',
				},
			],
		},
	],
	forContactInfo: [
		{
			id: 'ophn_01GVH3VEVCFKT3NWQ79STYVDKR',
			number: '2027457000',
			ext: null,
			primary: true,
			locationOnly: false,
			country: 'US',
			phoneType: null,
			description: {
				key: 'whitman-walker-health.ophn_01GVH3VEVCFKT3NWQ79STYVDKR.description',
				defaultText: 'Medical Care/ Appointments',
			},
		},
		{
			id: 'ophn_01GVH3VEVCYYQQS9NGH5Z1GYJ4',
			number: '2027456175',
			ext: null,
			primary: false,
			locationOnly: false,
			country: 'US',
			phoneType: null,
			description: {
				key: 'whitman-walker-health.ophn_01GVH3VEVCYYQQS9NGH5Z1GYJ4.description',
				defaultText: 'GMHW Sexual Health Clinic',
			},
		},
		{
			id: 'ophn_01GVH3VEVCE8GNAJ7NJ9FYKME5',
			number: '2029397630',
			ext: null,
			primary: false,
			locationOnly: false,
			country: 'US',
			phoneType: null,
			description: {
				key: 'whitman-walker-health.ophn_01GVH3VEVCE8GNAJ7NJ9FYKME5.description',
				defaultText: 'Legal Services Program',
			},
		},
		{
			id: 'ophn_01GVH3VEVCQW5N7R8YEV06D3AZ',
			number: '2027974457',
			ext: null,
			primary: false,
			locationOnly: false,
			country: 'US',
			phoneType: null,
			description: {
				key: 'whitman-walker-health.ophn_01GVH3VEVCQW5N7R8YEV06D3AZ.description',
				defaultText: 'Gender Affirming Services',
			},
		},
		{
			id: 'ophn_01GVH3VEVC36PW0Z9GDV0ZERV1',
			number: '2027974439',
			ext: null,
			primary: false,
			locationOnly: false,
			country: 'US',
			phoneType: null,
			description: {
				key: 'whitman-walker-health.ophn_01GVH3VEVC36PW0Z9GDV0ZERV1.description',
				defaultText: 'HIV/STI Testing or Sexual Health Appointment',
			},
		},
		{
			id: 'ophn_01GVH3VEVCV5Y3PEXRQ0SDK41K',
			number: '2022072360',
			ext: null,
			primary: false,
			locationOnly: false,
			country: 'US',
			phoneType: null,
			description: {
				key: 'whitman-walker-health.ophn_01GVH3VEVCV5Y3PEXRQ0SDK41K.description',
				defaultText: 'Youth Care',
			},
		},
		{
			id: 'ophn_01GVH3VEVCSADS12PEYP2GF2Y3',
			number: '2029397623',
			ext: null,
			primary: false,
			locationOnly: false,
			country: 'US',
			phoneType: null,
			description: {
				key: 'whitman-walker-health.ophn_01GVH3VEVCSADS12PEYP2GF2Y3.description',
				defaultText: 'Behavioral Health (Therapy & Psychiatry)',
			},
		},
		{
			id: 'ophn_01GVH3VEVCDEFMAGG3SAJVWJFQ',
			number: '2025439355',
			ext: null,
			primary: false,
			locationOnly: false,
			country: 'US',
			phoneType: null,
			description: {
				key: 'whitman-walker-health.ophn_01GVH3VEVCDEFMAGG3SAJVWJFQ.description',
				defaultText: 'Max Robinson Center HIV/STI & Pregnancy Testing',
			},
		},
		{
			id: 'ophn_01GVH3VEVCBFHYF56W5EZ5M2QS',
			number: '2027974437',
			ext: null,
			primary: false,
			locationOnly: false,
			country: 'US',
			phoneType: null,
			description: {
				key: 'whitman-walker-health.ophn_01GVH3VEVCBFHYF56W5EZ5M2QS.description',
				defaultText: 'New with HIV',
			},
		},
		{
			id: 'ophn_01GVH3VEVCKB84BV4X0MSAKE2M',
			number: '2029397690',
			ext: null,
			primary: false,
			locationOnly: false,
			country: 'US',
			phoneType: null,
			description: {
				key: 'whitman-walker-health.ophn_01GVH3VEVCKB84BV4X0MSAKE2M.description',
				defaultText: 'PrEP Clinic',
			},
		},
		{
			id: 'ophn_01GVH3VEVDSJTN1379Y17FNP28',
			number: '2022072480',
			ext: null,
			primary: false,
			locationOnly: false,
			country: 'US',
			phoneType: null,
			description: {
				key: 'whitman-walker-health.ophn_01GVH3VEVDSJTN1379Y17FNP28.description',
				defaultText: 'COVID-19 Vaccine Appointments',
			},
		},
	],
} satisfies MockDataObject<'orgPhone'>

export const orgPhone = {
	get: getTRPCMock({
		path: ['orgPhone', 'get'],
		response: orgPhoneData.get,
	}),
	upsertMany: getTRPCMock({
		path: ['orgPhone', 'upsertMany'],
		type: 'mutation',
		response: (input) => [],
	}),
	forContactInfo: getTRPCMock({
		path: ['orgPhone', 'forContactInfo'],
		type: 'query',
		response: ({ locationOnly }) =>
			locationOnly !== undefined
				? orgPhoneData.forContactInfo.filter((record) => record.locationOnly === locationOnly)
				: orgPhoneData.forContactInfo,
	}),
} satisfies MockHandlerObject<'orgPhone'>
