import { ApiInput, ApiOutput } from '@weareinreach/api'

type SearchInput = ApiInput['organization']['searchName']

export const mockOrgNameSearch = (input: SearchInput): ApiOutput['organization']['searchName'] => {
	const searchRegex = new RegExp(`.*${input.search}.*`, 'i')
	const results = mockData.filter(({ name }) => searchRegex.test(name))
	return results
}

export const mockData = [
	{
		value: 'Lyon-Martin Health Services',
		name: 'Lyon-Martin Health Services',
		id: 'orgn_01GSKV7YTJ3R4PM8SSHBZ72HX1',
		slug: 'lyon-martin-health-services',
	},
	{
		value: 'Larkin Street Youth Services',
		name: 'Larkin Street Youth Services',
		id: 'orgn_01GSKV7YV30W3B6EWEF4SJSX9S',
		slug: 'larkin-street-youth-services',
	},
	{
		value: 'Mission Neighborhood Health Center',
		name: 'Mission Neighborhood Health Center',
		id: 'orgn_01GSKV7YVNTF1REYZGTAPA9HP8',
		slug: 'mission-neighborhood-health-center',
	},
	{
		value: 'North East Medical Services',
		name: 'North East Medical Services',
		id: 'orgn_01GSKV7YW7XVRN9VZF9EPWWQVJ',
		slug: 'north-east-medical-services',
	},
	{
		value: 'San Francisco Community Health Center',
		name: 'San Francisco Community Health Center',
		id: 'orgn_01GSKV7YWS9CEYHZF99HEXMT48',
		slug: 'san-francisco-community-health-center',
	},
	{
		value: 'San Francisco City Clinic',
		name: 'San Francisco City Clinic',
		id: 'orgn_01GSKV7YXBSTXX9F9627HHRSMN',
		slug: 'san-francisco-city-clinic',
	},
	{
		value: 'St. James Infirmary (SJI)',
		name: 'St. James Infirmary (SJI)',
		id: 'orgn_01GSKV7YXX9PW72HTYAD5DAPW4',
		slug: 'st-james-infirmary-sji',
	},
	{
		value: 'Upwardly Global',
		name: 'Upwardly Global',
		id: 'orgn_01GSKV7YYF8FDW9PAEQM606T5J',
		slug: 'upwardly-global',
	},
	{
		value: 'Episcopal Community Services',
		name: 'Episcopal Community Services',
		id: 'orgn_01GSKV7YZ12KK64KBGYJTNDY7Q',
		slug: 'episcopal-community-services',
	},
	{
		value: 'Transgender Law Center (TLC)',
		name: 'Transgender Law Center (TLC)',
		id: 'orgn_01GSKV7YZK90DKC1JCJGTJFJQS',
		slug: 'transgender-law-center-tlc',
	},
	{
		value: 'San Francisco City Impact',
		name: 'San Francisco City Impact',
		id: 'orgn_01GSKV7Z0425JENMBG75JSD22P',
		slug: 'san-francisco-city-impact',
	},
	{
		value: 'The Trevor Project',
		name: 'The Trevor Project',
		id: 'orgn_01GSKV7Z18SGSYMEPJS59TNYGY',
		slug: 'the-trevor-project',
	},
	{
		value: 'Billy DeFrank LGBTQ+ Community Center',
		name: 'Billy DeFrank LGBTQ+ Community Center',
		id: 'orgn_01GSKV7Z1VFW1VB6RB04P7MQ56',
		slug: 'billy-defrank-lgbtq-community-center',
	},
	{
		value: 'United We Dream',
		name: 'United We Dream',
		id: 'orgn_01GSKV7Z2ZWQM265B04N0KP9JW',
		slug: 'united-we-dream',
	},
	{
		value: 'Los Angeles Regional Food Bank',
		name: 'Los Angeles Regional Food Bank',
		id: 'orgn_01GSKV7Z3HE7SSMGDF7ZF949RB',
		slug: 'los-angeles-regional-food-bank',
	},
	{
		value: 'Los Angeles LGBT Center',
		name: 'Los Angeles LGBT Center',
		id: 'orgn_01GSKV7Z40VJ549D2TX63K0D4R',
		slug: 'los-angeles-lgbt-center',
	},
	{
		value: "St. John's Well Child and Family Center",
		name: "St. John's Well Child and Family Center",
		id: 'orgn_01GSKV7Z4KN9HDW04FYQRF30Q4',
		slug: 'st-johns-well-child-and-family-center',
	},
	{
		value: 'Pro Bono Project',
		name: 'Pro Bono Project',
		id: 'orgn_01GSKV7Z545Y5NZCW5G2XJRR00',
		slug: 'pro-bono-project',
	},
	{
		value: 'LGBTQ Center Long Beach',
		name: 'LGBTQ Center Long Beach',
		id: 'orgn_01GSKV7Z5PFVY0KERFKHYMZDP6',
		slug: 'lgbtq-center-long-beach',
	},
	{
		value: 'Eastmont Community Center',
		name: 'Eastmont Community Center',
		id: 'orgn_01GSKV7Z6SJBT1TFD5QEZ7868Y',
		slug: 'eastmont-community-center',
	},
	{
		value: 'Covenant Presbyterian Church',
		name: 'Covenant Presbyterian Church',
		id: 'orgn_01GSKV7Z7AJKHE0B2G7B5HYW90',
		slug: 'covenant-presbyterian-church',
	},
	{
		value: 'Emeryville Citizens Assistance Program',
		name: 'Emeryville Citizens Assistance Program',
		id: 'orgn_01GSKV7Z7X422NREA7DXJ8G6WG',
		slug: 'emeryville-citizens-assistance-program',
	},
	{
		value: 'Northwest Immigrant Rights Project (NWIRP)',
		name: 'Northwest Immigrant Rights Project (NWIRP)',
		id: 'orgn_01GSKV7Z8FX1ZYM86191S1CCD9',
		slug: 'northwest-immigrant-rights-project-nwirp',
	},
	{
		value: 'Entre Hermanos',
		name: 'Entre Hermanos',
		id: 'orgn_01GSKV7Z9JDXB27TBFRDV5AGMZ',
		slug: 'entre-hermanos',
	},
	{
		value: 'Law Office of Andre Olivie, PLLC',
		name: 'Law Office of Andre Olivie, PLLC',
		id: 'orgn_01GSKV7ZA5CXFNH7E1A828J4PA',
		slug: 'law-office-of-andre-olivie-pllc',
	},
	{
		value: 'Jewish Vocational Service SoCal (JVS SoCal)',
		name: 'Jewish Vocational Service SoCal (JVS SoCal)',
		id: 'orgn_01GSKV7ZAQD87Q8D1CF5ET6XHG',
		slug: 'jewish-vocational-service-socal-jvs-socal',
	},
	{
		value: 'PARS Equality Center',
		name: 'PARS Equality Center',
		id: 'orgn_01GSKV7ZB9K1SVYNS48YAA26QP',
		slug: 'pars-equality-center',
	},
	{
		value: 'Haitian Women for Haitian Refugees',
		name: 'Haitian Women for Haitian Refugees',
		id: 'orgn_01GSKV7ZBVGFXCGM44HZDZBE6H',
		slug: 'haitian-women-for-haitian-refugees',
	},
	{
		value: 'The Karsh Center',
		name: 'The Karsh Center',
		id: 'orgn_01GSKV7ZCBCNXV6RM0CJNK8S3R',
		slug: 'the-karsh-center',
	},
	{
		value: 'Catholic Charities of Los Angeles, Inc.',
		name: 'Catholic Charities of Los Angeles, Inc.',
		id: 'orgn_01GSKV7ZCX8ABDKDQCJ0C7FYK2',
		slug: 'catholic-charities-of-los-angeles-inc',
	},
	{
		value: 'Friends Community Center',
		name: 'Friends Community Center',
		id: 'orgn_01GSKV7ZDE2C896P8H853D9C7Z',
		slug: 'friends-community-center',
	},
	{
		value: 'The Northwest Network of Survivors',
		name: 'The Northwest Network of Survivors',
		id: 'orgn_01GSKV7ZEHMQZW5VBK906C61DM',
		slug: 'the-northwest-network-of-survivors',
	},
	{
		value: 'Neighborcare Health',
		name: 'Neighborcare Health',
		id: 'orgn_01GSKV7ZFNDEJ0PH6YRWTA2QF7',
		slug: 'neighborcare-health',
	},
	{
		value: 'ROOTS',
		name: 'ROOTS',
		id: 'orgn_01GSKV7ZG74M6CMTK1B72X23KS',
		slug: 'roots',
	},
	{
		value: 'Jewish Family Service of Seattle',
		name: 'Jewish Family Service of Seattle',
		id: 'orgn_01GSKV7ZGRFA5HCK6DG4J2Q9JD',
		slug: 'jewish-family-service-of-seattle',
	},
	{
		value: 'Asian Counseling and Referral Service (ACRS)',
		name: 'Asian Counseling and Referral Service (ACRS)',
		id: 'orgn_01GSKV7ZHAXTMPN5H4V1YGB02R',
		slug: 'asian-counseling-and-referral-service-acrs',
	},
	{
		value: 'Thai Community Development Center',
		name: 'Thai Community Development Center',
		id: 'orgn_01GSKV7ZHVFG0XDYY5X2MQMNXR',
		slug: 'thai-community-development-center',
	},
	{
		value: "Alameda County Sheriff's Office - Youth and Family Services Bureau (YFSB)",
		name: "Alameda County Sheriff's Office - Youth and Family Services Bureau (YFSB)",
		id: 'orgn_01GSKV7ZJDJ75T1DSWC8832EEY',
		slug: 'alameda-county-sheriffs-office-youth-and-family-services-bureau-yfsb',
	},
	{
		value: 'Consejo Counseling & Referral Service',
		name: 'Consejo Counseling & Referral Service',
		id: 'orgn_01GSKV7ZJYDGBKM6VGYMJ0QM06',
		slug: 'consejo-counseling-and-referral-service',
	},
	{
		value: 'Three Dollar Bill Cinema',
		name: 'Three Dollar Bill Cinema',
		id: 'orgn_01GSKV7ZKG091YZ38BW1JV10F2',
		slug: 'three-dollar-bill-cinema',
	},
	{
		value: 'Rainbow City Performing Arts (RCPA)',
		name: 'Rainbow City Performing Arts (RCPA)',
		id: 'orgn_01GSKV7ZM1GCYTB888VCPJZTJ9',
		slug: 'rainbow-city-performing-arts-rcpa',
	},
	{
		value: 'OutVentures',
		name: 'OutVentures',
		id: 'orgn_01GSKV7ZN508X33W2571FXX85K',
		slug: 'outventures',
	},
	{
		value: 'Lutheran Community Services Northwest - Refugees Northwest Program',
		name: 'Lutheran Community Services Northwest - Refugees Northwest Program',
		id: 'orgn_01GSKV7ZPA3CK1KB29XFHQ273N',
		slug: 'lutheran-community-services-northwest-refugees-northwest-program',
	},
	{
		value: 'The Jewish Federation of Greater Seattle',
		name: 'The Jewish Federation of Greater Seattle',
		id: 'orgn_01GSKV7ZPW4NQ9T3ANJJSMBBG7',
		slug: 'the-jewish-federation-of-greater-seattle',
	},
	{
		value: 'Philadelphia Human Rights Clinic',
		name: 'Philadelphia Human Rights Clinic',
		id: 'orgn_01GSKV7ZR7Y7EJ40JMZ0T6ZHJR',
		slug: 'philadelphia-human-rights-clinic',
	},
	{
		value: 'William Way LGBT Community Center',
		name: 'William Way LGBT Community Center',
		id: 'orgn_01GSKV7ZRZ48X16MCV729SED80',
		slug: 'william-way-lgbt-community-center',
	},
	{
		value: 'Nemours Pediatrics',
		name: 'Nemours Pediatrics',
		id: 'orgn_01GSKV7ZSQPWJ7CMM074BWDCCW',
		slug: 'nemours-pediatrics',
	},
	{
		value: 'Reading Hospital Women’s Health Center',
		name: 'Reading Hospital Women’s Health Center',
		id: 'orgn_01GSKV7ZT9GGMHY4YVMNFRCN3Q',
		slug: 'reading-hospital-womens-health-center',
	},
	{
		value: 'Equal Access Legal Services',
		name: 'Equal Access Legal Services',
		id: 'orgn_01GSKV7ZTTMQ4A4T1Z6A2H96DG',
		slug: 'equal-access-legal-services',
	},
	{
		value: 'Philadelphia Voices of Pride',
		name: 'Philadelphia Voices of Pride',
		id: 'orgn_01GSKV7ZVXXXGP2069FX6M7A68',
		slug: 'philadelphia-voices-of-pride',
	},
	{
		value: 'Peer Seattle',
		name: 'Peer Seattle',
		id: 'orgn_01GSKV7ZX10FX9J6VAYVA9KDQE',
		slug: 'peer-seattle',
	},
	{
		value: "Children's Hospital of Philadelphia - Refugee Health Program",
		name: "Children's Hospital of Philadelphia - Refugee Health Program",
		id: 'orgn_01GSKV7ZXJEPEVWNN5M0EKRXCC',
		slug: 'childrens-hospital-of-philadelphia-refugee-health-program',
	},
	{
		value: 'Seattle Frontrunners',
		name: 'Seattle Frontrunners',
		id: 'orgn_01GSKV7ZY4XZEYANVX1C7E8AYF',
		slug: 'seattle-frontrunners',
	},
	{
		value: 'Whitman-Walker Health',
		name: 'Whitman-Walker Health',
		id: 'orgn_01GSKV7ZYP2GDSH8PNJY3TVTYK',
		slug: 'whitman-walker-health',
	},
	{
		value: 'The DC Center for the LGBT Community',
		name: 'The DC Center for the LGBT Community',
		id: 'orgn_01GSKV7ZZ7GMGR4HA686J09K2F',
		slug: 'the-dc-center-for-the-lgbt-community',
	},
	{
		value: 'The Attic Youth Center',
		name: 'The Attic Youth Center',
		id: 'orgn_01GSKV7ZZS5T2KXTK1YD385GGA',
		slug: 'the-attic-youth-center',
	},
	{
		value: 'COMHAR',
		name: 'COMHAR',
		id: 'orgn_01GSKV800AGJTHZS6Q3S210SVR',
		slug: 'comhar',
	},
	{
		value: 'Community Behavioral Health',
		name: 'Community Behavioral Health',
		id: 'orgn_01GSKV800WEBJP0026WFDC60ZP',
		slug: 'community-behavioral-health',
	},
	{
		value: 'Congreso',
		name: 'Congreso',
		id: 'orgn_01GSKV801EWZNDJDZHXNJYX0TJ',
		slug: 'congreso',
	},
	{
		value: 'AIDS Activities Coordinating Office',
		name: 'AIDS Activities Coordinating Office',
		id: 'orgn_01GSKV80202MD7PTD0TF764GQA',
		slug: 'aids-activities-coordinating-office',
	},
	{
		value: 'Einstein Health - Community Practice Center',
		name: 'Einstein Health - Community Practice Center',
		id: 'orgn_01GSKV804WKY61R21581QM1S08',
		slug: 'einstein-health-community-practice-center',
	},
	{
		value: 'Public Health Management Corporation - Health Connection',
		name: 'Public Health Management Corporation - Health Connection',
		id: 'orgn_01GSKV805EPXBQVVV0FAPCQSHS',
		slug: 'public-health-management-corporation-health-connection',
	},
	{
		value: 'Public Health Management Corporation - Rising Sun',
		name: 'Public Health Management Corporation - Rising Sun',
		id: 'orgn_01GSKV80601Q24151QRZCQ4HVN',
		slug: 'public-health-management-corporation-rising-sun',
	},
	{
		value: 'Lambert House',
		name: 'Lambert House',
		id: 'orgn_01GSKV806HHFJZRS3YZQQTMSY3',
		slug: 'lambert-house',
	},
	{
		value: 'The Mazzoni Center',
		name: 'The Mazzoni Center',
		id: 'orgn_01GSKV8072RG8Q64KT6EX7WM00',
		slug: 'the-mazzoni-center',
	},
	{
		value: 'Nationalities Services Center',
		name: 'Nationalities Services Center',
		id: 'orgn_01GSKV807MXP55HHZ9DR570S2W',
		slug: 'nationalities-services-center',
	},
	{
		value: 'The COLOURS Organization',
		name: 'The COLOURS Organization',
		id: 'orgn_01GSKV8086PF12B1G5S5KMHMHZ',
		slug: 'the-colours-organization',
	},
	{
		value: 'Women Organized Against Rape (WOAR)',
		name: 'Women Organized Against Rape (WOAR)',
		id: 'orgn_01GSKV808QQ0KSMMRT1900SB0J',
		slug: 'women-organized-against-rape-woar',
	},
	{
		value: 'AccessMatters',
		name: 'AccessMatters',
		id: 'orgn_01GSKV80AYBHFPQR5HYQHN1Y6V',
		slug: 'accessmatters',
	},
	{
		value: 'AIDS Law Project of Pennsylvania',
		name: 'AIDS Law Project of Pennsylvania',
		id: 'orgn_01GSKV80BF1DKN38AWM42N7CH2',
		slug: 'aids-law-project-of-pennsylvania',
	},
	{
		value: 'African Cultural Alliance of North America, Inc.',
		name: 'African Cultural Alliance of North America, Inc.',
		id: 'orgn_01GSKV80CHXF7S80WWMFHVHH05',
		slug: 'african-cultural-alliance-of-north-america-inc',
	},
	{
		value: 'Catholic Social Services of Philadelphia - Immigration Legal Services',
		name: 'Catholic Social Services of Philadelphia - Immigration Legal Services',
		id: 'orgn_01GSKV80D4G6VH7P46MZVE34QG',
		slug: 'catholic-social-services-of-philadelphia-immigration-legal-services',
	},
	{
		value: 'El Centro de la Raza',
		name: 'El Centro de la Raza',
		id: 'orgn_01GSKV80E6VAN5Y1VQYQZK7FRK',
		slug: 'el-centro-de-la-raza',
	},
	{
		value: 'Human Rights First',
		name: 'Human Rights First',
		id: 'orgn_01GSKV80EQB9J7JNV4AYESDR12',
		slug: 'human-rights-first',
	},
	{
		value: 'The George Washington University Immigration Clinic',
		name: 'The George Washington University Immigration Clinic',
		id: 'orgn_01GSKV80FB7Y8669784XFN5FQN',
		slug: 'the-george-washington-university-immigration-clinic',
	},
	{
		value: "Capital Area Immigrants' Rights (CAIR) Coalition",
		name: "Capital Area Immigrants' Rights (CAIR) Coalition",
		id: 'orgn_01GSKV80HG3HN3XKNW81BWFPH6',
		slug: 'capital-area-immigrants-rights-cair-coalition',
	},
	{
		value: 'National Center for Lesbian Rights (NCLR)',
		name: 'National Center for Lesbian Rights (NCLR)',
		id: 'orgn_01GSKV80J2KNWNP0TY5EM36Z2S',
		slug: 'national-center-for-lesbian-rights-nclr',
	},
	{
		value: 'Penn Medicine Program for LGBT Health',
		name: 'Penn Medicine Program for LGBT Health',
		id: 'orgn_01GSKV80K5Y6WT4JGDRZ605ZF6',
		slug: 'penn-medicine-program-for-lgbt-health',
	},
	{
		value: 'The LGBT Asylum Project',
		name: 'The LGBT Asylum Project',
		id: 'orgn_01GSKV80MSNSJXHV1SX209VSF7',
		slug: 'the-lgbt-asylum-project',
	},
	{
		value: 'The Lesbian, Gay, Bisexual & Transgender Community Center',
		name: 'The Lesbian, Gay, Bisexual & Transgender Community Center',
		id: 'orgn_01GSKV80PQTS0GCFACR35YG4J6',
		slug: 'the-lesbian-gay-bisexual-and-transgender-community-center',
	},
	{
		value: 'St. James Immigrant Assistance',
		name: 'St. James Immigrant Assistance',
		id: 'orgn_01GSKV80QXZS5281HXQ6SMJ2NP',
		slug: 'st-james-immigrant-assistance',
	},
	{
		value: 'Rainbow Center',
		name: 'Rainbow Center',
		id: 'orgn_01GSKV80REK1Z8XGH3NS8MHA4J',
		slug: 'rainbow-center',
	},
	{
		value: 'New York Legal Assistance Group (NYLAG)',
		name: 'New York Legal Assistance Group (NYLAG)',
		id: 'orgn_01GSKV80RZJV32Z3VEPEWGB8NK',
		slug: 'new-york-legal-assistance-group-nylag',
	},
	{
		value: 'African Hope Committee',
		name: 'African Hope Committee',
		id: 'orgn_01GSKV80SHTVWB7EK10WG3FSDP',
		slug: 'african-hope-committee',
	},
	{
		value: 'City Bar Justice Center (CBJC)',
		name: 'City Bar Justice Center (CBJC)',
		id: 'orgn_01GSKV80T3NTH3P2NEQF54XS0P',
		slug: 'city-bar-justice-center-cbjc',
	},
	{
		value: 'Housing Works',
		name: 'Housing Works',
		id: 'orgn_01GSKV80TMTCJDBVKNGA4CJHDT',
		slug: 'housing-works',
	},
	{
		value: 'Immigration Equality',
		name: 'Immigration Equality',
		id: 'orgn_01GSKV80V6ZX0E5WWQXQX0RC23',
		slug: 'immigration-equality',
	},
	{
		value: 'RAICES - San Antonio North',
		name: 'RAICES - San Antonio North',
		id: 'orgn_01GSKV81CKCYRQ4B6MNSSYCFK0',
		slug: 'raices-san-antonio-north',
	},
	{
		value: 'Gender Justice League (GJL)',
		name: 'Gender Justice League (GJL)',
		id: 'orgn_01GSKV80WC6JV47EF4T8NA1H8H',
		slug: 'gender-justice-league-gjl',
	},
	{
		value: 'People of Color Against AIDS Network (POCAAN)',
		name: 'People of Color Against AIDS Network (POCAAN)',
		id: 'orgn_01GSKV80Y1BQKC2FDKZ14R0BTJ',
		slug: 'people-of-color-against-aids-network-pocaan',
	},
	{
		value: 'HealthRIGHT 360',
		name: 'HealthRIGHT 360',
		id: 'orgn_01GSKV80Z48VYKHPRWHP01ZQC7',
		slug: 'healthright-360',
	},
	{
		value: 'Queer Detainee Empowerment Project (QDEP)',
		name: 'Queer Detainee Empowerment Project (QDEP)',
		id: 'orgn_01GSKV80ZPWHF9PM7C7G5E05VQ',
		slug: 'queer-detainee-empowerment-project-qdep',
	},
	{
		value: 'Community Forward San Francisco',
		name: 'Community Forward San Francisco',
		id: 'orgn_01GSKV8109S9RKKZQJY72GZRVF',
		slug: 'community-forward-san-francisco',
	},
	{
		value: 'Homeless Outreach Program Integrated Care System (HOPICS)',
		name: 'Homeless Outreach Program Integrated Care System (HOPICS)',
		id: 'orgn_01GSKV810T4GPF2RF968V4Z7ZP',
		slug: 'homeless-outreach-program-integrated-care-system-hopics',
	},
	{
		value: 'Safe Horizon',
		name: 'Safe Horizon',
		id: 'orgn_01GSKV811BMKXHS88PFD0VK2RJ',
		slug: 'safe-horizon',
	},
	{
		value: 'RUSA LGBT',
		name: 'RUSA LGBT',
		id: 'orgn_01GSKV8120EYRWBHAW915M0QE5',
		slug: 'rusa-lgbt',
	},
	{
		value: 'RIF Asylum Support',
		name: 'RIF Asylum Support',
		id: 'orgn_01GSKV812HYNB02ZGABFXAGNHP',
		slug: 'rif-asylum-support',
	},
	{
		value: 'Jewish Family Services of Western New York',
		name: 'Jewish Family Services of Western New York',
		id: 'orgn_01GSKV8134SBEQ5E34JCMKDAFS',
		slug: 'jewish-family-services-of-western-new-york',
	},
	{
		value: "HealthRight International's Human Rights Clinic (HRC)",
		name: "HealthRight International's Human Rights Clinic (HRC)",
		id: 'orgn_01GSKV813SGKXCKZWWX484G5WR',
		slug: 'healthright-internationals-human-rights-clinic-hrc',
	},
	{
		value: 'BronxWorks',
		name: 'BronxWorks',
		id: 'orgn_01GSKV814BV7YGZ46HCTJPAYDA',
		slug: 'bronxworks',
	},
]
