export const surveyOptions = {
	community: [
		{
			id: 'ucom_RANDOMID',
			community: 'data to be populated',
			tsKey: 'string',
			tsNs: 'user',
		},
		{
			id: 'ucom_RANDOMID2',
			community: 'data to be populated 2',
			tsKey: 'string',
			tsNs: 'user',
		},
		{
			id: 'ucom_RANDOMID3',
			community: 'data to be populated 3',
			tsKey: 'string',
			tsNs: 'user',
		},
		{
			id: 'ucom_RANDOMID4',
			community: 'data to be populated 4',
			tsKey: 'string',
			tsNs: 'user',
		},
	],
	countries: [
		{
			cca2: 'GT',
			id: 'ctry_01GW2HHDK6BPY9VBW9WR5HDVA5',
			tsKey: 'GTM.name',
			tsNs: 'country',
		},
		{
			cca2: 'BD',
			id: 'ctry_01GW2HHDK67CD2NGY24P7G22SF',
			tsKey: 'BGD.name',
			tsNs: 'country',
		},
		{
			cca2: 'AS',
			id: 'ctry_01GW2HHDK67GZQVGA3NZ8PE5SS',
			tsKey: 'ASM.name',
			tsNs: 'country',
		},
		{
			cca2: 'IT',
			id: 'ctry_01GW2HHDK65BRH9H4P9YZH3P3F',
			tsKey: 'ITA.name',
			tsNs: 'country',
		},
		{
			cca2: 'DZ',
			id: 'ctry_01GW2HHDK6ENG0N2YD2ZXD043N',
			tsKey: 'DZA.name',
			tsNs: 'country',
		},
		{
			cca2: 'FR',
			id: 'ctry_01GW2HHDK6TWQ3BN3PG06DQ3HM',
			tsKey: 'FRA.name',
			tsNs: 'country',
		},
		{
			cca2: 'BT',
			id: 'ctry_01GW2HHDK7QA15RA6W4YR0YTPQ',
			tsKey: 'BTN.name',
			tsNs: 'country',
		},
		{
			cca2: 'ST',
			id: 'ctry_01GW2HHDK73TNXH3DFC5BV244P',
			tsKey: 'STP.name',
			tsNs: 'country',
		},
		{
			cca2: 'NR',
			id: 'ctry_01GW2HHDK79QNCV8EVYND8E6MY',
			tsKey: 'NRU.name',
			tsNs: 'country',
		},
		{
			cca2: 'GA',
			id: 'ctry_01GW2HHDK7Z5N9Q2JPZNXP8VPE',
			tsKey: 'GAB.name',
			tsNs: 'country',
		},
		{
			cca2: 'NC',
			id: 'ctry_01GW2HHDK7HMC32S6PHPMFACZX',
			tsKey: 'NCL.name',
			tsNs: 'country',
		},
		{
			cca2: 'NO',
			id: 'ctry_01GW2HHDK74HTQCYV1EVM79B1G',
			tsKey: 'NOR.name',
			tsNs: 'country',
		},
		{
			cca2: 'TV',
			id: 'ctry_01GW2HHDK7BMH7NEWWCXXE4XTG',
			tsKey: 'TUV.name',
			tsNs: 'country',
		},
		{
			cca2: 'IN',
			id: 'ctry_01GW2HHDK7H0GWV1MRQ6EF6E8N',
			tsKey: 'IND.name',
			tsNs: 'country',
		},
		{
			cca2: 'KH',
			id: 'ctry_01GW2HHDK7T16K1ZJ1PZX1E1ZV',
			tsKey: 'KHM.name',
			tsNs: 'country',
		},
		{
			cca2: 'MU',
			id: 'ctry_01GW2HHDK7DF62BBZYJCBFGVYY',
			tsKey: 'MUS.name',
			tsNs: 'country',
		},
		{
			cca2: 'CD',
			id: 'ctry_01GW2HHDK7AMX8NEKVMBA64YJS',
			tsKey: 'COD.name',
			tsNs: 'country',
		},
		{
			cca2: 'SM',
			id: 'ctry_01GW2HHDK796T1HRBRQMRV2ZGH',
			tsKey: 'SMR.name',
			tsNs: 'country',
		},
		{
			cca2: 'PA',
			id: 'ctry_01GW2HHDK7JEDGYF9BQBZVDW0X',
			tsKey: 'PAN.name',
			tsNs: 'country',
		},
		{
			cca2: 'NL',
			id: 'ctry_01GW2HHDK76HGWY2MNZTFSTT61',
			tsKey: 'NLD.name',
			tsNs: 'country',
		},
		{
			cca2: 'NI',
			id: 'ctry_01GW2HHDK7372NTNTPP3V9BPGV',
			tsKey: 'NIC.name',
			tsNs: 'country',
		},
		{
			cca2: 'RE',
			id: 'ctry_01GW2HHDK7HX3TFSB0HX6YDCRR',
			tsKey: 'REU.name',
			tsNs: 'country',
		},
		{
			cca2: 'SL',
			id: 'ctry_01GW2HHDK70QBRG8S7ZXZP89W9',
			tsKey: 'SLE.name',
			tsNs: 'country',
		},
		{
			cca2: 'BB',
			id: 'ctry_01GW2HHDK8SPF3A2D6NW2XPTHM',
			tsKey: 'BRB.name',
			tsNs: 'country',
		},
		{
			cca2: 'IL',
			id: 'ctry_01GW2HHDK8JM827C3VY37CM7TF',
			tsKey: 'ISR.name',
			tsNs: 'country',
		},
		{
			cca2: 'EH',
			id: 'ctry_01GW2HHDK87660QN220M6T4S2K',
			tsKey: 'ESH.name',
			tsNs: 'country',
		},
		{
			cca2: 'AI',
			id: 'ctry_01GW2HHDK87VQBC3WXQDJJZ6XM',
			tsKey: 'AIA.name',
			tsNs: 'country',
		},
		{
			cca2: 'RW',
			id: 'ctry_01GW2HHDK8ZYZHYB9CAVW6C4ER',
			tsKey: 'RWA.name',
			tsNs: 'country',
		},
		{
			cca2: 'TR',
			id: 'ctry_01GW2HHDK8NAY2T3GHNV1HVD3M',
			tsKey: 'TUR.name',
			tsNs: 'country',
		},
		{
			cca2: 'MH',
			id: 'ctry_01GW2HHDK8HTCM0MWQXBJRXEYB',
			tsKey: 'MHL.name',
			tsNs: 'country',
		},
		{
			cca2: 'MZ',
			id: 'ctry_01GW2HHDK8VJ7Z7R0D99K5E4AN',
			tsKey: 'MOZ.name',
			tsNs: 'country',
		},
		{
			cca2: 'NG',
			id: 'ctry_01GW2HHDK8AXT584ZTWBN739SN',
			tsKey: 'NGA.name',
			tsNs: 'country',
		},
		{
			cca2: 'RU',
			id: 'ctry_01GW2HHDK8A3W54F0AW64VV2GD',
			tsKey: 'RUS.name',
			tsNs: 'country',
		},
		{
			cca2: 'CU',
			id: 'ctry_01GW2HHDK8K7BJH8JW34Q7JK12',
			tsKey: 'CUB.name',
			tsNs: 'country',
		},
		{
			cca2: 'JE',
			id: 'ctry_01GW2HHDK8NAN0FT6100XB79PX',
			tsKey: 'JEY.name',
			tsNs: 'country',
		},
		{
			cca2: 'VG',
			id: 'ctry_01GW2HHDK88EQB8BSKDWEPG76N',
			tsKey: 'VGB.name',
			tsNs: 'country',
		},
		{
			cca2: 'CR',
			id: 'ctry_01GW2HHDK8WHEVKX1JE6V2E5JJ',
			tsKey: 'CRI.name',
			tsNs: 'country',
		},
		{
			cca2: 'PM',
			id: 'ctry_01GW2HHDK8MZVCAHNP3EBTHDGH',
			tsKey: 'SPM.name',
			tsNs: 'country',
		},
		{
			cca2: 'SV',
			id: 'ctry_01GW2HHDK8HE6ZXBJEN5GGJYBA',
			tsKey: 'SLV.name',
			tsNs: 'country',
		},
		{
			cca2: 'HN',
			id: 'ctry_01GW2HHDK96FCPGE9HBHC01VDE',
			tsKey: 'HND.name',
			tsNs: 'country',
		},
		{
			cca2: 'MO',
			id: 'ctry_01GW2HHDK9114P6V7VFFNFTMNP',
			tsKey: 'MAC.name',
			tsNs: 'country',
		},
		{
			cca2: 'GM',
			id: 'ctry_01GW2HHDK90V1XFYZ6AWB05J58',
			tsKey: 'GMB.name',
			tsNs: 'country',
		},
		{
			cca2: 'MM',
			id: 'ctry_01GW2HHDK99MQM7GZ8EN4WZ9FK',
			tsKey: 'MMR.name',
			tsNs: 'country',
		},
		{
			cca2: 'EG',
			id: 'ctry_01GW2HHDK9ZK9PGCD8MGCD8YN9',
			tsKey: 'EGY.name',
			tsNs: 'country',
		},
		{
			cca2: 'LB',
			id: 'ctry_01GW2HHDK9NG4F38ZGH49JE311',
			tsKey: 'LBN.name',
			tsNs: 'country',
		},
		{
			cca2: 'KE',
			id: 'ctry_01GW2HHDK9D4RQ30ZEV336H36F',
			tsKey: 'KEN.name',
			tsNs: 'country',
		},
		{
			cca2: 'GQ',
			id: 'ctry_01GW2HHDK95TZ43CS71K1P62JD',
			tsKey: 'GNQ.name',
			tsNs: 'country',
		},
		{
			cca2: 'HR',
			id: 'ctry_01GW2HHDK9SZZ6W0GPYA0STVYG',
			tsKey: 'HRV.name',
			tsNs: 'country',
		},
		{
			cca2: 'BQ',
			id: 'ctry_01GW2HHDK9JPEM2C72VSS71G4H',
			tsKey: 'BES.name',
			tsNs: 'country',
		},
		{
			cca2: 'PH',
			id: 'ctry_01GW2HHDKAQTGEVED1E27QW61N',
			tsKey: 'PHL.name',
			tsNs: 'country',
		},
		{
			cca2: 'KZ',
			id: 'ctry_01GW2HHDKAE2X1VJCYX05SQ15T',
			tsKey: 'KAZ.name',
			tsNs: 'country',
		},
		{
			cca2: 'XK',
			id: 'ctry_01GW2HHDKA32KTYFEBFF1FRX6G',
			tsKey: 'UNK.name',
			tsNs: 'country',
		},
		{
			cca2: 'AR',
			id: 'ctry_01GW2HHDKAYQQC5ZYAY81QFF4G',
			tsKey: 'ARG.name',
			tsNs: 'country',
		},
		{
			cca2: 'PT',
			id: 'ctry_01GW2HHDK9W45HXETV96K8CZAZ',
			tsKey: 'PRT.name',
			tsNs: 'country',
		},
		{
			cca2: 'TT',
			id: 'ctry_01GW2HHDK94QVSXT8Q12EDB4XP',
			tsKey: 'TTO.name',
			tsNs: 'country',
		},
		{
			cca2: 'TJ',
			id: 'ctry_01GW2HHDKAHQVZWP2NHE3A02B5',
			tsKey: 'TJK.name',
			tsNs: 'country',
		},
		{
			cca2: 'AZ',
			id: 'ctry_01GW2HHDKA3CZ3WF381DJZ5D0Z',
			tsKey: 'AZE.name',
			tsNs: 'country',
		},
		{
			cca2: 'RO',
			id: 'ctry_01GW2HHDKAGCFGK8W1ZFE62QKQ',
			tsKey: 'ROU.name',
			tsNs: 'country',
		},
		{
			cca2: 'CL',
			id: 'ctry_01GW2HHDKAMPFS09WBC3XZHQKX',
			tsKey: 'CHL.name',
			tsNs: 'country',
		},
		{
			cca2: 'CY',
			id: 'ctry_01GW2HHDKAZ27CDARTX8QS2JMN',
			tsKey: 'CYP.name',
			tsNs: 'country',
		},
		{
			cca2: 'CV',
			id: 'ctry_01GW2HHDKAJ64YAST64W2BJQSV',
			tsKey: 'CPV.name',
			tsNs: 'country',
		},
		{
			cca2: 'BG',
			id: 'ctry_01GW2HHDKAWJN8K8E3EYVZDENE',
			tsKey: 'BGR.name',
			tsNs: 'country',
		},
		{
			cca2: 'UY',
			id: 'ctry_01GW2HHDKAZYVYFHDZNZDE4HPB',
			tsKey: 'URY.name',
			tsNs: 'country',
		},
		{
			cca2: 'MK',
			id: 'ctry_01GW2HHDKAKGTGCFFE8HQGZXF4',
			tsKey: 'MKD.name',
			tsNs: 'country',
		},
		{
			cca2: 'AF',
			id: 'ctry_01GW2HHDKATDZGNR55QRS6Y5NX',
			tsKey: 'AFG.name',
			tsNs: 'country',
		},
		{
			cca2: 'BW',
			id: 'ctry_01GW2HHDKA6G8FACKBG654B237',
			tsKey: 'BWA.name',
			tsNs: 'country',
		},
		{
			cca2: 'AQ',
			id: 'ctry_01GW2HHDKAFPAWV4NQHE9VT4BA',
			tsKey: 'ATA.name',
			tsNs: 'country',
		},
		{
			cca2: 'MR',
			id: 'ctry_01GW2HHDKAR1506PSRF3PB1HYX',
			tsKey: 'MRT.name',
			tsNs: 'country',
		},
		{
			cca2: 'QA',
			id: 'ctry_01GW2HHDKA77DT55ZPJ8XKM8P3',
			tsKey: 'QAT.name',
			tsNs: 'country',
		},
		{
			cca2: 'ES',
			id: 'ctry_01GW2HHDKAMRVA2E0TZBFPX7VF',
			tsKey: 'ESP.name',
			tsNs: 'country',
		},
		{
			cca2: 'YE',
			id: 'ctry_01GW2HHDKA60427HJJGXNGC3EV',
			tsKey: 'YEM.name',
			tsNs: 'country',
		},
		{
			cca2: 'SO',
			id: 'ctry_01GW2HHDKBHVDM3WCVS2THFMHT',
			tsKey: 'SOM.name',
			tsNs: 'country',
		},
		{
			cca2: 'SE',
			id: 'ctry_01GW2HHDKBCAGQ1RJGC3ZP6Z5S',
			tsKey: 'SWE.name',
			tsNs: 'country',
		},
		{
			cca2: 'LI',
			id: 'ctry_01GW2HHDKBKDT96T91NCRFZE8A',
			tsKey: 'LIE.name',
			tsNs: 'country',
		},
		{
			cca2: 'GS',
			id: 'ctry_01GW2HHDKBM1E4N9900Q4N942Y',
			tsKey: 'SGS.name',
			tsNs: 'country',
		},
		{
			cca2: 'MA',
			id: 'ctry_01GW2HHDKBJ9NNQ06K5V64NAB8',
			tsKey: 'MAR.name',
			tsNs: 'country',
		},
		{
			cca2: 'MG',
			id: 'ctry_01GW2HHDKBN3B46NQY3YEACJ0K',
			tsKey: 'MDG.name',
			tsNs: 'country',
		},
		{
			cca2: 'UA',
			id: 'ctry_01GW2HHDKBX833SWMMRHFEXGDG',
			tsKey: 'UKR.name',
			tsNs: 'country',
		},
		{
			cca2: 'IR',
			id: 'ctry_01GW2HHDKBEYBGKWE7BCHXZHJ6',
			tsKey: 'IRN.name',
			tsNs: 'country',
		},
		{
			cca2: 'PL',
			id: 'ctry_01GW2HHDKBRG2CC67WN648YK7S',
			tsKey: 'POL.name',
			tsNs: 'country',
		},
		{
			cca2: 'TD',
			id: 'ctry_01GW2HHDKBDJH4JA3QZRZCDB1C',
			tsKey: 'TCD.name',
			tsNs: 'country',
		},
		{
			cca2: 'VU',
			id: 'ctry_01GW2HHDKBARW56WYXTBMBX9Z8',
			tsKey: 'VUT.name',
			tsNs: 'country',
		},
		{
			cca2: 'PW',
			id: 'ctry_01GW2HHDKBRDF1DMR5DA9DAT7K',
			tsKey: 'PLW.name',
			tsNs: 'country',
		},
		{
			cca2: 'PE',
			id: 'ctry_01GW2HHDKBRRZ84X368SH12W7Q',
			tsKey: 'PER.name',
			tsNs: 'country',
		},
		{
			cca2: 'SZ',
			id: 'ctry_01GW2HHDKBT6AMAW7JQ18MAEGF',
			tsKey: 'SWZ.name',
			tsNs: 'country',
		},
		{
			cca2: 'MQ',
			id: 'ctry_01GW2HHDKB96KWQYA4T0D8VXTV',
			tsKey: 'MTQ.name',
			tsNs: 'country',
		},
		{
			cca2: 'LU',
			id: 'ctry_01GW2HHDKBTPBSDQE1XHBMBXJE',
			tsKey: 'LUX.name',
			tsNs: 'country',
		},
		{
			cca2: 'DJ',
			id: 'ctry_01GW2HHDKBS9SYM4Z85HKVCW7S',
			tsKey: 'DJI.name',
			tsNs: 'country',
		},
		{
			cca2: 'HT',
			id: 'ctry_01GW2HHDKBP9EB7HW41MH04MCA',
			tsKey: 'HTI.name',
			tsNs: 'country',
		},
		{
			cca2: 'SY',
			id: 'ctry_01GW2HHDKBCYJXSMFM5N5VW3Q5',
			tsKey: 'SYR.name',
			tsNs: 'country',
		},
		{
			cca2: 'GI',
			id: 'ctry_01GW2HHDKBW4RFHHBG7R71M5B5',
			tsKey: 'GIB.name',
			tsNs: 'country',
		},
		{
			cca2: 'IS',
			id: 'ctry_01GW2HHDKB1FFT4ZEBATSQXWRB',
			tsKey: 'ISL.name',
			tsNs: 'country',
		},
		{
			cca2: 'FJ',
			id: 'ctry_01GW2HHDKC0MEFFZTGK0RWCRQA',
			tsKey: 'FJI.name',
			tsNs: 'country',
		},
		{
			cca2: 'KP',
			id: 'ctry_01GW2HHDKCQX4EJEVCEME3EEBS',
			tsKey: 'PRK.name',
			tsNs: 'country',
		},
		{
			cca2: 'SB',
			id: 'ctry_01GW2HHDKC5TFN4HP9KQ7QCQR9',
			tsKey: 'SLB.name',
			tsNs: 'country',
		},
		{
			cca2: 'UM',
			id: 'ctry_01GW2HHDKCRS9KW4FG2WR2GG06',
			tsKey: 'UMI.name',
			tsNs: 'country',
		},
		{
			cca2: 'GN',
			id: 'ctry_01GW2HHDKCK11551EN1JD1AMT6',
			tsKey: 'GIN.name',
			tsNs: 'country',
		},
		{
			cca2: 'KN',
			id: 'ctry_01GW2HHDKC0N6MV90J9VWJ6CQN',
			tsKey: 'KNA.name',
			tsNs: 'country',
		},
		{
			cca2: 'TF',
			id: 'ctry_01GW2HHDKCZ5TVB7QPAQNRS362',
			tsKey: 'ATF.name',
			tsNs: 'country',
		},
		{
			cca2: 'BH',
			id: 'ctry_01GW2HHDKCBYW7V5T1DWEBPFRV',
			tsKey: 'BHR.name',
			tsNs: 'country',
		},
		{
			cca2: 'LT',
			id: 'ctry_01GW2HHDKC6BNE39T2DV3QC4NJ',
			tsKey: 'LTU.name',
			tsNs: 'country',
		},
		{
			cca2: 'GE',
			id: 'ctry_01GW2HHDKCJV96MQND976G21HR',
			tsKey: 'GEO.name',
			tsNs: 'country',
		},
		{
			cca2: 'RS',
			id: 'ctry_01GW2HHDKCGEP7FXQHWTQWB904',
			tsKey: 'SRB.name',
			tsNs: 'country',
		},
		{
			cca2: 'CF',
			id: 'ctry_01GW2HHDKCW140K2TYTEE750YT',
			tsKey: 'CAF.name',
			tsNs: 'country',
		},
		{
			cca2: 'ML',
			id: 'ctry_01GW2HHDKCFG7G5S12F71S6QG5',
			tsKey: 'MLI.name',
			tsNs: 'country',
		},
		{
			cca2: 'MN',
			id: 'ctry_01GW2HHDKC2Q96XZGFSTMMQPNB',
			tsKey: 'MNG.name',
			tsNs: 'country',
		},
		{
			cca2: 'DM',
			id: 'ctry_01GW2HHDKCVDAHZVSVC2YD68XN',
			tsKey: 'DMA.name',
			tsNs: 'country',
		},
		{
			cca2: 'GL',
			id: 'ctry_01GW2HHDKCBG5RYMSXJ7NE0EQH',
			tsKey: 'GRL.name',
			tsNs: 'country',
		},
		{
			cca2: 'ET',
			id: 'ctry_01GW2HHDKC2S12HZKRBMRC51WB',
			tsKey: 'ETH.name',
			tsNs: 'country',
		},
		{
			cca2: 'LY',
			id: 'ctry_01GW2HHDKC77VK7AC2YXTJFP9H',
			tsKey: 'LBY.name',
			tsNs: 'country',
		},
		{
			cca2: 'NA',
			id: 'ctry_01GW2HHDKCGYGA9KDYNQ3CK7H7',
			tsKey: 'NAM.name',
			tsNs: 'country',
		},
		{
			cca2: 'MD',
			id: 'ctry_01GW2HHDKCZNJN6F1J1JTQRZ25',
			tsKey: 'MDA.name',
			tsNs: 'country',
		},
		{
			cca2: 'BO',
			id: 'ctry_01GW2HHDKCS87MJP31FAC9S4NB',
			tsKey: 'BOL.name',
			tsNs: 'country',
		},
		{
			cca2: 'DO',
			id: 'ctry_01GW2HHDKCGAXYVWHRWSD40516',
			tsKey: 'DOM.name',
			tsNs: 'country',
		},
		{
			cca2: 'CW',
			id: 'ctry_01GW2HHDKDEHGJVDQC1VDXFM0P',
			tsKey: 'CUW.name',
			tsNs: 'country',
		},
		{
			cca2: 'ID',
			id: 'ctry_01GW2HHDKDHB62D7NFGE7RRNDN',
			tsKey: 'IDN.name',
			tsNs: 'country',
		},
		{
			cca2: 'BY',
			id: 'ctry_01GW2HHDKD14G6PFAPNEMTW5F5',
			tsKey: 'BLR.name',
			tsNs: 'country',
		},
		{
			cca2: 'BV',
			id: 'ctry_01GW2HHDKDSY01QJC6KX2BRXH8',
			tsKey: 'BVT.name',
			tsNs: 'country',
		},
		{
			cca2: 'CG',
			id: 'ctry_01GW2HHDKD20967VJAPNPBARXM',
			tsKey: 'COG.name',
			tsNs: 'country',
		},
		{
			cca2: 'LR',
			id: 'ctry_01GW2HHDKDHEQGH45498FKFDM8',
			tsKey: 'LBR.name',
			tsNs: 'country',
		},
		{
			cca2: 'MT',
			id: 'ctry_01GW2HHDKDD06KYX7CY9JJR1SQ',
			tsKey: 'MLT.name',
			tsNs: 'country',
		},
		{
			cca2: 'MF',
			id: 'ctry_01GW2HHDKD311V08MQJWG7CK03',
			tsKey: 'MAF.name',
			tsNs: 'country',
		},
		{
			cca2: 'ZA',
			id: 'ctry_01GW2HHDKDNEGQ31JPB4V9BBMK',
			tsKey: 'ZAF.name',
			tsNs: 'country',
		},
		{
			cca2: 'TG',
			id: 'ctry_01GW2HHDKDMWST2K7SVAAEP7K5',
			tsKey: 'TGO.name',
			tsNs: 'country',
		},
		{
			cca2: 'AM',
			id: 'ctry_01GW2HHDKD3SFPCG8ED0EP3MX3',
			tsKey: 'ARM.name',
			tsNs: 'country',
		},
		{
			cca2: 'SH',
			id: 'ctry_01GW2HHDKD9T5SF5CAMVPA1M4F',
			tsKey: 'SHN.name',
			tsNs: 'country',
		},
		{
			cca2: 'AL',
			id: 'ctry_01GW2HHDKDSS3YW7W5994KW3ZT',
			tsKey: 'ALB.name',
			tsNs: 'country',
		},
		{
			cca2: 'AD',
			id: 'ctry_01GW2HHDKDE152HYH5H1TD8CK6',
			tsKey: 'AND.name',
			tsNs: 'country',
		},
		{
			cca2: 'SS',
			id: 'ctry_01GW2HHDKD48PB3V9R7ZWXZ3KP',
			tsKey: 'SSD.name',
			tsNs: 'country',
		},
		{
			cca2: 'GG',
			id: 'ctry_01GW2HHDKDXS2FKHD8YPRKBZPY',
			tsKey: 'GGY.name',
			tsNs: 'country',
		},
		{
			cca2: 'AE',
			id: 'ctry_01GW2HHDKDXBNPG01NBMPKYFZ2',
			tsKey: 'ARE.name',
			tsNs: 'country',
		},
		{
			cca2: 'CZ',
			id: 'ctry_01GW2HHDKDWZR3XW85F2G82SME',
			tsKey: 'CZE.name',
			tsNs: 'country',
		},
		{
			cca2: 'GP',
			id: 'ctry_01GW2HHDKDT4XD73Q57W6631FN',
			tsKey: 'GLP.name',
			tsNs: 'country',
		},
		{
			cca2: 'GD',
			id: 'ctry_01GW2HHDKDK9BZQS106Q7H8XJR',
			tsKey: 'GRD.name',
			tsNs: 'country',
		},
		{
			cca2: 'PK',
			id: 'ctry_01GW2HHDKDDHRPPGSEFG2P69F0',
			tsKey: 'PAK.name',
			tsNs: 'country',
		},
		{
			cca2: 'VA',
			id: 'ctry_01GW2HHDKD09MHFTWE9SKVMMJ0',
			tsKey: 'VAT.name',
			tsNs: 'country',
		},
		{
			cca2: 'WF',
			id: 'ctry_01GW2HHDKEYSJWN1W0AYDS0NH4',
			tsKey: 'WLF.name',
			tsNs: 'country',
		},
		{
			cca2: 'SJ',
			id: 'ctry_01GW2HHDKEG4RY89ACRQMNT8SB',
			tsKey: 'SJM.name',
			tsNs: 'country',
		},
		{
			cca2: 'CM',
			id: 'ctry_01GW2HHDKEZMTF03P4JYAFZRN1',
			tsKey: 'CMR.name',
			tsNs: 'country',
		},
		{
			cca2: 'JM',
			id: 'ctry_01GW2HHDKEVZK4MDJTHQ025AQG',
			tsKey: 'JAM.name',
			tsNs: 'country',
		},
		{
			cca2: 'KM',
			id: 'ctry_01GW2HHDKE2EJHZ22HF2GWSB4H',
			tsKey: 'COM.name',
			tsNs: 'country',
		},
		{
			cca2: 'FK',
			id: 'ctry_01GW2HHDKE1JW9G222WXWADT5M',
			tsKey: 'FLK.name',
			tsNs: 'country',
		},
		{
			cca2: 'TM',
			id: 'ctry_01GW2HHDKEFVF6N0VM03AGGZF7',
			tsKey: 'TKM.name',
			tsNs: 'country',
		},
		{
			cca2: 'BN',
			id: 'ctry_01GW2HHDKEGN1AYW58P63XQPZ0',
			tsKey: 'BRN.name',
			tsNs: 'country',
		},
		{
			cca2: 'GH',
			id: 'ctry_01GW2HHDKEW7A1ZRA4EFNWN6FB',
			tsKey: 'GHA.name',
			tsNs: 'country',
		},
		{
			cca2: 'KW',
			id: 'ctry_01GW2HHDKE2127XE2CXSCB0SWG',
			tsKey: 'KWT.name',
			tsNs: 'country',
		},
		{
			cca2: 'ER',
			id: 'ctry_01GW2HHDKE6ZTA1B0KNFYXA7XZ',
			tsKey: 'ERI.name',
			tsNs: 'country',
		},
		{
			cca2: 'ZW',
			id: 'ctry_01GW2HHDKENXBKBZTFJ4PA6Z2C',
			tsKey: 'ZWE.name',
			tsNs: 'country',
		},
		{
			cca2: 'TZ',
			id: 'ctry_01GW2HHDKE97QHYGJXTAGWENKK',
			tsKey: 'TZA.name',
			tsNs: 'country',
		},
		{
			cca2: 'EE',
			id: 'ctry_01GW2HHDKEM266QFKJYJVHC53T',
			tsKey: 'EST.name',
			tsNs: 'country',
		},
		{
			cca2: 'BZ',
			id: 'ctry_01GW2HHDKEZN2DQG8Y7XVGHA0G',
			tsKey: 'BLZ.name',
			tsNs: 'country',
		},
		{
			cca2: 'SA',
			id: 'ctry_01GW2HHDKE6SRWQT7YKMEV7N5Y',
			tsKey: 'SAU.name',
			tsNs: 'country',
		},
		{
			cca2: 'NZ',
			id: 'ctry_01GW2HHDKEKF565F1E5ZPTXFHE',
			tsKey: 'NZL.name',
			tsNs: 'country',
		},
		{
			cca2: 'TC',
			id: 'ctry_01GW2HHDKEE1FJ2XTH7MA2AZP1',
			tsKey: 'TCA.name',
			tsNs: 'country',
		},
		{
			cca2: 'CO',
			id: 'ctry_01GW2HHDKE747AN7G49Z1R39X7',
			tsKey: 'COL.name',
			tsNs: 'country',
		},
		{
			cca2: 'MY',
			id: 'ctry_01GW2HHDKEZED648DCY8RGH5NA',
			tsKey: 'MYS.name',
			tsNs: 'country',
		},
		{
			cca2: 'AG',
			id: 'ctry_01GW2HHDKE7QG3QATZ72P7YT7V',
			tsKey: 'ATG.name',
			tsNs: 'country',
		},
		{
			cca2: 'BM',
			id: 'ctry_01GW2HHDKE6FEQT1R83S60KVPT',
			tsKey: 'BMU.name',
			tsNs: 'country',
		},
		{
			cca2: 'AT',
			id: 'ctry_01GW2HHDKEH1KYC4T8236ZSY3C',
			tsKey: 'AUT.name',
			tsNs: 'country',
		},
		{
			cca2: 'WS',
			id: 'ctry_01GW2HHDKFTYX6T84QB1WZYYAY',
			tsKey: 'WSM.name',
			tsNs: 'country',
		},
		{
			cca2: 'UG',
			id: 'ctry_01GW2HHDKF91Z0RAW6TC6P5TAP',
			tsKey: 'UGA.name',
			tsNs: 'country',
		},
		{
			cca2: 'NP',
			id: 'ctry_01GW2HHDKFT9BZY0XPP6DESZX8',
			tsKey: 'NPL.name',
			tsNs: 'country',
		},
		{
			cca2: 'PY',
			id: 'ctry_01GW2HHDKF47X5KGDW8RWF841A',
			tsKey: 'PRY.name',
			tsNs: 'country',
		},
		{
			cca2: 'AU',
			id: 'ctry_01GW2HHDKFCKFTFJP7MARGNHRZ',
			tsKey: 'AUS.name',
			tsNs: 'country',
		},
		{
			cca2: 'FO',
			id: 'ctry_01GW2HHDKF8Y6KNW8X28APN60W',
			tsKey: 'FRO.name',
			tsNs: 'country',
		},
		{
			cca2: 'GB',
			id: 'ctry_01GW2HHDKFTPR1W2P2M9E081J5',
			tsKey: 'GBR.name',
			tsNs: 'country',
		},
		{
			cca2: 'TK',
			id: 'ctry_01GW2HHDKFRPGM3P3HD5747R23',
			tsKey: 'TKL.name',
			tsNs: 'country',
		},
		{
			cca2: 'ZM',
			id: 'ctry_01GW2HHDKFPXSJ18WSJ8GEZKJ0',
			tsKey: 'ZMB.name',
			tsNs: 'country',
		},
		{
			cca2: 'LC',
			id: 'ctry_01GW2HHDKFPY9T4YYDFWGBZP5P',
			tsKey: 'LCA.name',
			tsNs: 'country',
		},
		{
			cca2: 'IM',
			id: 'ctry_01GW2HHDKFFE67B6CGZGV25R1C',
			tsKey: 'IMN.name',
			tsNs: 'country',
		},
		{
			cca2: 'KG',
			id: 'ctry_01GW2HHDKFGDMKVKEAVVCVHXG4',
			tsKey: 'KGZ.name',
			tsNs: 'country',
		},
		{
			cca2: 'PF',
			id: 'ctry_01GW2HHDKFK3ME6G5ZNBVT26XS',
			tsKey: 'PYF.name',
			tsNs: 'country',
		},
		{
			cca2: 'EC',
			id: 'ctry_01GW2HHDKFWZA5DF33HK20AMQK',
			tsKey: 'ECU.name',
			tsNs: 'country',
		},
		{
			cca2: 'HK',
			id: 'ctry_01GW2HHDKF1ZKQGXHGKH67QXYA',
			tsKey: 'HKG.name',
			tsNs: 'country',
		},
		{
			cca2: 'MP',
			id: 'ctry_01GW2HHDKFJ4Q7PBTTN4GSMPV0',
			tsKey: 'MNP.name',
			tsNs: 'country',
		},
		{
			cca2: 'TL',
			id: 'ctry_01GW2HHDKF1NR34T2G6FMKQCYD',
			tsKey: 'TLS.name',
			tsNs: 'country',
		},
		{
			cca2: 'VC',
			id: 'ctry_01GW2HHDKFYB0C2FBC8KQ50M36',
			tsKey: 'VCT.name',
			tsNs: 'country',
		},
		{
			cca2: 'VN',
			id: 'ctry_01GW2HHDKFX9C6AWNQ3F32P95P',
			tsKey: 'VNM.name',
			tsNs: 'country',
		},
		{
			cca2: 'HM',
			id: 'ctry_01GW2HHDKFVJ4QNETXPR3PGZES',
			tsKey: 'HMD.name',
			tsNs: 'country',
		},
		{
			cca2: 'IE',
			id: 'ctry_01GW2HHDKF939YJGVTR7H30KPX',
			tsKey: 'IRL.name',
			tsNs: 'country',
		},
		{
			cca2: 'FI',
			id: 'ctry_01GW2HHDKFPPCXV7F8BNVZZ81G',
			tsKey: 'FIN.name',
			tsNs: 'country',
		},
		{
			cca2: 'JP',
			id: 'ctry_01GW2HHDKFEWN5X3FJ1QFQ55NW',
			tsKey: 'JPN.name',
			tsNs: 'country',
		},
		{
			cca2: 'IO',
			id: 'ctry_01GW2HHDKG19TTZ3XA7NKMZ3TJ',
			tsKey: 'IOT.name',
			tsNs: 'country',
		},
		{
			cca2: 'NF',
			id: 'ctry_01GW2HHDKGHKX9XHGFYN7FAF95',
			tsKey: 'NFK.name',
			tsNs: 'country',
		},
		{
			cca2: 'BR',
			id: 'ctry_01GW2HHDKGTHZA8H042BMMGF3J',
			tsKey: 'BRA.name',
			tsNs: 'country',
		},
		{
			cca2: 'ME',
			id: 'ctry_01GW2HHDKGA35BCNN91RB2DFX7',
			tsKey: 'MNE.name',
			tsNs: 'country',
		},
		{
			cca2: 'GY',
			id: 'ctry_01GW2HHDKGRJCTDX2GK4ZZDKAS',
			tsKey: 'GUY.name',
			tsNs: 'country',
		},
		{
			cca2: 'SK',
			id: 'ctry_01GW2HHDKG21ZM449SKC9HB5YK',
			tsKey: 'SVK.name',
			tsNs: 'country',
		},
		{
			cca2: 'MC',
			id: 'ctry_01GW2HHDKGB3V0H2DKQA84VA5K',
			tsKey: 'MCO.name',
			tsNs: 'country',
		},
		{
			cca2: 'CN',
			id: 'ctry_01GW2HHDKGEYB1AM0P2DVYBS7A',
			tsKey: 'CHN.name',
			tsNs: 'country',
		},
		{
			cca2: 'AW',
			id: 'ctry_01GW2HHDKGHT708N7RM8QDDEBK',
			tsKey: 'ABW.name',
			tsNs: 'country',
		},
		{
			cca2: 'LA',
			id: 'ctry_01GW2HHDKG8SKA53C146FV5E0G',
			tsKey: 'LAO.name',
			tsNs: 'country',
		},
		{
			cca2: 'VE',
			id: 'ctry_01GW2HHDKGJG43HR2M2T7JQ5DC',
			tsKey: 'VEN.name',
			tsNs: 'country',
		},
		{
			cca2: 'PS',
			id: 'ctry_01GW2HHDKGRRZM6X62GJ3M62Z4',
			tsKey: 'PSE.name',
			tsNs: 'country',
		},
		{
			cca2: 'SX',
			id: 'ctry_01GW2HHDKGQMAVVKJ3SPPCS689',
			tsKey: 'SXM.name',
			tsNs: 'country',
		},
		{
			cca2: 'HU',
			id: 'ctry_01GW2HHDKGGQ8SZPJH74RXNCP6',
			tsKey: 'HUN.name',
			tsNs: 'country',
		},
		{
			cca2: 'DE',
			id: 'ctry_01GW2HHDKGGTVBR39ZYJVVDGNY',
			tsKey: 'DEU.name',
			tsNs: 'country',
		},
		{
			cca2: 'TO',
			id: 'ctry_01GW2HHDKG1TWFSYE4QQ6CRFX7',
			tsKey: 'TON.name',
			tsNs: 'country',
		},
		{
			cca2: 'IQ',
			id: 'ctry_01GW2HHDKGM9N3RGKASW4677KV',
			tsKey: 'IRQ.name',
			tsNs: 'country',
		},
		{
			cca2: 'TH',
			id: 'ctry_01GW2HHDKGVAGE7SGTXWD5V2EP',
			tsKey: 'THA.name',
			tsNs: 'country',
		},
		{
			cca2: 'SC',
			id: 'ctry_01GW2HHDKHF02X3NEPGZ12ZFZV',
			tsKey: 'SYC.name',
			tsNs: 'country',
		},
		{
			cca2: 'CX',
			id: 'ctry_01GW2HHDKHV33E0R9ZQSE302T3',
			tsKey: 'CXR.name',
			tsNs: 'country',
		},
		{
			cca2: 'FM',
			id: 'ctry_01GW2HHDKHHXXT7NMR9TQ0TY97',
			tsKey: 'FSM.name',
			tsNs: 'country',
		},
		{
			cca2: 'BE',
			id: 'ctry_01GW2HHDKHCQVPDAC0H3PQV53N',
			tsKey: 'BEL.name',
			tsNs: 'country',
		},
		{
			cca2: 'TW',
			id: 'ctry_01GW2HHDKHMX2CYG3GWYA23W4B',
			tsKey: 'TWN.name',
			tsNs: 'country',
		},
		{
			cca2: 'KR',
			id: 'ctry_01GW2HHDKH6NG85CKMSESSPHQK',
			tsKey: 'KOR.name',
			tsNs: 'country',
		},
		{
			cca2: 'DK',
			id: 'ctry_01GW2HHDKH7Z155XNFE328RJK5',
			tsKey: 'DNK.name',
			tsNs: 'country',
		},
		{
			cca2: 'OM',
			id: 'ctry_01GW2HHDKH3SMD6TVK8MPGE6DD',
			tsKey: 'OMN.name',
			tsNs: 'country',
		},
		{
			cca2: 'CK',
			id: 'ctry_01GW2HHDK8FK98CXW90F5HFRJH',
			tsKey: 'COK.name',
			tsNs: 'country',
		},
		{
			cca2: 'NU',
			id: 'ctry_01GW2HHDK9B08AAMK0WGCVR313',
			tsKey: 'NIU.name',
			tsNs: 'country',
		},
		{
			cca2: 'SI',
			id: 'ctry_01GW2HHDK95AW3T41X8R552F6R',
			tsKey: 'SVN.name',
			tsNs: 'country',
		},
		{
			cca2: 'PG',
			id: 'ctry_01GW2HHDK9HZ6M9Q2PJEX8T6HA',
			tsKey: 'PNG.name',
			tsNs: 'country',
		},
		{
			cca2: 'GF',
			id: 'ctry_01GW2HHDKH5GV00V6MM2F7CZ3P',
			tsKey: 'GUF.name',
			tsNs: 'country',
		},
		{
			cca2: 'PN',
			id: 'ctry_01GW2HHDKJRNN53ENTSS4Z001K',
			tsKey: 'PCN.name',
			tsNs: 'country',
		},
		{
			cca2: 'SN',
			id: 'ctry_01GW2HHDKJ4620D1AB421E7JYX',
			tsKey: 'SEN.name',
			tsNs: 'country',
		},
		{
			cca2: 'PR',
			id: 'ctry_01GW2HHDK7PACTC9GJ2XBMVPKY',
			tsKey: 'PRI.name',
			tsNs: 'country',
		},
		{
			cca2: 'VI',
			id: 'ctry_01GW2HHDK9DG12Y7RQMVEE5XSQ',
			tsKey: 'VIR.name',
			tsNs: 'country',
		},
		{
			cca2: 'SG',
			id: 'ctry_01GW2HHDK6FGT7BES1NPX66JTQ',
			tsKey: 'SGP.name',
			tsNs: 'country',
		},
		{
			cca2: 'BA',
			id: 'ctry_01GW2HHDK6V0QGJ9GRNQCW6A29',
			tsKey: 'BIH.name',
			tsNs: 'country',
		},
		{
			cca2: 'MV',
			id: 'ctry_01GW2HHDK6FR8HMD3W523Q3WRA',
			tsKey: 'MDV.name',
			tsNs: 'country',
		},
		{
			cca2: 'LV',
			id: 'ctry_01GW2HHDK69KVF1HPHBRBTSSBE',
			tsKey: 'LVA.name',
			tsNs: 'country',
		},
		{
			cca2: 'GR',
			id: 'ctry_01GW2HHDK6GRHQQEYGGJX4CQ1Z',
			tsKey: 'GRC.name',
			tsNs: 'country',
		},
		{
			cca2: 'CC',
			id: 'ctry_01GW2HHDK66TC7PJG0EVPFMBFP',
			tsKey: 'CCK.name',
			tsNs: 'country',
		},
		{
			cca2: 'YT',
			id: 'ctry_01GW2HHDK6BG4CBH38VKSZ9M4X',
			tsKey: 'MYT.name',
			tsNs: 'country',
		},
		{
			cca2: 'JO',
			id: 'ctry_01GW2HHDK6Q6BB2C5DWKAYKVP9',
			tsKey: 'JOR.name',
			tsNs: 'country',
		},
		{
			cca2: 'TN',
			id: 'ctry_01GW2HHDKGG7JZ2RN968FJNWJ8',
			tsKey: 'TUN.name',
			tsNs: 'country',
		},
		{
			cca2: 'BI',
			id: 'ctry_01GW2HHDKGB5RY2JAQVVF4RC4X',
			tsKey: 'BDI.name',
			tsNs: 'country',
		},
		{
			cca2: 'CH',
			id: 'ctry_01GW2HHDKGFE1AY05PY62XEWPM',
			tsKey: 'CHE.name',
			tsNs: 'country',
		},
		{
			cca2: 'AX',
			id: 'ctry_01GW2HHDKGQRTDPFBTD9GJT3BN',
			tsKey: 'ALA.name',
			tsNs: 'country',
		},
		{
			cca2: 'BJ',
			id: 'ctry_01GW2HHDKGTGG62NESH7TDS364',
			tsKey: 'BEN.name',
			tsNs: 'country',
		},
		{
			cca2: 'KI',
			id: 'ctry_01GW2HHDKGR9X8QJBDSK84PAG1',
			tsKey: 'KIR.name',
			tsNs: 'country',
		},
		{
			cca2: 'SD',
			id: 'ctry_01GW2HHDKH7NVGT1JBPB5B9SP3',
			tsKey: 'SDN.name',
			tsNs: 'country',
		},
		{
			cca2: 'UZ',
			id: 'ctry_01GW2HHDKH6KGE8D69GPF7SSAJ',
			tsKey: 'UZB.name',
			tsNs: 'country',
		},
		{
			cca2: 'BF',
			id: 'ctry_01GW2HHDKHD6PPNGQWWGD59BQT',
			tsKey: 'BFA.name',
			tsNs: 'country',
		},
		{
			cca2: 'LK',
			id: 'ctry_01GW2HHDKHZNVZP299TK5QC9X6',
			tsKey: 'LKA.name',
			tsNs: 'country',
		},
		{
			cca2: 'NE',
			id: 'ctry_01GW2HHDKHMY5MATBT7VET2W95',
			tsKey: 'NER.name',
			tsNs: 'country',
		},
		{
			cca2: 'SR',
			id: 'ctry_01GW2HHDKHZP2AGK419VGS2YQ0',
			tsKey: 'SUR.name',
			tsNs: 'country',
		},
		{
			cca2: 'AO',
			id: 'ctry_01GW2HHDKH6H61ZD7Q4D1EVHP5',
			tsKey: 'AGO.name',
			tsNs: 'country',
		},
		{
			cca2: 'CI',
			id: 'ctry_01GW2HHDKHRGA9ME9MF56RDYYC',
			tsKey: 'CIV.name',
			tsNs: 'country',
		},
		{
			cca2: 'KY',
			id: 'ctry_01GW2HHDKHA0DCHV26S9FDT5P4',
			tsKey: 'CYM.name',
			tsNs: 'country',
		},
		{
			cca2: 'LS',
			id: 'ctry_01GW2HHDKH74J20AXR1GWGX6ZQ',
			tsKey: 'LSO.name',
			tsNs: 'country',
		},
		{
			cca2: 'MS',
			id: 'ctry_01GW2HHDKHCN2Q3JMYRQ7HJ5VH',
			tsKey: 'MSR.name',
			tsNs: 'country',
		},
		{
			cca2: 'MW',
			id: 'ctry_01GW2HHDKHRXXQZHPZYDV3SNVZ',
			tsKey: 'MWI.name',
			tsNs: 'country',
		},
		{
			cca2: 'BS',
			id: 'ctry_01GW2HHDKH7K0Z1YPRYG3CMEMW',
			tsKey: 'BHS.name',
			tsNs: 'country',
		},
		{
			cca2: 'GW',
			id: 'ctry_01GW2HHDKHXN8ZSHAGKGENMQ4N',
			tsKey: 'GNB.name',
			tsNs: 'country',
		},
		{
			cca2: 'BL',
			id: 'ctry_01GW2HHDKH0MMEJM9R74Z359R6',
			tsKey: 'BLM.name',
			tsNs: 'country',
		},
		{
			cca2: 'GU',
			id: 'ctry_01GW2HHDKGZ2XQ8Q9D8GX564MJ',
			tsKey: 'GUM.name',
			tsNs: 'country',
		},
		{
			cca2: 'US',
			id: 'ctry_01GW2HHDK9M26M80SG63T21SVH',
			tsKey: 'USA.name',
			tsNs: 'country',
		},
		{
			cca2: 'CA',
			id: 'ctry_01GW2HHDKAWXWYHAAESAA5HH94',
			tsKey: 'CAN.name',
			tsNs: 'country',
		},
		{
			cca2: 'MX',
			id: 'ctry_01GW2HHDKB9DG2T2YZM5MFFVX9',
			tsKey: 'MEX.name',
			tsNs: 'country',
		},
	],
	ethnicity: [
		{
			id: 'ueth_00000000008P0CEKTFHPSB5ZMH',
			tsKey: 'eth-black',
			tsNs: 'user',
			ethnicity: 'Black',
		},
		{
			id: 'ueth_0000000000VHKHZCYN8Y1XKKSM',
			tsKey: 'eth-middle-easternnorth-african',
			tsNs: 'user',
			ethnicity: 'Middle Eastern/North African',
		},
		{
			id: 'ueth_0000000000M2F0RHECPMF0MR6X',
			tsKey: 'eth-asian',
			tsNs: 'user',
			ethnicity: 'Asian',
		},
		{
			id: 'ueth_0000000000PNE879MSM1953PAJ',
			tsKey: 'eth-latinoaxhispanic',
			tsNs: 'user',
			ethnicity: 'Latino/a/x/Hispanic',
		},
		{
			id: 'ueth_00000000008WXJ64CV556WDFX8',
			tsKey: 'eth-south-asian',
			tsNs: 'user',
			ethnicity: 'South Asian',
		},
		{
			id: 'ueth_0000000000KEK72B3N4QHVTA3A',
			tsKey: 'eth-biracialmultiracial',
			tsNs: 'user',
			ethnicity: 'Biracial/Multiracial',
		},
		{
			id: 'ueth_00000000006F1H2JQ07NJTREXW',
			tsKey: 'eth-american-indiannative-americanindigenous-person',
			tsNs: 'user',
			ethnicity: 'American Indian/Native American/Indigenous Person',
		},
		{
			id: 'ueth_00000000000050AVJB64RKM26N',
			tsKey: 'eth-native-hawaiianpacific-islander',
			tsNs: 'user',
			ethnicity: 'Native Hawaiian/Pacific Islander',
		},
		{
			id: 'ueth_0000000000MGT66394R9VSBBBT',
			tsKey: 'eth-white',
			tsNs: 'user',
			ethnicity: 'White',
		},
		{
			id: 'ueth_0000000000E5KVESBAY6NPGJW3',
			tsKey: 'eth-other',
			tsNs: 'user',
			ethnicity: 'Other',
		},
		{
			id: 'ueth_0000000000408WMYJX00AG1QPW',
			tsKey: 'eth-prefer-not-to-say',
			tsNs: 'user',
			ethnicity: 'Prefer not to say',
		},
	],
	immigration: [
		{
			id: 'uimm_01GW2HHHS4V1GC918V546W60KD',
			tsKey: 'immigration-asylee',
			tsNs: 'user',
			status: 'Asylee (granted asylum)',
		},
		{
			id: 'uimm_01GW2HHHS4Y4GY5HY7HCSG8YK7',
			tsKey: 'immigration-asylum-seeker',
			tsNs: 'user',
			status: 'Asylum seeker',
		},
		{
			id: 'uimm_01GW2HHHS402DH862YGCY0PCMT',
			tsKey: 'immigration-dreamer',
			tsNs: 'user',
			status: 'Dreamer (DACA recipient)',
		},
		{
			id: 'uimm_01GW2HHHS4G6TA7FVKXBC3NT8M',
			tsKey: 'immigration-immigrant',
			tsNs: 'user',
			status: 'Immigrant',
		},
		{
			id: 'uimm_01GW2HHHS4DQRF2AJR7RTQ1WDJ',
			tsKey: 'immigration-refugee',
			tsNs: 'user',
			status: 'Refugee',
		},
	],
	sog: [
		{
			id: 'usog_01GW2HHHJ24AEGCKRWGJBM40VH',
			tsKey: 'identity-ally',
			tsNs: 'user',
			identifyAs: 'Ally',
		},
		{
			id: 'usog_01GW2HHHJ2SW75W5HN05XSYPBD',
			tsKey: 'identity-asexual',
			tsNs: 'user',
			identifyAs: 'Asexual',
		},
		{
			id: 'usog_01GW2HHHJ20BNN1QNFSKCFZJY0',
			tsKey: 'identity-bisexual',
			tsNs: 'user',
			identifyAs: 'Bisexual',
		},
		{
			id: 'usog_01GW2HHHJ2B12W0TQJK6C40QVC',
			tsKey: 'identity-gay',
			tsNs: 'user',
			identifyAs: 'Gay',
		},
		{
			id: 'usog_01GW2HHHJ21DDB2R0D19R7M7JH',
			tsKey: 'identity-intersex',
			tsNs: 'user',
			identifyAs: 'Intersex',
		},
		{
			id: 'usog_01GW2HHHJ2QDQXKF5NP5RS5Y39',
			tsKey: 'identity-lesbian',
			tsNs: 'user',
			identifyAs: 'Lesbian',
		},
		{
			id: 'usog_01GW2HHHJ23WPP795Y15Q870KV',
			tsKey: 'identity-man',
			tsNs: 'user',
			identifyAs: 'Man',
		},
		{
			id: 'usog_01GW2HHHJ2Z9CG508G0Y7DYPGE',
			tsKey: 'identity-nonbinary',
			tsNs: 'user',
			identifyAs: 'Nonbinary',
		},
		{
			id: 'usog_01GW2HHHJ2DHFBR3CMFMCYH0K5',
			tsKey: 'identity-pansexual',
			tsNs: 'user',
			identifyAs: 'Pansexual',
		},
		{
			id: 'usog_01GW2HHHJ2WQZ68B82GX495XF8',
			tsKey: 'identity-queer',
			tsNs: 'user',
			identifyAs: 'Queer',
		},
		{
			id: 'usog_01GW2HHHJ2HH62GFVMWJCSA4XT',
			tsKey: 'identity-questioning',
			tsNs: 'user',
			identifyAs: 'Questioning',
		},
		{
			id: 'usog_01GW2HHHJ37AW3SB0Y8BDGQF8N',
			tsKey: 'identity-straight',
			tsNs: 'user',
			identifyAs: 'Straight',
		},
		{
			id: 'usog_01GW2HHHJ3PQQ2XHK0AGDWCFJB',
			tsKey: 'identity-transgender',
			tsNs: 'user',
			identifyAs: 'Transgender',
		},
		{
			id: 'usog_01GW2HHHJ3N748VNX751AY4KPE',
			tsKey: 'identity-woman',
			tsNs: 'user',
			identifyAs: 'Woman',
		},
	],
}
