export const surveyOptions = {
	immigration: [
		{
			id: 'uimm_01GW2HHHS4V1GC918V546W60KD',
			status: 'Asylee (granted asylum)',
			tsKey: 'immigration-asylee',
			tsNs: 'user',
		},
		{
			id: 'uimm_01GW2HHHS4Y4GY5HY7HCSG8YK7',
			status: 'Asylum seeker',
			tsKey: 'immigration-asylum-seeker',
			tsNs: 'user',
		},
		{
			id: 'uimm_01GW2HHHS402DH862YGCY0PCMT',
			status: 'Dreamer (DACA recipient)',
			tsKey: 'immigration-dreamer',
			tsNs: 'user',
		},
		{
			id: 'uimm_01GW2HHHS4G6TA7FVKXBC3NT8M',
			status: 'Immigrant',
			tsKey: 'immigration-immigrant',
			tsNs: 'user',
		},
		{
			id: 'uimm_01GW2HHHS4DQRF2AJR7RTQ1WDJ',
			status: 'Refugee',
			tsKey: 'immigration-refugee',
			tsNs: 'user',
		},
	],
	sog: [
		{
			id: 'usog_01GW2HHHJ24AEGCKRWGJBM40VH',
			identifyAs: 'Ally',
			tsKey: 'identity-ally',
			tsNs: 'user',
		},
		{
			id: 'usog_01GW2HHHJ2SW75W5HN05XSYPBD',
			identifyAs: 'Asexual',
			tsKey: 'identity-asexual',
			tsNs: 'user',
		},
		{
			id: 'usog_01GW2HHHJ20BNN1QNFSKCFZJY0',
			identifyAs: 'Bisexual',
			tsKey: 'identity-bisexual',
			tsNs: 'user',
		},
		{
			id: 'usog_01GW2HHHJ2B12W0TQJK6C40QVC',
			identifyAs: 'Gay',
			tsKey: 'identity-gay',
			tsNs: 'user',
		},
		{
			id: 'usog_01GW2HHHJ21DDB2R0D19R7M7JH',
			identifyAs: 'Intersex',
			tsKey: 'identity-intersex',
			tsNs: 'user',
		},
		{
			id: 'usog_01GW2HHHJ2QDQXKF5NP5RS5Y39',
			identifyAs: 'Lesbian',
			tsKey: 'identity-lesbian',
			tsNs: 'user',
		},
		{
			id: 'usog_01GW2HHHJ23WPP795Y15Q870KV',
			identifyAs: 'Man',
			tsKey: 'identity-man',
			tsNs: 'user',
		},
		{
			id: 'usog_01GW2HHHJ2Z9CG508G0Y7DYPGE',
			identifyAs: 'Nonbinary',
			tsKey: 'identity-nonbinary',
			tsNs: 'user',
		},
		{
			id: 'usog_01GW2HHHJ2DHFBR3CMFMCYH0K5',
			identifyAs: 'Pansexual',
			tsKey: 'identity-pansexual',
			tsNs: 'user',
		},
		{
			id: 'usog_01GW2HHHJ2WQZ68B82GX495XF8',
			identifyAs: 'Queer',
			tsKey: 'identity-queer',
			tsNs: 'user',
		},
		{
			id: 'usog_01GW2HHHJ2HH62GFVMWJCSA4XT',
			identifyAs: 'Questioning',
			tsKey: 'identity-questioning',
			tsNs: 'user',
		},
		{
			id: 'usog_01GW2HHHJ37AW3SB0Y8BDGQF8N',
			identifyAs: 'Straight',
			tsKey: 'identity-straight',
			tsNs: 'user',
		},
		{
			id: 'usog_01GW2HHHJ3PQQ2XHK0AGDWCFJB',
			identifyAs: 'Transgender',
			tsKey: 'identity-transgender',
			tsNs: 'user',
		},
		{
			id: 'usog_01GW2HHHJ3N748VNX751AY4KPE',
			identifyAs: 'Woman',
			tsKey: 'identity-woman',
			tsNs: 'user',
		},
	],
	ethnicity: [
		{
			id: 'ueth_00000000008P0CEKTFHPSB5ZMH',
			ethnicity: 'Black',
			tsKey: 'eth-black',
			tsNs: 'user',
		},
		{
			id: 'ueth_0000000000VHKHZCYN8Y1XKKSM',
			ethnicity: 'Middle Eastern/North African',
			tsKey: 'eth-middle-easternnorth-african',
			tsNs: 'user',
		},
		{
			id: 'ueth_0000000000M2F0RHECPMF0MR6X',
			ethnicity: 'Asian',
			tsKey: 'eth-asian',
			tsNs: 'user',
		},
		{
			id: 'ueth_0000000000PNE879MSM1953PAJ',
			ethnicity: 'Latino/a/x/Hispanic',
			tsKey: 'eth-latinoaxhispanic',
			tsNs: 'user',
		},
		{
			id: 'ueth_00000000008WXJ64CV556WDFX8',
			ethnicity: 'South Asian',
			tsKey: 'eth-south-asian',
			tsNs: 'user',
		},
		{
			id: 'ueth_0000000000KEK72B3N4QHVTA3A',
			ethnicity: 'Biracial/Multiracial',
			tsKey: 'eth-biracialmultiracial',
			tsNs: 'user',
		},
		{
			id: 'ueth_00000000006F1H2JQ07NJTREXW',
			ethnicity: 'American Indian/Native American/Indigenous Person',
			tsKey: 'eth-american-indiannative-americanindigenous-person',
			tsNs: 'user',
		},
		{
			id: 'ueth_00000000000050AVJB64RKM26N',
			ethnicity: 'Native Hawaiian/Pacific Islander',
			tsKey: 'eth-native-hawaiianpacific-islander',
			tsNs: 'user',
		},
		{
			id: 'ueth_0000000000MGT66394R9VSBBBT',
			ethnicity: 'White',
			tsKey: 'eth-white',
			tsNs: 'user',
		},
		{
			id: 'ueth_0000000000E5KVESBAY6NPGJW3',
			ethnicity: 'Other',
			tsKey: 'eth-other',
			tsNs: 'user',
		},
		{
			id: 'ueth_0000000000408WMYJX00AG1QPW',
			ethnicity: 'Prefer not to say',
			tsKey: 'eth-prefer-not-to-say',
			tsNs: 'user',
		},
	],
	community: [
		{
			id: 'string',
			community: 'string',
			tsKey: 'string',
			tsNs: 'user',
		},
	],
}
