import { TRPCError } from '@trpc/server'

export const PRISMA_ERROR_CODES: Record<string, TRPCError['code']> = {
	P1000: 'FORBIDDEN', //Authentication failed against database server.'
	P1001: 'INTERNAL_SERVER_ERROR', //"Can't reach database server.",
	P1002: 'INTERNAL_SERVER_ERROR', //'The database server was reached but timed out.',
	P1003: 'NOT_FOUND', //'Database does not exist at file_path.',
	P1008: 'TIMEOUT', //'Operations timed out.',
	P1009: 'CONFLICT', //'Database already exists on the database server.',
	P1010: 'UNAUTHORIZED', //'User was denied access on the database.',
	P1011: 'INTERNAL_SERVER_ERROR', //'Error opening a TLS connection.',
	P1012: 'BAD_REQUEST', //'Argumentis missing.',
	P1013: 'INTERNAL_SERVER_ERROR', //'The provided database string is invalid.',
	P1014: 'BAD_REQUEST', //'The underlying {kind} for model does not exist.',
	P1015: 'INTERNAL_SERVER_ERROR', //'Your Prisma schema is using features that are not supported for the version of the database.',
	P1016: 'BAD_REQUEST', //'Your raw query had an incorrect number of parameters.',
	P1017: 'CLIENT_CLOSED_REQUEST', //'Server has closed the connection.',
	P2000: 'PAYLOAD_TOO_LARGE', //"The provided value for the column is too long for the column's type.",
	P2001: 'NOT_FOUND', //'The record searched for in the where condition does not exist.',
	P2002: 'BAD_REQUEST', //'Unique constraint failed.',
	P2003: 'BAD_REQUEST', //'Foreign key constraint failed on the field',
	P2004: 'BAD_REQUEST', //'A constraint failed on the database.',
	P2005: 'BAD_REQUEST', //"The value stored in the database for the field is invalid for the field's type.",
	P2006: 'BAD_REQUEST', //'The provided value for field is not valid.',
	P2007: 'BAD_REQUEST', //'Data validation error.',
	P2008: 'BAD_REQUEST', //'Failed to parse the query.',
	P2009: 'BAD_REQUEST', //'Failed to validate the query.',
	P2010: 'BAD_REQUEST', //'Raw query failed.',
	P2011: 'BAD_REQUEST', //'Null constraint violation on the constraint.',
	P2012: 'BAD_REQUEST', //'Missing a required value.',
	P2013: 'BAD_REQUEST', //'Missing the required argument for field.',
	P2014: 'BAD_REQUEST', //'The change you are trying to make would violate the required relation between the models.',
	P2015: 'NOT_FOUND', //'A related record could not be found.',
	P2016: 'BAD_REQUEST', //'Query interpretation error',
	P2017: 'CONFLICT', //'The records for relation between the parent and child models are not connected.',
	P2018: 'NOT_FOUND', //'The required connected records were not found.',
	P2019: 'BAD_REQUEST', //'Input error.',
	P2020: 'BAD_REQUEST', //'Value out of range for the type.',
	P2021: 'NOT_FOUND', //'The table does not exist in the current database.',
	P2022: 'NOT_FOUND', //'The column does not exist in the current database.',
	P2023: 'BAD_REQUEST', //'Inconsistent column data',
	P2024: 'TIMEOUT', //'Timed out fetching a new connection from the connection pool.',
	P2025: 'NOT_FOUND', //'An operation failed because it depends on one or more records that were required but not found.',
	P2026: 'INTERNAL_SERVER_ERROR', //"The current database provider doesn't support a feature that the query used.",
	P2027: 'INTERNAL_SERVER_ERROR', //'Multiple errors occurred on the database during query execution.',
	P2030: 'INTERNAL_SERVER_ERROR', //'Cannot find a fulltext index to use for the search.',
	P2033: 'BAD_REQUEST', //'A number used in the query does not fit into a 64 bit signed integer.',
	P5000: 'BAD_REQUEST',
	P5001: 'INTERNAL_SERVER_ERROR',
	P5002: 'INTERNAL_SERVER_ERROR',
	P5003: 'NOT_FOUND',
	P5004: 'INTERNAL_SERVER_ERROR',
	P5005: 'INTERNAL_SERVER_ERROR',
	P5006: 'INTERNAL_SERVER_ERROR',
	P5007: 'FORBIDDEN',
	P5008: 'TOO_MANY_REQUESTS',
	P5009: 'TIMEOUT',
	P5010: 'INTERNAL_SERVER_ERROR',
	P5011: 'BAD_REQUEST',
	P5012: 'INTERNAL_SERVER_ERROR',
	P5013: 'TIMEOUT',
	P5014: 'INTERNAL_SERVER_ERROR',
	P5015: 'CONFLICT',
} as const
