import { z } from 'zod'

// Generated by https://quicktype.io

export interface ExistingOrgs {
	_id: ID
	is_published: boolean
	description: string
	name: string
	properties?: { [key: string]: string }
	slug: string
	verified_at?: EdAt
	website?: string
	emails: Email[]
	locations: Location[]
	phones: Phone[]
	schedules: Schedule[]
	services: Service[]
	source?: Source
	created_at: EdAt
	__v: number
	alert_message?: string
	updated_at: EdAt
	description_ES?: string
	website_ES?: string
	alert_message_ES?: string
	slug_ES?: string
	name_ES?: string
	owners?: Owner[]
	venue_id?: string
	photos?: Photo[]
	social_media?: SocialMedia[]
	notes_log?: NotesLog[]
	is_deleted: boolean
	adminEmails?: any[]
}

export interface ID {
	$oid: string
}

export interface EdAt {
	$date: string
}

export interface Email {
	_id: ID
	email: string
	first_name?: null | string
	is_primary?: boolean
	last_name?: null | string
	show_on_organization?: boolean
	title?: null | string
	title_ES?: string
}

export interface Location {
	geolocation: Geolocation
	_id: ID
	address?: string
	city?: string
	is_primary: boolean
	lat?: string
	long?: string
	name?: string
	show_on_organization: boolean
	state?: string
	unit?: string
	zip_code?: string
	country_ES?: CountryES
	state_ES?: string
	name_ES?: string
	country?: string
	city_ES?: string
}

export enum CountryES {
	CA = 'CA',
	Canada = 'Canada',
	CountryESCanada = ' Canada',
	CountryESEEUU = 'EE.UU',
	CountryESEstadosUnidos = 'Estados Unidos',
	CountryESMexico = 'Mexico ',
	CountryESMéxico = 'México ',
	CountryESUnitedStates = 'United States ',
	Cánada = 'Cánada',
	EEUU = 'E.E.U.U.',
	EeUu = 'EE.UU.',
	Eeuu = 'EEUU',
	Empty = '',
	EstadosUnidos = 'Estados Unidos ',
	LosEEUU = 'Los EEUU',
	LosEstadosUnidos = 'Los Estados Unidos',
	LossEEUU = 'Loss EEUU',
	Mexico = 'Mexico',
	México = 'México',
	PurpleEEUU = 'EE UU',
	PurpleEstadosUnidos = 'Estados unidos',
	UnitedStates = 'United States',
	Us = 'US',
	Usa = 'USA',
}

export interface Geolocation {
	coordinates: Coordinate[]
	type: Type
}

export interface Coordinate {
	$numberDecimal: string
}

export enum Type {
	Point = 'Point',
}

export interface NotesLog {
	_id: ID
	note: string
	created_at: EdAt
}

export interface Owner {
	_id: ID
	email: string
	isApproved: boolean
	userId: string
}

export interface Phone {
	_id: ID
	digits?: null | string
	is_primary?: boolean
	phone_type: string
	show_on_organization?: boolean
	phone_type_ES?: string
}

export interface Photo {
	src: string
	suffix: string
	foursquare_vendor_id: string
	width: number
	height: number
}

export interface Schedule {
	_id: ID
	monday_start?: string
	monday_end?: string
	tuesday_start?: string
	tuesday_end?: string
	wednesday_start?: string
	wednesday_end?: string
	thursday_start?: string
	thursday_end?: string
	friday_start?: string
	friday_end?: string
	saturday_start?: string
	saturday_end?: string
	sunday_start?: string
	sunday_end?: string
	name?: string
	timezone?: Timezone
	note?: string
}

export enum Timezone {
	AST = 'AST',
	Akst = 'AKST',
	Cdt = 'CDT',
	Cst = 'CST',
	Edt = 'EDT',
	Empty = '',
	Est = 'EST',
	Hst = 'HST',
	Mdt = 'MDT',
	Mst = 'MST',
	Pdt = 'PDT',
	Pst = 'PST',
}

export interface Service {
	is_published: boolean
	is_deleted: boolean
	_id: ID
	tags?: Tags
	created_at: EdAt
	access_instructions: AccessInstruction[]
	description?: string
	email_id?: string
	location_id?: string
	name: string
	phone_id?: string
	properties?: { [key: string]: any[] | string }
	schedule_id?: string
	slug: string
	updated_at: EdAt
	name_ES?: string
	slug_ES?: string
	description_ES?: string
	notes_log?: NotesLog[]
}

export interface AccessInstruction {
	_id: ID
	access_value?: string
	access_type?: AccessType
	instructions?: string
	access_value_ES?: string
	instructions_ES?: string
}

export enum AccessType {
	Email = 'email',
	Empty = '',
	File = 'file',
	Link = 'link',
	Location = 'location',
	Other = 'other',
	Phone = 'phone',
}

export interface Tags {
	united_states?: UnitedStates
	canada?: Canada
	mexico?: Mexico
}

export interface Canada {
	'Mental Health'?: CanadaMentalHealth
	'Hygiene and Clothing'?: CanadaHygieneAndClothing
	Food?: string
	Legal?: CanadaLegal
	'Community Support'?: CanadaCommunitySupport
	Medical?: Medical
	'Education and Employment'?: CanadaEducationAndEmployment
	Housing?: CanadaHousing
	'Translation and Interpretation'?: string
	Transportation?: CanadaTransportation
	'Computers and Internet'?: string
	'Sports and Entertainment'?: string
}

export interface CanadaCommunitySupport {
	'LGBTQ centres'?: string
	'Cultural centres'?: string
	'Reception services'?: string
	'Spiritual Support'?: string
}

export interface CanadaEducationAndEmployment {
	Scholarships?: string
	'Career counseling'?: string
	'Educational support for LGBTQ youth'?: string
	'Language classes'?: string
	Libraries?: string
}

export interface CanadaHousing {
	'Housing information and referrals'?: string
	'Drop-in centres for LGBTQ youth'?: string
	'Emergency housing'?: string
	'Short-term housing'?: string
}

export interface CanadaHygieneAndClothing {
	'Gender-affirming items'?: string
	Clothes?: string
	Hygiene?: string
	'Gender-neutral washrooms'?: string
}

export interface CanadaLegal {
	'Immigration detention'?: string
	'Refugee claim'?: string
	'Deportation or removal'?: string
	'Legal hotlines'?: string
	'Crime and discrimination'?: string
	'Name and gender change'?: string
}

export interface Medical {
	'HIV and sexual health'?: string
	'Medical clinics'?: string
	'Trans health'?: string
	'Dental care'?: string
	'OBGYN services'?: string
	'Trans Health - Hormone Therapy'?: string
	'Trans Health - Hormone and Surgery Letters'?: string
}

export interface CanadaMentalHealth {
	Hotlines?: string
	'Trans support groups'?: string
	'Support groups'?: string
	'Private therapy and counseling'?: string
	'Substance use'?: string
	'Psychological evaluations for asylum claim'?: string
}

export interface CanadaTransportation {
	'Transportation assistance'?: string
	'Transit passes and discounts'?: string
}

export interface Mexico {
	'Community Support'?: MexicoCommunitySupport
	'Sports and Entertainment'?: string
	Medical?: { [key: string]: string }
	'Mental Health'?: CanadaMentalHealth
	'Education and Employment'?: CanadaEducationAndEmployment
	Legal?: MexicoLegal
	Food?: string
	'Hygiene and Clothing'?: MexicoHygieneAndClothing
	'Translation and Interpretation'?: string
	Housing?: MexicoHousing
	'Computers and Internet'?: string
	'Abortion Care'?: MexicoAbortionCare
	Transportation?: MexicoTransportation
}

export interface MexicoAbortionCare {
	'Abortion Providers': string
}

export interface MexicoCommunitySupport {
	'LGBTQ centers'?: string
	'Cultural centers'?: string
	'Spiritual Support'?: string
	Sponsors?: string
}

export interface MexicoHousing {
	'Housing information and referrals'?: string
	'Emergency housing'?: string
	'Drop-in centers for LGBTQ youth'?: string
}

export interface MexicoHygieneAndClothing {
	Hygiene?: string
	Clothes?: string
}

export interface MexicoLegal {
	'Name and gender change'?: string
	'Crime and discrimination'?: string
	'Asylum application in the US from Mexico'?: string
	'Asylum application in Mexico'?: string
	'Deportation or removal'?: string
	'Immigration detention'?: string
}

export interface MexicoTransportation {
	'Transportation assistance': string
}

export interface UnitedStates {
	Housing?: UnitedStatesHousing
	'Education and Employment'?: UnitedStatesEducationAndEmployment
	'Hygiene and Clothing'?: UnitedStatesHygieneAndClothing
	Medical?: { [key: string]: string }
	'Mental Health'?: UnitedStatesMentalHealth
	Food?: string
	'Community Support'?: MexicoCommunitySupport
	'Computers and Internet'?: string
	'Sports and Entertainment'?: string
	Legal?: { [key: string]: string }
	Mail?: string
	'Translation and Interpretation'?: string
	Transportation?: CanadaTransportation
	'Abortion Care'?: UnitedStatesAbortionCare
}

export interface UnitedStatesAbortionCare {
	'Abortion Providers'?: string
	'Financial Assistance'?: string
	'Mental Health Support'?: string
	'Mail Order Services'?: string
	'Travel Assistance'?: string
	'Lodging Assistance'?: string
}

export interface UnitedStatesEducationAndEmployment {
	'Career counseling'?: string
	'Career counselling'?: string
	'Leadership training and professional development'?: string
	Libraries?: string
	'Educational support for LGBTQ youth'?: string
	'English classes'?: string
	Scholarships?: string
}

export interface UnitedStatesHousing {
	'Emergency housing'?: string
	'Housing information and referrals'?: string
	'Trans housing'?: string
	'Drop-in centers for LGBTQ youth'?: string
	'Short-term housing'?: string
}

export interface UnitedStatesHygieneAndClothing {
	Hygiene?: string
	Clothes?: string
	'Gender-neutral bathrooms'?: string
	'Gender-affirming items'?: string
	'Gender-affirming items '?: string
	Hygienee?: string
	'Haircuts and stylists'?: string
}

export interface UnitedStatesMentalHealth {
	Hotlines?: string
	'Support groups'?: string
	'Substance use'?: string
	'Private therapy and counseling'?: string
	'Trans support groups'?: string
	'BIPOC support groups'?: string
	'Support for caregivers of trans youth'?: string
	'Psychological evaluations for asylum claim'?: string
	'Support for conversion therapy survivors'?: string
}

export interface SocialMedia {
	_id: ID
	name?: Name
	url: string
}

export enum Name {
	Facebook = 'facebook',
	Instagram = 'instagram',
	Linkedin = 'linkedin',
	Twitter = 'twitter',
	Youtube = 'youtube',
}

export enum Source {
	OneDegree = 'OneDegree',
}

export const idSchema = z.object({
	$oid: z.string(),
})

export const edAtSchema = z.object({
	$date: z.string(),
})

export const emailSchema = z.object({
	_id: idSchema,
	email: z.string(),
	first_name: z.string().optional().nullable(),
	is_primary: z.boolean().optional(),
	last_name: z.string().optional().nullable(),
	show_on_organization: z.boolean().optional(),
	title: z.string().optional().nullable(),
	title_ES: z.string().optional(),
})

export const countryESSchema = z.nativeEnum(CountryES)

export const coordinateSchema = z.object({
	$numberDecimal: z.string(),
})

export const typeSchema = z.nativeEnum(Type)

export const notesLogSchema = z.object({
	_id: idSchema,
	note: z.string(),
	created_at: edAtSchema,
})

export const ownerSchema = z.object({
	_id: idSchema,
	email: z.string(),
	isApproved: z.boolean(),
	userId: z.string(),
})

export const phoneSchema = z.object({
	_id: idSchema,
	digits: z.string().optional().nullable(),
	is_primary: z.boolean().optional(),
	phone_type: z.string(),
	show_on_organization: z.boolean().optional(),
	phone_type_ES: z.string().optional(),
})

export const photoSchema = z.object({
	src: z.string(),
	suffix: z.string(),
	foursquare_vendor_id: z.string(),
	width: z.number(),
	height: z.number(),
})

export const timezoneSchema = z.nativeEnum(Timezone)

export const accessTypeSchema = z.nativeEnum(AccessType)

export const canadaCommunitySupportSchema = z.object({
	'LGBTQ centres': z.string().optional(),
	'Cultural centres': z.string().optional(),
	'Reception services': z.string().optional(),
	'Spiritual Support': z.string().optional(),
})

export const canadaEducationAndEmploymentSchema = z.object({
	Scholarships: z.string().optional(),
	'Career counseling': z.string().optional(),
	'Educational support for LGBTQ youth': z.string().optional(),
	'Language classes': z.string().optional(),
	Libraries: z.string().optional(),
})

export const canadaHousingSchema = z.object({
	'Housing information and referrals': z.string().optional(),
	'Drop-in centres for LGBTQ youth': z.string().optional(),
	'Emergency housing': z.string().optional(),
	'Short-term housing': z.string().optional(),
})

export const canadaHygieneAndClothingSchema = z.object({
	'Gender-affirming items': z.string().optional(),
	Clothes: z.string().optional(),
	Hygiene: z.string().optional(),
	'Gender-neutral washrooms': z.string().optional(),
})

export const canadaLegalSchema = z.object({
	'Immigration detention': z.string().optional(),
	'Refugee claim': z.string().optional(),
	'Deportation or removal': z.string().optional(),
	'Legal hotlines': z.string().optional(),
	'Crime and discrimination': z.string().optional(),
	'Name and gender change': z.string().optional(),
})

export const medicalSchema = z.object({
	'HIV and sexual health': z.string().optional(),
	'Medical clinics': z.string().optional(),
	'Trans health': z.string().optional(),
	'Dental care': z.string().optional(),
	'OBGYN services': z.string().optional(),
	'Trans Health - Hormone Therapy': z.string().optional(),
	'Trans Health - Hormone and Surgery Letters': z.string().optional(),
})

export const canadaMentalHealthSchema = z.object({
	Hotlines: z.string().optional(),
	'Trans support groups': z.string().optional(),
	'Support groups': z.string().optional(),
	'Private therapy and counseling': z.string().optional(),
	'Substance use': z.string().optional(),
	'Psychological evaluations for asylum claim': z.string().optional(),
})

export const canadaTransportationSchema = z.object({
	'Transportation assistance': z.string().optional(),
	'Transit passes and discounts': z.string().optional(),
})

export const mexicoAbortionCareSchema = z.object({
	'Abortion Providers': z.string(),
})

export const mexicoCommunitySupportSchema = z.object({
	'LGBTQ centers': z.string().optional(),
	'Cultural centers': z.string().optional(),
	'Spiritual Support': z.string().optional(),
	Sponsors: z.string().optional(),
})

export const mexicoHousingSchema = z.object({
	'Housing information and referrals': z.string().optional(),
	'Emergency housing': z.string().optional(),
	'Drop-in centers for LGBTQ youth': z.string().optional(),
})

export const mexicoHygieneAndClothingSchema = z.object({
	Hygiene: z.string().optional(),
	Clothes: z.string().optional(),
})

export const mexicoLegalSchema = z.object({
	'Name and gender change': z.string().optional(),
	'Crime and discrimination': z.string().optional(),
	'Asylum application in the US from Mexico': z.string().optional(),
	'Asylum application in Mexico': z.string().optional(),
	'Deportation or removal': z.string().optional(),
	'Immigration detention': z.string().optional(),
})

export const mexicoTransportationSchema = z.object({
	'Transportation assistance': z.string(),
})

export const unitedStatesAbortionCareSchema = z.object({
	'Abortion Providers': z.string().optional(),
	'Financial Assistance': z.string().optional(),
	'Mental Health Support': z.string().optional(),
	'Mail Order Services': z.string().optional(),
	'Travel Assistance': z.string().optional(),
	'Lodging Assistance': z.string().optional(),
})

export const unitedStatesEducationAndEmploymentSchema = z.object({
	'Career counseling': z.string().optional(),
	'Career counselling': z.string().optional(),
	'Leadership training and professional development': z.string().optional(),
	Libraries: z.string().optional(),
	'Educational support for LGBTQ youth': z.string().optional(),
	'English classes': z.string().optional(),
	Scholarships: z.string().optional(),
})

export const unitedStatesHousingSchema = z.object({
	'Emergency housing': z.string().optional(),
	'Housing information and referrals': z.string().optional(),
	'Trans housing': z.string().optional(),
	'Drop-in centers for LGBTQ youth': z.string().optional(),
	'Short-term housing': z.string().optional(),
})

export const unitedStatesHygieneAndClothingSchema = z.object({
	Hygiene: z.string().optional(),
	Clothes: z.string().optional(),
	'Gender-neutral bathrooms': z.string().optional(),
	'Gender-affirming items': z.string().optional(),
	'Gender-affirming items ': z.string().optional(),
	Hygienee: z.string().optional(),
	'Haircuts and stylists': z.string().optional(),
})

export const unitedStatesMentalHealthSchema = z.object({
	Hotlines: z.string().optional(),
	'Support groups': z.string().optional(),
	'Substance use': z.string().optional(),
	'Private therapy and counseling': z.string().optional(),
	'Trans support groups': z.string().optional(),
	'BIPOC support groups': z.string().optional(),
	'Support for caregivers of trans youth': z.string().optional(),
	'Psychological evaluations for asylum claim': z.string().optional(),
	'Support for conversion therapy survivors': z.string().optional(),
})

export const nameSchema = z.nativeEnum(Name)

export const sourceSchema = z.nativeEnum(Source)

export const geolocationSchema = z.object({
	coordinates: z.array(coordinateSchema),
	type: typeSchema,
})

export const scheduleSchema = z.object({
	_id: idSchema,
	monday_start: z.string().optional(),
	monday_end: z.string().optional(),
	tuesday_start: z.string().optional(),
	tuesday_end: z.string().optional(),
	wednesday_start: z.string().optional(),
	wednesday_end: z.string().optional(),
	thursday_start: z.string().optional(),
	thursday_end: z.string().optional(),
	friday_start: z.string().optional(),
	friday_end: z.string().optional(),
	saturday_start: z.string().optional(),
	saturday_end: z.string().optional(),
	sunday_start: z.string().optional(),
	sunday_end: z.string().optional(),
	name: z.string().optional(),
	timezone: timezoneSchema.optional(),
	note: z.string().optional(),
})

export const accessInstructionSchema = z.object({
	_id: idSchema,
	access_value: z.string().optional(),
	access_type: accessTypeSchema.optional(),
	instructions: z.string().optional(),
	access_value_ES: z.string().optional(),
	instructions_ES: z.string().optional(),
})

export const canadaSchema = z.object({
	'Mental Health': canadaMentalHealthSchema.optional(),
	'Hygiene and Clothing': canadaHygieneAndClothingSchema.optional(),
	Food: z.string().optional(),
	Legal: canadaLegalSchema.optional(),
	'Community Support': canadaCommunitySupportSchema.optional(),
	Medical: medicalSchema.optional(),
	'Education and Employment': canadaEducationAndEmploymentSchema.optional(),
	Housing: canadaHousingSchema.optional(),
	'Translation and Interpretation': z.string().optional(),
	Transportation: canadaTransportationSchema.optional(),
	'Computers and Internet': z.string().optional(),
	'Sports and Entertainment': z.string().optional(),
})

export const mexicoSchema = z.object({
	'Community Support': mexicoCommunitySupportSchema.optional(),
	'Sports and Entertainment': z.string().optional(),
	Medical: z.record(z.string()).optional(),
	'Mental Health': canadaMentalHealthSchema.optional(),
	'Education and Employment': canadaEducationAndEmploymentSchema.optional(),
	Legal: mexicoLegalSchema.optional(),
	Food: z.string().optional(),
	'Hygiene and Clothing': mexicoHygieneAndClothingSchema.optional(),
	'Translation and Interpretation': z.string().optional(),
	Housing: mexicoHousingSchema.optional(),
	'Computers and Internet': z.string().optional(),
	'Abortion Care': mexicoAbortionCareSchema.optional(),
	Transportation: mexicoTransportationSchema.optional(),
})

export const unitedStatesSchema = z.object({
	Housing: unitedStatesHousingSchema.optional(),
	'Education and Employment': unitedStatesEducationAndEmploymentSchema.optional(),
	'Hygiene and Clothing': unitedStatesHygieneAndClothingSchema.optional(),
	Medical: z.record(z.string()).optional(),
	'Mental Health': unitedStatesMentalHealthSchema.optional(),
	Food: z.string().optional(),
	'Community Support': mexicoCommunitySupportSchema.optional(),
	'Computers and Internet': z.string().optional(),
	'Sports and Entertainment': z.string().optional(),
	Legal: z.record(z.string()).optional(),
	Mail: z.string().optional(),
	'Translation and Interpretation': z.string().optional(),
	Transportation: canadaTransportationSchema.optional(),
	'Abortion Care': unitedStatesAbortionCareSchema.optional(),
})

export const socialMediaSchema = z.object({
	_id: idSchema,
	name: nameSchema.optional(),
	url: z.string(),
})

export const locationSchema = z.object({
	geolocation: geolocationSchema,
	_id: idSchema,
	address: z.string().optional(),
	city: z.string().optional(),
	is_primary: z.boolean(),
	lat: z.string().optional(),
	long: z.string().optional(),
	name: z.string().optional(),
	show_on_organization: z.boolean(),
	state: z.string().optional(),
	unit: z.string().optional(),
	zip_code: z.string().optional(),
	country_ES: countryESSchema.optional(),
	state_ES: z.string().optional(),
	name_ES: z.string().optional(),
	country: z.string().optional(),
	city_ES: z.string().optional(),
})

export const tagsSchema = z.object({
	united_states: unitedStatesSchema.optional(),
	canada: canadaSchema.optional(),
	mexico: mexicoSchema.optional(),
})

export const serviceSchema = z.object({
	is_published: z.boolean(),
	is_deleted: z.boolean(),
	_id: idSchema,
	tags: tagsSchema.optional(),
	created_at: edAtSchema,
	access_instructions: z.array(accessInstructionSchema),
	description: z.string().optional(),
	email_id: z.string().optional(),
	location_id: z.string().optional(),
	name: z.string(),
	phone_id: z.string().optional(),
	properties: z.record(z.union([z.array(z.any()), z.string()])).optional(),
	schedule_id: z.string().optional(),
	slug: z.string(),
	updated_at: edAtSchema,
	name_ES: z.string().optional(),
	slug_ES: z.string().optional(),
	description_ES: z.string().optional(),
	notes_log: z.array(notesLogSchema).optional(),
})

export const existingOrgsSchema = z.object({
	_id: idSchema,
	is_published: z.boolean(),
	description: z.string(),
	name: z.string(),
	properties: z.record(z.string()).optional(),
	slug: z.string(),
	verified_at: edAtSchema.optional(),
	website: z.string().optional(),
	emails: z.array(emailSchema),
	locations: z.array(locationSchema),
	phones: z.array(phoneSchema),
	schedules: z.array(scheduleSchema),
	services: z.array(serviceSchema),
	source: sourceSchema.optional(),
	created_at: edAtSchema,
	__v: z.number(),
	alert_message: z.string().optional(),
	updated_at: edAtSchema,
	description_ES: z.string().optional(),
	website_ES: z.string().optional(),
	alert_message_ES: z.string().optional(),
	slug_ES: z.string().optional(),
	name_ES: z.string().optional(),
	owners: z.array(ownerSchema).optional(),
	venue_id: z.string().optional(),
	photos: z.array(photoSchema).optional(),
	social_media: z.array(socialMediaSchema).optional(),
	notes_log: z.array(notesLogSchema).optional(),
	is_deleted: z.boolean(),
	adminEmails: z.array(z.any()).optional(),
})
