import axios from 'axios'
import { countries as countryExtra } from 'countries-languages'
import * as langs from 'langs'

const targetLangs = ['es', 'fr', 'ru', 'ar']

const countryData = async () => {
	const { data: countries } = await axios.get<Array<Country>>(
		'https://restcountries.com/v3.1/all?fields=name,cca3'
	)
	return { countries }
}

export const generateCountryTranslations = async () => {
	const { countries } = await countryData()

	for (const target of targetLangs) {
		const iso = langs.where('1', target)?.[2]
		if (!iso) continue
		const data = countries.map((country) => ({
			[country.cca3]: {
				name: country.translations[iso] ?? '',
			},
		}))
	}
}

// Generated by https://quicktype.io

interface Country {
	cca3: string
	capital: string[]
	altSpellings: string[]
	translations: { [key: string]: Translation }
}

interface Translation {
	official: string
	common: string
}
