/* eslint-disable node/no-process-env */

/**
 * Packages/db/lib/syncCrowdinContext.ts
 *
 * Standalone, additive script. Does not modify any existing Crowdin API function or mutation handler.
 *
 * Lives in packages/db (not packages/crowdin) because it needs both Prisma and the Crowdin API client, and
 * packages/db already depends on @weareinreach/crowdin - the reverse dependency would create a cycle.
 *
 * Purpose: Populate the Crowdin `context` field for org-data strings with a direct link to the corresponding
 * organization (and, for location-scoped strings, the specific location) in the live app - e.g.
 * https://app.inreach.org/org/<slug> or https://app.inreach.org/org/<slug>/<oloc_id> - replacing Crowdin's
 * auto-generated identifier-breadcrumb fallback ("orgn_xxx -> osvc_xxx -> name").
 *
 * Safe to re-run: strings that already have a real (non-breadcrumb) context are skipped by default.
 *
 * Before writing anything for real, every changed string's PREVIOUS context is backed up to a timestamped
 * JSON file under packages/db/crowdin-backups/ - use --revert <path> to restore from one if needed.
 *
 * Usage (local): pnpm --filter @weareinreach/db crowdin:sync-context pnpm --filter @weareinreach/db
 * crowdin:sync-context -- --dry-run pnpm --filter @weareinreach/db crowdin:sync-context -- --force (overwrite
 * even non-breadcrumb context) pnpm --filter @weareinreach/db crowdin:sync-context -- --dry-run
 * --sample-skipped (print a sample of strings being skipped because they already look like they have real
 * context - useful for sanity- checking that isAutoGeneratedContext isn't over-matching) pnpm --filter
 * @weareinreach/db crowdin:sync-context -- --revert ./crowdin-backups/<file>.json pnpm --filter
 * @weareinreach/db crowdin:sync-context -- --revert ./crowdin-backups/<file>.json --dry-run pnpm --filter
 * @weareinreach/db crowdin:sync-context -- --limit 5 (only apply the first N pending updates - use this for a
 * small live smoke test before trusting a full run)
 *
 * Writes go through sourceStringsApi.stringBatchOperations() (one HTTP call covering many strings) rather
 * than editString() (one HTTP call per string) - a prior version of this script used editString() in a loop
 * and, against the full ~69k-string production backlog, took several seconds per string even though a single
 * isolated call to the same endpoint was well under a second - consistent with Crowdin throttling sustained
 * per-string write volume from one token, not a network or client-side problem. Batching cuts the number of
 * HTTP round-trips by ~BATCH_SIZE. --dry-run only validates the decision logic (which strings, what values) -
 * it never calls the API, so it can't confirm the batch request shape itself is accepted. Test with a small
 * --limit run before trusting this against the full backlog.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

import { branches, crowdinApi, projectId } from '@weareinreach/crowdin/api'
import { prisma } from '~db/client'

const APP_BASE_URL = process.env.APP_BASE_URL ?? 'https://app.inreach.org'
const BACKUP_DIR = path.join(__dirname, '..', 'crowdin-backups')

// Crowdin's documented cap on operations per batch-PATCH call is 100 as of this writing - verify against
// https://developer.crowdin.com/api/v2/#operation/api.projects.strings.batchPatch before relying on this.
const BATCH_SIZE = 100

const DRY_RUN = process.argv.includes('--dry-run')
const FORCE = process.argv.includes('--force')
const SAMPLE_SKIPPED = process.argv.includes('--sample-skipped')
const SAMPLE_SIZE = 15
const revertFlagIndex = process.argv.indexOf('--revert')
const REVERT_PATH = revertFlagIndex !== -1 ? process.argv[revertFlagIndex + 1] : undefined
const limitFlagIndex = process.argv.indexOf('--limit')
const LIMIT = limitFlagIndex !== -1 ? Number(process.argv[limitFlagIndex + 1]) : undefined

const chunk = <T>(items: T[], size: number): T[][] => {
	const chunks: T[][] = []
	for (let i = 0; i < items.length; i += size) {
		chunks.push(items.slice(i, i + size))
	}
	return chunks
}

type BackupEntry = { id: number; identifier: string; oldContext: string | null; newContext: string }

/**
 * Matches Crowdin's auto-generated fallback. In practice Crowdin populates this as BOTH the raw identifier
 * and the arrow-breadcrumb form, on separate lines (e.g. "orgn_xxx.osvc_xxx.name\norgn_xxx -> osvc_xxx ->
 * name") - so every line of the context must be one of those two known forms for it to count as
 * auto-generated. A context with any additional real line (e.g. a translator's note) is NOT auto-generated,
 * regardless of what else it contains.
 */
const isAutoGeneratedContext = (context: string | null | undefined, identifier: string): boolean => {
	if (!context) {
		return true
	}
	const breadcrumb = identifier.replaceAll('.', ' -> ').trim()
	const rawIdentifier = identifier.trim()
	return context
		.split('\n')
		.map((line) => line.trim())
		.every((line) => line === breadcrumb || line === rawIdentifier)
}

/**
 * Pulls the org ID (e.g. "orgn_01GVH3V92WRQC2VFANN0M43X71") out of a translation key like
 * "orgn_xxx.osvc_xxx.name".
 */
const extractOrgId = (identifier: string): string | undefined => {
	const match = /^(orgn_[A-Za-z0-9]+)/.exec(identifier)
	return match?.[1]
}

/**
 * Pulls a location ID (e.g. "oloc_01GVXX0WC3GWTZD880VP3FYCN1") out of a translation key, if present anywhere
 * in it - e.g. "orgn_xxx.oloc_xxx.name". Not currently produced by any known key-generation path, but handled
 * here so location-scoped strings get the more specific URL as soon as one exists.
 */
const extractLocationId = (identifier: string): string | undefined => {
	const match = /(oloc_[A-Za-z0-9]+)/.exec(identifier)
	return match?.[1]
}

/**
 * Builds the context URL for a string: the location page (org/<slug>/<oloc_id>) when the identifier includes
 * a location ID, otherwise the plain org page (org/<slug>) - covers org-level and service-level (osvc_) keys
 * alike, since services don't have their own page/anchor in the app.
 */
const buildContextUrl = (slug: string, locationId: string | undefined) =>
	locationId ? `${APP_BASE_URL}/org/${slug}/${locationId}` : `${APP_BASE_URL}/org/${slug}`

const writeBackup = (entries: BackupEntry[]) => {
	if (entries.length === 0) {
		return
	}
	mkdirSync(BACKUP_DIR, { recursive: true })
	const filename = `crowdin-context-backup-${new Date().toISOString().replace(/[:.]/g, '-')}.json`
	const filePath = path.join(BACKUP_DIR, filename)
	writeFileSync(filePath, JSON.stringify(entries, null, 2))
	console.log(`\nBacked up ${entries.length} previous context value(s) to ${filePath}`)
	console.log(`To revert: pnpm --filter @weareinreach/db crowdin:sync-context -- --revert ${filePath}`)
}

type CrowdinString = { id: number; identifier: string; context: string | null }

/** Pulls every string currently in the org-data (database) branch on Crowdin, one page at a time. */
const fetchAllStrings = async (): Promise<CrowdinString[]> => {
	const allStrings: CrowdinString[] = []
	let offset = 0
	const limit = 500
	for (;;) {
		const { data: page } = await crowdinApi.sourceStringsApi.listProjectStrings(projectId.dbContent, {
			branchId: branches.database,
			limit,
			offset,
		})
		if (page.length === 0) {
			break
		}
		for (const { data } of page) {
			allStrings.push({ id: data.id, identifier: data.identifier, context: data.context ?? null })
		}
		offset += limit
	}
	return allStrings
}

/** Builds a slug lookup for every org referenced by these strings, in one query. */
const buildSlugLookup = async (allStrings: CrowdinString[]) => {
	const orgIds = Array.from(
		new Set(allStrings.map((s) => extractOrgId(s.identifier)).filter((id): id is string => Boolean(id)))
	)
	const orgs = await prisma.organization.findMany({
		where: { id: { in: orgIds } },
		select: { id: true, slug: true },
	})
	return { slugById: new Map(orgs.map((o): [string, string] => [o.id, o.slug])), orgIdCount: orgIds.length }
}

type StringDecision =
	| { kind: 'skippedNoOrgMatch' }
	| { kind: 'skippedHasContext'; sample: { identifier: string; context: string | null } }
	| { kind: 'unchanged' }
	| { kind: 'needsUpdate'; id: number; identifier: string; oldContext: string | null; newContext: string }

/** Decides what (if anything) a single string needs. Pure - makes no network calls. */
const decideString = (str: CrowdinString, slugById: Map<string, string>): StringDecision => {
	const orgId = extractOrgId(str.identifier)
	if (!orgId) {
		console.warn(`Identifier doesn't start with an orgn_ id at all: "${str.identifier}"`)
		return { kind: 'skippedNoOrgMatch' }
	}
	const slug = slugById.get(orgId)
	if (!slug) {
		console.warn(`No org/slug found for identifier "${str.identifier}" (parsed org id: ${orgId})`)
		return { kind: 'skippedNoOrgMatch' }
	}

	if (!FORCE && !isAutoGeneratedContext(str.context, str.identifier)) {
		return { kind: 'skippedHasContext', sample: { identifier: str.identifier, context: str.context } }
	}

	const locationId = extractLocationId(str.identifier)
	const newContext = buildContextUrl(slug, locationId)
	if (str.context === newContext) {
		return { kind: 'unchanged' }
	}

	return { kind: 'needsUpdate', id: str.id, identifier: str.identifier, oldContext: str.context, newContext }
}

type PendingUpdate = { id: number; identifier: string; oldContext: string | null; newContext: string }

/**
 * Applies one batch of updates via a single stringBatchOperations() call. Returns the backup entries for
 * everything in the batch on success. On failure, logs which string ids were affected and returns none -
 * Crowdin's batch endpoint's partial-failure behavior isn't verified, so treat the whole batch as
 * indeterminate rather than guessing; re-running the script later safely picks up anything not actually
 * applied, since already-updated strings are skipped on the next pass.
 */
const applyBatch = async (batch: PendingUpdate[]): Promise<BackupEntry[]> => {
	const ops = batch.map(({ id, newContext }) => ({
		op: 'replace' as const,
		path: `/${id}/context`,
		value: newContext,
	}))
	try {
		await crowdinApi.sourceStringsApi.stringBatchOperations(projectId.dbContent, ops)
		return batch.map(({ id, identifier, oldContext, newContext }) => ({
			id,
			identifier,
			oldContext,
			newContext,
		}))
	} catch (err) {
		console.error(
			`Batch of ${batch.length} failed (string ids: ${batch.map((b) => b.id).join(', ')}). Re-run this ` +
				`script later to safely retry - already-applied strings are skipped automatically. Error:`,
			err
		)
		return []
	}
}

const run = async () => {
	console.log(`Starting Crowdin context sync (dryRun=${DRY_RUN}, force=${FORCE})`)

	// 1. Pull every string currently in the org-data (database) branch on Crowdin.
	const allStrings = await fetchAllStrings()
	console.log(
		`Fetched ${allStrings.length} strings from Crowdin (project ${projectId.dbContent}, branch ${branches.database})`
	)

	// 2. Build a slug lookup for every org referenced by these strings, in one query.
	const { slugById, orgIdCount } = await buildSlugLookup(allStrings)
	console.log(`Resolved ${slugById.size}/${orgIdCount} organization slugs`)

	// 3. Decide what every string needs. Pure/local - no network calls yet.
	let skippedHasContext = 0
	let skippedNoOrgMatch = 0
	const skippedHasContextSample: Array<{ identifier: string; context: string | null }> = []
	const pendingUpdates: PendingUpdate[] = []

	for (const str of allStrings) {
		const decision = decideString(str, slugById)
		switch (decision.kind) {
			case 'skippedNoOrgMatch': {
				skippedNoOrgMatch++
				break
			}
			case 'skippedHasContext': {
				skippedHasContext++
				if (SAMPLE_SKIPPED && skippedHasContextSample.length < SAMPLE_SIZE) {
					skippedHasContextSample.push(decision.sample)
				}
				break
			}
			case 'unchanged': {
				break
			}
			case 'needsUpdate': {
				pendingUpdates.push(decision)
				break
			}
		}
	}

	const updatesToApply = LIMIT ? pendingUpdates.slice(0, LIMIT) : pendingUpdates
	if (LIMIT) {
		console.log(
			`--limit ${LIMIT}: applying ${updatesToApply.length}/${pendingUpdates.length} pending updates`
		)
	}

	// 4. Apply the change, batched (see the file header comment for why batching over editString()).
	let updated = 0
	const backupEntries: BackupEntry[] = []

	if (DRY_RUN) {
		for (const { identifier, newContext } of updatesToApply) {
			console.log(`[dry-run] Would set context for "${identifier}" -> "${newContext}"`)
		}
		updated = updatesToApply.length
	} else {
		const batches = chunk(updatesToApply, BATCH_SIZE)
		console.log(
			`Applying ${updatesToApply.length} update(s) in ${batches.length} batch(es) of up to ${BATCH_SIZE}`
		)
		try {
			for (const [i, batch] of batches.entries()) {
				const applied = await applyBatch(batch)
				backupEntries.push(...applied)
				updated += applied.length
				const percentComplete = (((i + 1) / batches.length) * 100).toFixed(1)
				console.log(
					`Batch ${i + 1}/${batches.length} (${percentComplete}%): ${applied.length}/${batch.length} applied ` +
						`- ${updated}/${updatesToApply.length} total`
				)
			}
		} finally {
			// Persist whatever was actually written, even if the loop above throws partway through - a partial
			// backup is still a valid revert path for everything that did get changed.
			writeBackup(backupEntries)
		}
	}

	console.log('Done.')
	console.log(`  Updated:            ${updated}`)
	console.log(`  Skipped (has real context, use --force to override): ${skippedHasContext}`)
	console.log(`  Skipped (no matching org):                          ${skippedNoOrgMatch}`)

	if (SAMPLE_SKIPPED && skippedHasContextSample.length > 0) {
		console.log(`\nSample of ${skippedHasContextSample.length} skipped "already has real context" strings:`)
		for (const { identifier, context } of skippedHasContextSample) {
			console.log(`  "${identifier}" -> ${JSON.stringify(context)}`)
		}
	}
}

/**
 * Reverts a prior run's changes from its backup file.
 *
 * The two `console.log` calls below that read from `entries` each trip SonarCloud's "confidential data should
 * not be logged" rule (tssecurity:S8689). That rule treats any `readFileSync` result as unconditionally
 * "credential data" (password/API key/secret/token) without inspecting what the file actually contains - and
 * no amount of extracting values into intermediate variables changes that, since the taint tracking follows
 * dataflow through assignment. `backupPath` here only ever points at this same script's own backup JSON
 * (Crowdin string ids, org-data key identifiers, and public context URLs written by writeBackup() above) -
 * never a secrets/credentials file - so there is nothing confidential to leak.
 */
const revert = async (backupPath: string) => {
	console.log(`Reverting from ${backupPath} (dryRun=${DRY_RUN})`)
	const entries: BackupEntry[] = JSON.parse(readFileSync(backupPath, 'utf-8'))
	console.log(`Loaded ${entries.length} entries to revert`) // NOSONAR - see function comment

	let reverted = 0
	for (const entry of entries) {
		if (DRY_RUN) {
			console.log(`[dry-run] Would restore "${entry.identifier}" -> ${JSON.stringify(entry.oldContext)}`) // NOSONAR - see function comment
			reverted++
			continue
		}
		await crowdinApi.sourceStringsApi.editString(projectId.dbContent, entry.id, [
			{ op: 'replace', path: '/context', value: entry.oldContext ?? '' },
		])
		reverted++
	}
	console.log('Done.')
	console.log(`  Reverted: ${reverted}`)
}

;(REVERT_PATH ? revert(REVERT_PATH) : run())
	.catch((err) => {
		console.error('Crowdin context sync failed:', err)
		process.exitCode = 1
	})
	.finally(async () => {
		await prisma.$disconnect()
	})
