/* eslint-disable node/no-process-env */

/**
 * Packages/db/lib/syncCrowdinContext.ts
 *
 * Standalone, additive script. Does not modify any existing Crowdin API function or mutation handler.
 *
 * Lives in packages/db (not packages/crowdin) because it needs both Prisma and the Crowdin API client, and
 * packages/db already depends on @weareinreach/crowdin - the reverse dependency would create a cycle.
 *
 * Purpose: Populate the Crowdin `context` field for org-data strings with a direct link to the corresponding
 * organization (and, for location-scoped strings, the specific location) in the live app - e.g.
 * https://app.inreach.org/org/<slug> or https://app.inreach.org/org/<slug>/<oloc_id> - replacing Crowdin's
 * auto-generated identifier-breadcrumb fallback ("orgn_xxx -> osvc_xxx -> name").
 *
 * Safe to re-run: strings that already have a real (non-breadcrumb) context are skipped by default.
 *
 * Before writing anything for real, every changed string's PREVIOUS context is backed up to a timestamped
 * JSON file under packages/db/crowdin-backups/ - use --revert <path> to restore from one if needed.
 *
 * Usage (local): pnpm --filter @weareinreach/db crowdin:sync-context pnpm --filter @weareinreach/db
 * crowdin:sync-context -- --dry-run pnpm --filter @weareinreach/db crowdin:sync-context -- --force (overwrite
 * even non-breadcrumb context) pnpm --filter @weareinreach/db crowdin:sync-context -- --dry-run
 * --sample-skipped (print a sample of strings being skipped because they already look like they have real
 * context - useful for sanity- checking that isAutoGeneratedContext isn't over-matching) pnpm --filter
 * @weareinreach/db crowdin:sync-context -- --revert ./crowdin-backups/<file>.json pnpm --filter
 * @weareinreach/db crowdin:sync-context -- --revert ./crowdin-backups/<file>.json --dry-run
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

import { branches, crowdinApi, projectId } from '@weareinreach/crowdin/api'
import { prisma } from '~db/client'

const APP_BASE_URL = process.env.APP_BASE_URL ?? 'https://app.inreach.org'
const BACKUP_DIR = path.join(__dirname, '..', 'crowdin-backups')

const DRY_RUN = process.argv.includes('--dry-run')
const FORCE = process.argv.includes('--force')
const SAMPLE_SKIPPED = process.argv.includes('--sample-skipped')
const SAMPLE_SIZE = 15
const revertFlagIndex = process.argv.indexOf('--revert')
const REVERT_PATH = revertFlagIndex !== -1 ? process.argv[revertFlagIndex + 1] : undefined

type BackupEntry = { id: number; identifier: string; oldContext: string | null; newContext: string }

/**
 * Matches Crowdin's auto-generated fallback. In practice Crowdin populates this as BOTH the raw identifier
 * and the arrow-breadcrumb form, on separate lines (e.g. "orgn_xxx.osvc_xxx.name\norgn_xxx -> osvc_xxx ->
 * name") - so every line of the context must be one of those two known forms for it to count as
 * auto-generated. A context with any additional real line (e.g. a translator's note) is NOT auto-generated,
 * regardless of what else it contains.
 */
const isAutoGeneratedContext = (context: string | null | undefined, identifier: string): boolean => {
	if (!context) {
		return true
	}
	const breadcrumb = identifier.replaceAll('.', ' -> ').trim()
	const rawIdentifier = identifier.trim()
	return context
		.split('\n')
		.map((line) => line.trim())
		.every((line) => line === breadcrumb || line === rawIdentifier)
}

/**
 * Pulls the org ID (e.g. "orgn_01GVH3V92WRQC2VFANN0M43X71") out of a translation key like
 * "orgn_xxx.osvc_xxx.name".
 */
const extractOrgId = (identifier: string): string | undefined => {
	const match = /^(orgn_[A-Za-z0-9]+)/.exec(identifier)
	return match?.[1]
}

/**
 * Pulls a location ID (e.g. "oloc_01GVXX0WC3GWTZD880VP3FYCN1") out of a translation key, if present anywhere
 * in it - e.g. "orgn_xxx.oloc_xxx.name". Not currently produced by any known key-generation path, but handled
 * here so location-scoped strings get the more specific URL as soon as one exists.
 */
const extractLocationId = (identifier: string): string | undefined => {
	const match = /(oloc_[A-Za-z0-9]+)/.exec(identifier)
	return match?.[1]
}

/**
 * Builds the context URL for a string: the location page (org/<slug>/<oloc_id>) when the identifier includes
 * a location ID, otherwise the plain org page (org/<slug>) - covers org-level and service-level (osvc_) keys
 * alike, since services don't have their own page/anchor in the app.
 */
const buildContextUrl = (slug: string, locationId: string | undefined) =>
	locationId ? `${APP_BASE_URL}/org/${slug}/${locationId}` : `${APP_BASE_URL}/org/${slug}`

const writeBackup = (entries: BackupEntry[]) => {
	if (entries.length === 0) {
		return
	}
	mkdirSync(BACKUP_DIR, { recursive: true })
	const filename = `crowdin-context-backup-${new Date().toISOString().replace(/[:.]/g, '-')}.json`
	const filePath = path.join(BACKUP_DIR, filename)
	writeFileSync(filePath, JSON.stringify(entries, null, 2))
	console.log(`\nBacked up ${entries.length} previous context value(s) to ${filePath}`)
	console.log(`To revert: pnpm --filter @weareinreach/db crowdin:sync-context -- --revert ${filePath}`)
}

type CrowdinString = { id: number; identifier: string; context: string | null }

/** Pulls every string currently in the org-data (database) branch on Crowdin, one page at a time. */
const fetchAllStrings = async (): Promise<CrowdinString[]> => {
	const allStrings: CrowdinString[] = []
	let offset = 0
	const limit = 500
	for (;;) {
		const { data: page } = await crowdinApi.sourceStringsApi.listProjectStrings(projectId.dbContent, {
			branchId: branches.database,
			limit,
			offset,
		})
		if (page.length === 0) {
			break
		}
		for (const { data } of page) {
			allStrings.push({ id: data.id, identifier: data.identifier, context: data.context ?? null })
		}
		offset += limit
	}
	return allStrings
}

/** Builds a slug lookup for every org referenced by these strings, in one query. */
const buildSlugLookup = async (allStrings: CrowdinString[]) => {
	const orgIds = Array.from(
		new Set(allStrings.map((s) => extractOrgId(s.identifier)).filter((id): id is string => Boolean(id)))
	)
	const orgs = await prisma.organization.findMany({
		where: { id: { in: orgIds } },
		select: { id: true, slug: true },
	})
	return { slugById: new Map(orgs.map((o): [string, string] => [o.id, o.slug])), orgIdCount: orgIds.length }
}

type ProcessResult =
	| { kind: 'skippedNoOrgMatch' }
	| { kind: 'skippedHasContext'; sample: { identifier: string; context: string | null } }
	| { kind: 'unchanged' }
	| { kind: 'dryRunUpdate' }
	| { kind: 'updated'; backupEntry: BackupEntry }

/** Decides what (if anything) a single string needs, and applies it. */
const processString = async (str: CrowdinString, slugById: Map<string, string>): Promise<ProcessResult> => {
	const orgId = extractOrgId(str.identifier)
	if (!orgId) {
		console.warn(`Identifier doesn't start with an orgn_ id at all: "${str.identifier}"`)
		return { kind: 'skippedNoOrgMatch' }
	}
	const slug = slugById.get(orgId)
	if (!slug) {
		console.warn(`No org/slug found for identifier "${str.identifier}" (parsed org id: ${orgId})`)
		return { kind: 'skippedNoOrgMatch' }
	}

	if (!FORCE && !isAutoGeneratedContext(str.context, str.identifier)) {
		return { kind: 'skippedHasContext', sample: { identifier: str.identifier, context: str.context } }
	}

	const locationId = extractLocationId(str.identifier)
	const newContext = buildContextUrl(slug, locationId)
	if (str.context === newContext) {
		return { kind: 'unchanged' }
	}

	if (DRY_RUN) {
		console.log(`[dry-run] Would set context for "${str.identifier}" -> "${newContext}"`)
		return { kind: 'dryRunUpdate' }
	}

	await crowdinApi.sourceStringsApi.editString(projectId.dbContent, str.id, [
		{ op: 'replace', path: '/context', value: newContext },
	])
	return {
		kind: 'updated',
		backupEntry: { id: str.id, identifier: str.identifier, oldContext: str.context, newContext },
	}
}

const run = async () => {
	console.log(`Starting Crowdin context sync (dryRun=${DRY_RUN}, force=${FORCE})`)

	// 1. Pull every string currently in the org-data (database) branch on Crowdin.
	const allStrings = await fetchAllStrings()
	console.log(
		`Fetched ${allStrings.length} strings from Crowdin (project ${projectId.dbContent}, branch ${branches.database})`
	)

	// 2. Build a slug lookup for every org referenced by these strings, in one query.
	const { slugById, orgIdCount } = await buildSlugLookup(allStrings)
	console.log(`Resolved ${slugById.size}/${orgIdCount} organization slugs`)

	// 3. Walk every string, decide whether it needs updating, and apply the change.
	let updated = 0
	let skippedHasContext = 0
	let skippedNoOrgMatch = 0
	const skippedHasContextSample: Array<{ identifier: string; context: string | null }> = []
	const backupEntries: BackupEntry[] = []

	try {
		for (const str of allStrings) {
			const result = await processString(str, slugById)
			switch (result.kind) {
				case 'skippedNoOrgMatch': {
					skippedNoOrgMatch++
					break
				}
				case 'skippedHasContext': {
					skippedHasContext++
					if (SAMPLE_SKIPPED && skippedHasContextSample.length < SAMPLE_SIZE) {
						skippedHasContextSample.push(result.sample)
					}
					break
				}
				case 'unchanged': {
					break
				}
				case 'dryRunUpdate': {
					updated++
					break
				}
				case 'updated': {
					backupEntries.push(result.backupEntry)
					updated++
					break
				}
			}
		}
	} finally {
		// Persist whatever was actually written, even if the loop above throws partway through - a partial
		// backup is still a valid revert path for everything that did get changed.
		if (!DRY_RUN) {
			writeBackup(backupEntries)
		}
	}

	console.log('Done.')
	console.log(`  Updated:            ${updated}`)
	console.log(`  Skipped (has real context, use --force to override): ${skippedHasContext}`)
	console.log(`  Skipped (no matching org):                          ${skippedNoOrgMatch}`)

	if (SAMPLE_SKIPPED && skippedHasContextSample.length > 0) {
		console.log(`\nSample of ${skippedHasContextSample.length} skipped "already has real context" strings:`)
		for (const { identifier, context } of skippedHasContextSample) {
			console.log(`  "${identifier}" -> ${JSON.stringify(context)}`)
		}
	}
}

const revert = async (backupPath: string) => {
	console.log(`Reverting from ${backupPath} (dryRun=${DRY_RUN})`)
	const entries: BackupEntry[] = JSON.parse(readFileSync(backupPath, 'utf-8'))
	const entryCount = entries.length
	console.log(`Loaded ${entryCount} entries to revert`)

	let reverted = 0
	for (const entry of entries) {
		if (DRY_RUN) {
			console.log(`[dry-run] Would restore "${entry.identifier}" -> ${JSON.stringify(entry.oldContext)}`)
			reverted++
			continue
		}
		await crowdinApi.sourceStringsApi.editString(projectId.dbContent, entry.id, [
			{ op: 'replace', path: '/context', value: entry.oldContext ?? '' },
		])
		reverted++
	}
	console.log('Done.')
	console.log(`  Reverted: ${reverted}`)
}

;(REVERT_PATH ? revert(REVERT_PATH) : run())
	.catch((err) => {
		console.error('Crowdin context sync failed:', err)
		process.exitCode = 1
	})
	.finally(async () => {
		await prisma.$disconnect()
	})
