import { z } from 'zod'

// Generated by https://quicktype.io
export interface OrgData {
	_id: {
		$oid: string
	}
	is_published: boolean
	name: string
	emails: {
		_id: {
			$oid: string
		}
		show_on_organization?: boolean
	}[]
	locations: {
		_id: {
			$oid: string
		}
		show_on_organization?: boolean
	}[]
	phones: {
		_id: {
			$oid: string
		}
		show_on_organization?: boolean
	}[]
	services: {
		is_published: boolean
		is_deleted: boolean
		_id: {
			$oid: string
		}
	}[]
	is_deleted: boolean
}

// Generated by ts-to-zod
export const orgDataSchema = z
	.object({
		_id: z.object({
			$oid: z.string(),
		}),
		is_published: z.boolean(),
		name: z.string(),
		emails: z.array(
			z.object({
				_id: z.object({
					$oid: z.string(),
				}),
				show_on_organization: z.boolean().optional(),
			})
		),
		locations: z.array(
			z.object({
				_id: z.object({
					$oid: z.string(),
				}),
				show_on_organization: z.boolean().optional(),
			})
		),
		phones: z.array(
			z.object({
				_id: z.object({
					$oid: z.string(),
				}),
				show_on_organization: z.boolean().optional(),
			})
		),
		services: z.array(
			z.object({
				is_published: z.boolean(),
				is_deleted: z.boolean(),
				_id: z.object({
					$oid: z.string(),
				}),
			})
		),
		is_deleted: z.boolean(),
	})
	.array()
