import { groq } from 'next-sanity'

// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface GetNavByPageResult {
	menuLabel: string | null
	subMenuLabel: string | null
}

export const getNavByPage = groq`
*[_id == 'site-navigation'].mainNavigation[references($id)]{
    'menuLabel': menuLabel[0].value,
    'subMenuLabel': subMenuItemLabel[0].value
}`
