/* eslint-disable node/no-process-env */

/**
 * Packages/crowdin/api/syncContext.ts
 *
 * Standalone, additive script. Does not modify any existing Crowdin API function or mutation handler.
 *
 * Purpose: Populate the Crowdin `context` field for org-data strings with a direct link to the corresponding
 * organization in the live app (e.g. https://app.inreach.org/org/<slug>), replacing Crowdin's auto-generated
 * identifier-breadcrumb fallback ("orgn_xxx -> osvc_xxx -> name").
 *
 * Safe to re-run: strings that already have a real (non-breadcrumb) context are skipped by default.
 *
 * Usage (local): pnpm tsx packages/crowdin/api/syncContext.ts pnpm tsx packages/crowdin/api/syncContext.ts
 * --dry-run pnpm tsx packages/crowdin/api/syncContext.ts --force (overwrite even non-breadcrumb context)
 */

import { prisma } from '@weareinreach/db/client'

import { branches, projectId } from '../constants'
import { crowdinApi } from './index'

const APP_BASE_URL = process.env.APP_BASE_URL ?? 'https://app.inreach.org'

const DRY_RUN = process.argv.includes('--dry-run')
const FORCE = process.argv.includes('--force')

/** Matches Crowdin's auto-generated fallback, e.g. "orgn_xxx -> osvc_xxx -> name" (also tolerates a
single-segment key with no arrows). */
const isAutoGeneratedContext = (context: string | null | undefined, identifier: string): boolean => {
	if (!context) return true
	const breadcrumb = identifier.split('.').join(' -> ')
	return context.trim() === breadcrumb.trim() || context.trim() === identifier.trim()
}

/** Pulls the org ID (e.g. "orgn_01GVH3V92WRQC2VFANN0M43X71") out of a translation key like
"orgn_xxx.osvc_xxx.name". */
const extractOrgId = (identifier: string): string | undefined => {
	const match = identifier.match(/^(orgn_[A-Za-z0-9]+)/)
	return match?.[1]
}

const buildOrgUrl = (slug: string) => `${APP_BASE_URL}/org/${slug}`

const run = async () => {
	console.log(`Starting Crowdin context sync (dryRun=${DRY_RUN}, force=${FORCE})`)

	// 1. Pull every string currently in the org-data (database) branch on Crowdin.
	const allStrings: Array<{ id: number; identifier: string; context: string | null }> = []
	let offset = 0
	const limit = 500
	// eslint-disable-next-line no-constant-condition
	while (true) {
		const { data: page } = await crowdinApi.sourceStringsApi.listProjectStrings(projectId.dbContent, {
			branchId: branches.database,
			limit,
			offset,
		})
		if (page.length === 0) break
		for (const { data } of page) {
			allStrings.push({ id: data.id, identifier: data.identifier, context: data.context ?? null })
		}
		offset += limit
	}
	console.log(
		`Fetched ${allStrings.length} strings from Crowdin (project ${projectId.dbContent}, branch ${branches.database})`
	)

	// 2. Build a slug lookup for every org referenced by these strings, in one query.
	const orgIds = Array.from(
		new Set(allStrings.map((s) => extractOrgId(s.identifier)).filter((id): id is string => Boolean(id)))
	)
	const orgs = await prisma.organization.findMany({
		where: { id: { in: orgIds } },
		select: { id: true, slug: true },
	})
	const slugById = new Map(orgs.map((o) => [o.id, o.slug]))
	console.log(`Resolved ${slugById.size}/${orgIds.length} organization slugs`)

	// 3. Walk every string, decide whether it needs updating, and apply the change.
	let updated = 0
	let skippedHasContext = 0
	let skippedNoOrgMatch = 0

	for (const str of allStrings) {
		const orgId = extractOrgId(str.identifier)
		if (!orgId) {
			skippedNoOrgMatch++
			continue
		}
		const slug = slugById.get(orgId)
		if (!slug) {
			console.warn(`No org/slug found for identifier "${str.identifier}" (parsed org id: ${orgId})`)
			skippedNoOrgMatch++
			continue
		}

		if (!FORCE && !isAutoGeneratedContext(str.context, str.identifier)) {
			skippedHasContext++
			continue
		}

		const newContext = buildOrgUrl(slug)
		if (str.context === newContext) {
			continue
		}

		if (DRY_RUN) {
			console.log(`[dry-run] Would set context for "${str.identifier}" -> "${newContext}"`)
			updated++
			continue
		}

		await crowdinApi.sourceStringsApi.editString(projectId.dbContent, str.id, [
			{ op: 'replace', path: '/context', value: newContext },
		])
		updated++
	}

	console.log('Done.')
	console.log(`  Updated:            ${updated}`)
	console.log(`  Skipped (has real context, use --force to override): ${skippedHasContext}`)
	console.log(`  Skipped (no matching org):                          ${skippedNoOrgMatch}`)
}

run()
	.catch((err) => {
		console.error('Crowdin context sync failed:', err)
		process.exitCode = 1
	})
	.finally(async () => {
		await prisma.$disconnect()
	})
