-- AlterTable
ALTER TABLE "Account" ALTER COLUMN "providerAccountId" SET DATA TYPE VARCHAR(128);

-- AlterTable
ALTER TABLE "Country" ALTER COLUMN "name" SET DATA TYPE VARCHAR(128);

-- AlterTable
ALTER TABLE "CountryTranslation" ALTER COLUMN "name" SET DATA TYPE VARCHAR(128);

-- AlterTable
ALTER TABLE "OrgEmail" ALTER COLUMN "firstName" SET DATA TYPE VARCHAR(128),
ALTER COLUMN "lastName" SET DATA TYPE VARCHAR(128),
ALTER COLUMN "email" SET DATA TYPE VARCHAR(128);

-- AlterTable
ALTER TABLE "OrgPhotos" ALTER COLUMN "foursquareId" SET DATA TYPE VARCHAR(128);

-- AlterTable
ALTER TABLE "OrgSocialMedia" ALTER COLUMN "username" SET DATA TYPE VARCHAR(128);

-- AlterTable
ALTER TABLE "OrgSource" ALTER COLUMN "source" SET DATA TYPE VARCHAR(128);

-- AlterTable
ALTER TABLE "Organization" ALTER COLUMN "name" SET DATA TYPE VARCHAR(128);

-- AlterTable
ALTER TABLE "TranslationItem" ALTER COLUMN "tagName" SET DATA TYPE VARCHAR(128);

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "name" SET DATA TYPE VARCHAR(128),
ALTER COLUMN "email" SET DATA TYPE VARCHAR(128);

-- AlterTable
ALTER TABLE "UserCommunity" ALTER COLUMN "community" SET DATA TYPE VARCHAR(128);

-- AlterTable
ALTER TABLE "UserEthnicity" ALTER COLUMN "ethnicity" SET DATA TYPE VARCHAR(128);

-- AlterTable
ALTER TABLE "UserImmigration" ALTER COLUMN "status" SET DATA TYPE VARCHAR(128);

-- AlterTable
ALTER TABLE "UserList" ALTER COLUMN "name" SET DATA TYPE VARCHAR(128);

-- AlterTable
ALTER TABLE "UserRole" ALTER COLUMN "name" SET DATA TYPE VARCHAR(128);

-- AlterTable
ALTER TABLE "UserSOG" ALTER COLUMN "sog" SET DATA TYPE VARCHAR(128);

-- AlterTable
ALTER TABLE "UserTitle" ALTER COLUMN "text" SET DATA TYPE VARCHAR(128);
