import { z } from 'zod'

export const OrgAttributesSchema = z.object({
	'private-practice': z.array(
		z.object({
			legacyId: z.string(),
		})
	),
	'religiously-affiliated': z.array(
		z.object({
			legacyId: z.string(),
		})
	),

	'women-led': z.array(
		z.object({
			legacyId: z.string(),
		})
	),
})
export const ServAttributesSchema = z.object({
	'caregivers-focus': z.array(
		z.object({
			legacyId: z.string(),
			legacyServiceId: z.string(),
		})
	),
	'disabled-focus': z.array(
		z.object({
			legacyId: z.string(),
			legacyServiceId: z.string(),
		})
	),
	'elder-focus': z.array(
		z.object({
			legacyId: z.string(),
			legacyServiceId: z.string(),
		})
	),
	'incarcerated-focus': z.array(
		z.object({
			legacyId: z.string(),
			legacyServiceId: z.string(),
		})
	),
	'women-focus': z.array(
		z.object({
			legacyId: z.string(),
			legacyServiceId: z.string(),
		})
	),
})
export const ServiceTagsSchema = z.object({
	'community-support.community-social-groups': z.array(
		z.object({
			legacyId: z.string(),
			legacyServiceId: z.string(),
		})
	),
	'community-support.reentry-services': z.array(
		z.object({
			legacyId: z.string(),
			legacyServiceId: z.string(),
		})
	),
	'sports-and-entertainment.art-music-literature': z.array(
		z.object({
			legacyId: z.string(),
			legacyServiceId: z.string(),
		})
	),
})

// Generated by https://quicktype.io

export interface Attributes {
	'caregivers-focus': {
		legacyId: string
		legacyServiceId: null | string
	}[]
	'disabled-focus': {
		legacyId: string
		legacyServiceId: null | string
	}[]
	'elder-focus': {
		legacyId: string
		legacyServiceId: null | string
	}[]
	'incarcerated-focus': {
		legacyId: string
		legacyServiceId: null | string
	}[]
	'offers-remote-services': {
		legacyId: string
		legacyServiceId: null | string
	}[]
	'private-practice': { legacyId: string }[]
	'religiously-affiliated': { legacyId: string }[]
	'women-focus': {
		legacyId: string
		legacyServiceId: null | string
	}[]
	'women-led': { legacyId: string }[]
}

// Generated by https://quicktype.io

export interface ServiceTags {
	'community-support.community-social-groups': {
		legacyId: string
		legacyServiceId: string
	}[]
	'community-support.reentry-services': {
		legacyId: string
		legacyServiceId: string
	}[]
	'sports-and-entertainment.art-music-literature': {
		legacyId: string
		legacyServiceId: string
	}[]
}
