version = 0.1
[default.deploy.parameters]
stack_name = "cognito-messaging"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-i42qqmsezts8"
s3_prefix = "cognito-messaging"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
