AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Cognito user migration script.

Globals:
  Function:
    Runtime: nodejs18.x
    CodeUri: ./dist/
    Timeout: 60
    MemorySize: 512
    Architectures:
      - x86_64

Resources:
  usermigrate:
    Type: 'AWS::Serverless::Function'
    # Metadata:
    #   BuildMethod: makefile
    Properties:
      FunctionName: 'cognito-user-migrate'
      Handler: dist/index.handler
      Role: arn:aws:iam::142495371698:role/cognito-migration-lambda
      Environment:
        Variables:
          DATABASE_URL: '{{resolve:ssm:/prod/inreach-prod}}'
          DB_DIRECT_URL: '{{resolve:ssm:/prod/inreach-prod}}'
  # runtimeDepsLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   Metadata:
  #     BuildMethod: makefile
  #   Properties:
  #     LayerName: "usermigrate-dependencies"
  #     ContentUri: ./
  #     CompatibleRuntimes:
  #       - nodejs18.x
  #     RetentionPolicy: Retain
