// codegen:start {preset: barrel, include: ./*.schema.ts}
export * from './mutation.attachAttribute.schema'
export * from './mutation.createNewQuick.schema'
export * from './mutation.createNewSuggestion.schema'
export * from './mutation.updateAttributesBasic.schema'
export * from './mutation.updateBasic.schema'
export * from './query.checkForExisting.schema'
export * from './query.forBadgeEditModal.schema'
export * from './query.forLocationPage.schema'
export * from './query.forOrganizationTable.schema'
export * from './query.forOrgPage.schema'
export * from './query.forOrgPageEdits.schema'
export * from './query.generateSlug.schema'
export * from './query.getAlerts.schema'
export * from './query.getAllPublishedForCSV.schema'
export * from './query.getAllUnpublishedForCSV.schema'
export * from './query.getAttributes.schema'
export * from './query.getById.schema'
export * from './query.getBySlug.schema'
export * from './query.getIdFromSlug.schema'
export * from './query.getIntlCrisis.schema'
export * from './query.getNameFromSlug.schema'
export * from './query.getNatlCrisis.schema'
export * from './query.isSaved.schema'
export * from './query.searchDistance.schema'
export * from './query.searchName.schema'
export * from './query.slugRedirect.schema'
// codegen:end
