name: '🤖 PR Auto Approve'
on:
  pull_request:
    types: [review_requested]

permissions:
  pull-requests: write
  checks: write
  contents: write
  statuses: read

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    name: '🤖 PR Auto Approve'
    steps:
      - uses: github/privileged-requester@f8d60d9344e1c10976aad5c1af0c7c977badd677 # v2.1.0
        if: ${{ github.event.requested_reviewer.login == 'InReach-svc'}}
        with:
          github_token: ${{ secrets.GH_ACT_PAT }}
          path: .github/autoapprove-config.yaml
          checkCommits: 'false'
          checkDiff: 'false'
          checkLabels: 'false'
