name: '🤖 PR Auto Approve'
on:
  pull_request:
    types: [review_requested]

permissions:
  pull-requests: write
  checks: write
  contents: write
  statuses: read

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    name: '🤖 PR Auto Approve'
    steps:
      - uses: github/privileged-requester@ceea3f40bfb3ddaa2aabd3d19377eb2457a20c1a # v2.3.4
        if: ${{ github.event.requested_reviewer.login == 'InReach-svc'}}
        with:
          github_token: ${{ secrets.GH_ACT_PAT }}
          path: .github/autoapprove-config.yaml
          checkCommits: 'false'
          checkDiff: 'false'
          checkLabels: 'false'
