name: 'PR Auto Approve'
on:
  pull_request:
    types: [review_requested]

permissions:
  pull-requests: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: github/privileged-requester@91ebaf95f94bf27577b474f91936815d0f98138e # v1.0.1
        if: ${{ github.event.requested_reviewer.login == 'InReach-svc'}}
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          robotUserToken: ${{ secrets.GH_ACT_PAT }}
          path: .github/autoapprove-config.yaml
          prCreator: ${{ github.event.pull_request.user.login }}
          prNumber: ${{ github.event.pull_request.number }}
          checkCommits: 'false'
          checkDiff: 'false'
          checkLabels: 'false'
