name: Cypress Steps Validation
on: [pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3
      - name: Install PNPM
        run: npm i -g pnpm
      - name: Cypress run
        uses: cypress-io/github-action@30008f1458a5a2c97054bfe118fe33d75976c482 # v4.2.0
        with:
          command: npm run cypress:run:steps
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
