name: Sync branch
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  sync-branch:
    name: Update dev branch
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - name: Checkout repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - uses: connor-baer/action-sync-branch@4f44fe844a1a3f53676699cfe74453820a38ca65 # main
        with:
          branch: dev
          token: ${{ secrets.GH_ACT_PAT }}
          force: false
